;-------------------------------------------------------------------------------
.extern	ANNOUNCE_NUM

.extern	B_VOP
.extern	BEEP
.extern	BEEP_START
.extern	BEEP_STOP
.extern	BBEEP
.extern	BBBEEP
.extern	BB_VOP
.extern	LBEEP

.extern	BCVOX_INIT
.extern	BLED_ON
.extern	BLED_OFF
;.extern	CLR_BUSY_FG

.extern	CLR_FUNC
.extern	CLR_LED1FG
.extern	CLR_MSG
.extern	CLR_TIMER

.extern	COMP_ALLTELNUM
.extern	CONCEN_DAT

.extern	DAA_OFF
.extern	DAA_REC
.extern	DAA_SPK
.extern	DAA_BSPK
.extern	DAA_ANS_SPK
.extern	DAA_ANS_REC
.extern	DAA_LIN_REC
.extern	DAA_LIN_SPK
.extern	DAA_TWAY_REC
.extern	DAM_BIOSFUNC

.extern	DAT_WRITE
.extern	DAT_WRITE_STOP
.extern	DECONCEN_DAT
;.extern	DEFATT_WRITE
.extern	DATETIME_WRITE
.extern	DEFOGM_LOCALPLY
.extern	DEL_ALLTEL
.extern	DEL_ONETEL
.extern	DELAY


.extern	GC_CHK
.extern	GET_INITLANGUAGE
.extern	GET_LANGUAGE
.extern	GET_ONLYID
.extern	GET_ONLYIDNEW
.extern	GET_USRDAT
.extern	GET_USRDATNEW
.extern	GET_TELID
.extern	GET_TELT
.extern	GET_TOTALMSG
.extern	GET_VPTLEN

.extern	GETBYTE_DAT

;.extern	HEXDIV
.extern	HOOK_OFF
.extern	HOOK_ON

.extern	INIT_DAM_FUNC

.extern	LINE_START

.extern	MEMFULL_CHK
.extern	MOVE_HTOL
.extern	MOVE_LTOH


.extern	NEWICM_CHK

.extern	OGM_SELECT
.extern	OGM_STATUS

.extern	RAM_STOR
.extern	REC_START
.extern	READ_TELNUM
.extern	REAL_DEL

.extern	SEND_DAT
.extern	SEND_HHMMSS
;.extern	SEND_MSGNUM
.extern	SENDLANGUAGE
.extern	SENDLOCACODE
.extern	SET_COMPS
.extern	SET_DECLTEL



.extern	SET_SILENCE
.extern	SET_TIMER
.extern	SET_TELGROUP
.extern	SET_TELUSRDAT
.extern	SET_USRDAT
.extern	SET_USRDAT1
.extern	STOPREADDAT
.extern	STORBYTE_DAT
.extern	STOR_MSG
.extern	STOR_VP

.extern	TEL_GC_CHK
.extern	TEL_SENDCOMM
.extern	TELNUMALL_DEL
.extern	TELNUM_WRITE
.extern	TOSENDBUF

.extern	VALUE_ADD
.extern	VALUE_SUB
.extern	VPMSG_CHK
;-------------------------------------------------------------------------------
.extern	VP_ENDOF
.extern	VP_MAILBOX
.extern	VP_MEMFUL
.extern	VP_MESSAGE
.extern	VP_MESSAGES
.extern	VP_NO
.extern	VP_NEW
.extern	VP_ONE

.extern	VP_DEFAULTOGM
.extern	VP_DEFOGM5

;-------------------------------------------------------------------------------
.END
