

OTP		==	1

DEFAULT_century	==	20
DEFAULT_year	==	08
DEFAULT_month	==	1
DEFAULT_day	==	1
DEFAULT_hour	==	0
DEFAULT_minute	==	0

DEFAULT_ringmelody	==	1 ; (jingle)
DEFAULT_ringvolume	==	2 ;(level 2)
DEFAULT_flashtime	==	1 ;(100ms)
DEFAULT_pausetime	==	3 ;(3s)
DEFAULT_contrast	==	5 ;(50%)
DEFAULT_ogm		==	0x81 ;(ogm1, ANS off)
DEFAULT_ringdelay	==	2
DEFAULT_remotecode1	==	0x01
DEFAULT_remotecode2	==	0x23
DEFAULT_areacode1	==	0xff
DEFAULT_areacode2	==	0xff
DEFAULT_rate		==	1
DEFAULT_language	==	0



