.NOLIST
.INCLUDE	REG_D22.inc
.INCLUDE	MX93D22.inc
.INCLUDE	MACRO.inc
.INCLUDE	CONST.inc

;-------------------------------------------------------------------------------
.EXTERN	GetOneConst

.EXTERN	ANNOUNCE_NUM

.EXTERN	BCVOX_INIT
.EXTERN	BBBEEP
.EXTERN	BBEEP
.EXTERN	BEEP

.EXTERN	CLR_FLAG
.EXTERN	CLR_FUNC
.EXTERN	CLR_TIMER

.EXTERN	DAA_SPK
.EXTERN	DAA_REC
.EXTERN	DAA_OFF
.EXTERN	DAM_BIOSFUNC
.EXTERN	DAT_WRITE_STOP
.EXTERN	DEL_ALLTEL
.EXTERN	DGT_TAB

.EXTERN	FFW_MANAGE
.EXTERN	GC_CHK
.EXTERN	GET_SEGCODE
.EXTERN GETHALFBYTE_DAT

.EXTERN	HOOK_ON
.EXTERN	HOOK_OFF
.EXTERN	INIT_DAM_FUNC

.EXTERN	LBEEP
.EXTERN LED4_DISP
.EXTERN	LED_HLDISP
.EXTERN	LINE_START
.EXTERN	LOCAL_PRO

.EXTERN	OGM_SELECT

.EXTERN	PHOVOL_TAB
.EXTERN	PHONE_START
.EXTERN	PUSH_FUNC

.EXTERN	REAL_DEL
.EXTERN	REC_START
.EXTERN	REW_MANAGE

.EXTERN	SET_LED1
.EXTERN	SET_LED2

.EXTERN	SET_LED3
.EXTERN	SET_LED4
.EXTERN	SET_TELGROUP
.EXTERN	SET_TIMER

.EXTERN	STOR_MSG
.EXTERN	STOR_VP
.EXTERN	STORBYTE_DAT
.EXTERN	STORHALFBYTE_DAT

.EXTERN	SET_DELMARK
.EXTERN	SET_PHOVOL

.EXTERN	TELNUM_WRITE

.EXTERN	VPMSG_DEL
.EXTERN	VP_Message
.EXTERN	VPMSG_CHK
.EXTERN	VP_EndOfMessages
;-------------------------------------------------------------------------------
.GLOBAL	LOCAL_PROREC
.GLOBAL	LOCAL_PROPLY
.GLOBAL	LOCAL_PROOGM
.GLOBAL	LOCAL_PROPHO
.GLOBAL	SET_PHONERUN

.LIST
;-------------------------------------------------------------------------------
;-------------------------------------------------------------------------------
LOCAL_PROREC:			;0Xyyy2 = record MEMO
	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,LOCAL_PROREC0	;prompt
	SBHK	1
	BS	ACZ,LOCAL_PROREC1	;record
	
	RET
LOCAL_PROREC0:
	LAC	MSG
	XORL	CMSG_KEY5S		;MEMO key released worn and stop
	BS	ACZ,LOCAL_PROWORN
;LOCAL_PROREC0_1:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PRO0_RECSTART	;end beep and start record
	
	RET
LOCAL_PROWORN:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBBEEP
	
	LACK	0X0
	SAH	PRO_VAR
	
	RET
LOCAL_PRO0_RECSTART:
	CALL	INIT_DAM_FUNC
	CALL	DAA_REC
	CALL	REC_START

	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1

	LACK	0X012
	SAH	PRO_VAR
	
	RET	
LOCAL_PROREC1:
	LAC	MSG
	XORL	CMSG_KEY5S		;stop record
	BS	ACZ,LOCAL_PROREC_STOP
LOCAL_PROREC1_1:
	LAC	MSG
	XORL	CREC_FULL		;timer
	BS	ACZ,LOCAL_PROREC_MFUL
LOCAL_PROREC1_2:
	LAC	MSG
	XORL	CMSG_TMR		;timer
	BS	ACZ,LOCAL_PROX_TMR

	RET

LOCAL_PROX_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	60
	BZ	SGN,LOCAL_PROREC_STOP
	
	LAC	PRO_VAR1
	ANDK	0X03F
	CALL	LED_HLDISP

	RET
;---------------------------------------
LOCAL_PROREC_MFUL:
	;CALL	STATUS_OVF_ON
LOCAL_PROREC_STOP:
	LAC	PRO_VAR1
	SBHK	2
	BS	SGN,LOCAL_PRORECFAIL_STOP
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBEEP
	
	LACK	0X0
	SAH	PRO_VAR

	RET			;录音完毕后(正常)退出
LOCAL_PRORECFAIL_STOP:		;录音失败(非正常)退出
	LAC	CONF
	ORL	0X0800
	SAH	CONF
	CALL	DAM_BIOSFUNC
	CALL	INIT_DAM_FUNC
	
	CALL	DAA_SPK
	CALL	BBBEEP
	
	LACK	0
	SAH	PRO_VAR
	
	RET

;-------------------------------------------------------------------------------
LOCAL_PROPLY:			;0Xyyy1
	LAC	MSG
	XORL	CMSG_KEY2S		;VOL+
	BS	ACZ,LOCAL_PROX_VOLA
	LAC	MSG
	XORL	CMSG_KEY3S		;VOL-
	BS	ACZ,LOCAL_PROX_VOLS
	LAC	MSG
	XORL	CMSG_KEY5S		;ON/OFF(stop)
	BS	ACZ,LOCAL_PROPLY_STOP

	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,LOCAL_PROPLY_0	;(0X0y01)playing
	SBHK	1
	BS	ACZ,LOCAL_PROPLY_1	;(0X0y11)pauseing
	SBHK	1
	BS	ACZ,LOCAL_PROPLY_2	;(0X0y21)pauseing(waiting for REW key release)
	
	RET

LOCAL_PROPLY_0:	
	LAC	MSG
	XORL	CMSG_KEY1S		;pause
	BS	ACZ,LOCAL_PROPLY_PAUSE

	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,LOCAL_PROPLY_0_0	;(0X0001)playing Vop
	SBHK	1
	BS	ACZ,LOCAL_PROPLY_0_1	;(0X0101)playing Message
	
	RET
;---------------------------------------
LOCAL_PROPLY_0_0:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,LOCAL_PROPLY_0_OVER
	
	RET
LOCAL_PROPLY_0_OVER:
	LACL	0X0101
	SAH	PRO_VAR
	BS	B1,LOCAL_PROPLY_OVER
;---------------------------------------
LOCAL_PROPLY_0_1:	
	
LOCAL_PROPLY_0_1_1:
	LAC	MSG
	XORL	CMSG_KEY8S		;FFW
	BS	ACZ,LOCAL_PROPLY_FFW
LOCAL_PROPLY_0_1_2:
	LAC	MSG
	XORL	CMSG_KEYCS		;erase
	BS	ACZ,LOCAL_PROPLY_ERASE
LOCAL_PROPLY_0_1_3:
	LAC	MSG
	XORL	CMSG_KEYGD		;repeat
	BS	ACZ,LOCAL_PROPLY_REW
LOCAL_PROPLY_0_1_4:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,LOCAL_PROPLY_OVER

	RET
;---------------
LOCAL_PROPLY_FFW:
	CALL	INIT_DAM_FUNC

	BS	B1,LOCAL_PROPLY_OVER


LOCAL_PROPLY_REW:
	LAC	PRO_VAR
	ANDL	0XFF0F
	ORK	0X020
	SAH	PRO_VAR

	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER

	LAC	CONF
	ORL	1<<8
	CALL	DAM_BIOSFUNC
	
	RET
LOCAL_PROPLY_PAUSE:
	LAC	CONF
	ANDL	0XF000
	SBHL	0X2000
	BS	ACZ,LOCAL_PROPLY_PAUSE0		;0X2000(message)
	SBHL	0X9000
	BS	ACZ,LOCAL_PROPLY_PAUSE0		;0XB000(voice prompt)
	BS	B1,LOCAL_PROPLY_PAUSE1
LOCAL_PROPLY_PAUSE0:
	LAC	PRO_VAR
	ANDL	0XFF0F
	ORK	0X010
	SAH	PRO_VAR
	
	LACL	0X8C88		;"PA"
	SAH	LED_L

	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER

	LAC	CONF
	ORL	1<<8
	CALL	DAM_BIOSFUNC
	
	RET
LOCAL_PROPLY_PAUSE1:		;若是BEEP,则循环再发
	LACL	CMSG_KEY1S
	CALL	STOR_MSG

	RET

LOCAL_PROX_VOLS:
	LACL	CMSG_VOLS
	CALL	STOR_MSG
	
	RET

LOCAL_PROX_VOLA:
	LACL	CMSG_VOLA
	CALL	STOR_MSG
	
	RET
LOCAL_PROPLY_ERASE:
	LAC	MSG_ID
	CALL	SET_DELMARK
	CALL	INIT_DAM_FUNC
	LACK	0X005
	CALL	STOR_VP

	RET
LOCAL_PROPLY_OVER:
	CALL	INIT_DAM_FUNC

	LAC	MSG_ID
	SBH	MSG_T
	BZ	SGN,LOCAL_PROPLY_STOP

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
	
	BIT	ANN_FG,12
	BZ	TB,LOCAL_PROPLY_LOADVP

	CALL	FFW_MANAGE
	BZ	ACZ,LOCAL_PROPLY_STOP	;THE LAST ONE	

LOCAL_PROPLY_LOADVP:

	LAC	MSG_ID
	CALL	LED_HLDISP

	CALL	VP_Message
	LAC	MSG_ID
	CALL	ANNOUNCE_NUM
	
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROPLY_STOP:		;全播放完毕或强行退出Play-Mode
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	VP_EndOfMessages
	
	CALL	REAL_DEL
	CALL	GC_CHK

	LACK	0X0
	SAH	PRO_VAR

	RET
;-------------------------------------------------------------------------------
LOCAL_PROPLY_1:
	LAC	MSG
	XORL	CMSG_KEY1S		;pause
	BS	ACZ,LOCAL_PROPLY_1_PLAY
LOCAL_PROPLY_1_2:
	LAC	MSG
	XORL	CMSG_KEYCS		;erase
	BS	ACZ,LOCAL_PROPLY_ERASE
LOCAL_PROPLY_1_3:
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,LOCAL_PROPLY_TMR
	
	RET
LOCAL_PROPLY_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	8
	BZ	SGN,LOCAL_PROPLY_STOP
	
	
	RET

LOCAL_PROPLY_1_PLAY:
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR

	CALL	CLR_TIMER

	LAC	CONF
	ANDL	~(1<<8)
	CALL	DAM_BIOSFUNC

	LAC	MSG_ID
	CALL	LED_HLDISP

	RET
;---------------------------------------
LOCAL_PROPLY_2:			;等待REW松开
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,LOCAL_PROPLY_REWEXE
	LAC	MSG
	XORL	CMSG_KEYGS		;repeat
	BS	ACZ,LOCAL_PROPLY_REP
	
	RET
LOCAL_PROPLY_REP:
	CALL	INIT_DAM_FUNC
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	BS	B1,LOCAL_PROPLY_LOADVP
;---------------------------------------
LOCAL_PROPLY_REWEXE:	
	LAC	MSG_ID
	SBHK	1
	BS	ACZ,LOCAL_PROPLY_REWEXE_1	;第一个吗?

	LAC	MSG_ID
	SBHK	1
	SAH	MSG_ID
LOCAL_PROPLY_REWEXE_1:	
	BIT	ANN_FG,12
	BZ	TB,LOCAL_PROPLY_REWEXE_2

	CALL	REW_MANAGE
LOCAL_PROPLY_REWEXE_2:
	CALL	INIT_DAM_FUNC
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	CALL	CLR_TIMER
	BS	B1,LOCAL_PROPLY_LOADVP
;-------------------------------------------------------------------------------
LOCAL_PROOGM:				;0Xyyy3
	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,LOCAL_PROOGM_PLYVOP		;0 - VOP
	SBHK	1
	BS	ACZ,LOCAL_PROOGM_RECOGM		;1 - record OGM
	SBHK	1
	BS	ACZ,LOCAL_PROOGM_PLYOGM		;2 - play OGM

	RET
LOCAL_PROOGM_PLYVOP:
	LAC	MSG
	XORL	CMSG_KEY5S
	BS	ACZ,LOCAL_PROOGM_WORN		;on/off worn and stop
;LOCAL_PROOGM_PLYVOP0_1:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROOGM_RECSTART	;end beep and start record
	
	RET
LOCAL_PROOGM_RECSTART:
	CALL	INIT_DAM_FUNC
	CALL	DAA_REC
	LACK	0X0013
	SAH	PRO_VAR
PROOGM_RECREADY:		;Note: 遥控录OGM时也跳转到此,不能随意更改
	;LACK	COGM_ID
	CALL	OGM_SELECT
;-------delete the old OGM fisrt------------
	LAC	MSG_ID
	CALL	VPMSG_DEL
	CALL	GC_CHK
;---	
    	LAC	MSG_N
    	ORL	0X8D00
    	CALL	DAM_BIOSFUNC		;set user index data0"OGM_ID"
;---	
	CALL	REC_START
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER

	RET
LOCAL_PROOGM_RECOGM:			;record OGM
	LAC	MSG
	XORL	CMSG_KEY5S		;STOP key released to stop record
	BS	ACZ,LOCAL_PROOGM_RECOGM_STOP
LOCAL_PROOGM_REC1_1:
	LAC	MSG
	XORL	CMSG_TMR		;timer
	BS	ACZ,LOCAL_PROOGM_RECTMR
	
	RET
LOCAL_PROOGM_RECTMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	60
	BZ	SGN,LOCAL_PROOGM_RECOGMSUCC_STOP
	
	RET
LOCAL_PROOGM_RECOGM_STOP:
	LAC	PRO_VAR1
	SBHK	2
	BZ	SGN,LOCAL_PROOGM_RECOGMSUCC_STOP

;LOCAL_PROOGM_RECOGMFAIL_STOP:	
	LAC	CONF
	ORL	0X0800
	ORL	1<<11
	CALL	DAM_BIOSFUNC
LOCAL_PROOGM_RECOGMSUCC_STOP:	;准备播放OGM
	
	CALL	DAA_SPK
	LACK	0X0023
	SAH	PRO_VAR		;进入播放OGM子功能
PROOGM_LOADOGM:
	CALL	INIT_DAM_FUNC
	;LACK	COGM_ID
	CALL	OGM_SELECT

;---LED_L "PA"
	LACL	0X8C88
	SAH	LED_L
	
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP

	;LACK	COGM_ID
	CALL	OGM_SELECT
	BZ	ACZ,MAIN_PRO0_PLAY_OGM1
	
	CALL	INIT_DAM_FUNC
	LACK	41
	ORL	0XFF00
	CALL	STOR_VP

MAIN_PRO0_PLAY_OGM1:

	RET
;---------------------------------------
LOCAL_PROOGM_PLYOGM:		;PLAY 
	LAC	MSG
	XORL	CMSG_KEY5S		;stop record(手动停止)
	BS	ACZ,LOCAL_PROOGM_PLYOGM_STOP
LOCAL_PROOGM_PLYOGM0_1:	
	LAC	MSG
	XORL	CVP_STOP		;stop record(播完停止)
	BS	ACZ,LOCAL_PROOGM_PLYOGM_STOP
LOCAL_PROOGM_PLYOGM0_2:	
	LAC	MSG
	XORL	CMSG_KEYCS		;stop record(播完停止)
	BS	ACZ,LOCAL_PROOGM_PLYOGM_ERASE
LOCAL_PROOGM_PLYOGM0_3:
	LAC	MSG
	XORL	CMSG_KEY2S		;VOL+
	BS	ACZ,LOCAL_PROX_VOLA
LOCAL_PROOGM_PLYOGM0_4:
	LAC	MSG
	XORL	CMSG_KEY3S		;VOL-
	BS	ACZ,LOCAL_PROX_VOLS
		
	RET
LOCAL_PROOGM_PLYOGM_STOP:
	CALL	INIT_DAM_FUNC
	CALL	BBEEP
	LACK	0
	SAH	PRO_VAR
	
	RET

LOCAL_PROOGM_PLYOGM_ERASE:
	LAC	MSG_ID
	CALL	VPMSG_DEL

	CALL	INIT_DAM_FUNC
	CALL	BBEEP
	
	CALL	GC_CHK
	
	LACK	0
	SAH	PRO_VAR
	
	RET
LOCAL_PROOGM_WORN:
	CALL	INIT_DAM_FUNC
	CALL	BBBEEP
	
	RET
;-------------------------------------------------------------------------------
.INCLUDE	f_phone.asm

.END
	