;-------------------------------------------------------------------------------
.NOLIST
.INCLUDE	REG_D20.inc
.INCLUDE	MD20U.inc
.INCLUDE	CONST.inc

.GLOBAL	ANS_STATE
;-------------------------------------------------------------------------------
.EXTERN	GetOneConst
.EXTERN	INIT_DAM_FUNC
;.EXTERN	DAA_LIN_SPK
;.EXTERN	DAA_LIN_REC
;.EXTERN	DAA_ROM_MOR
;.EXTERN	DAA_ROMMOR_ON
.EXTERN	DAA_SPK
.EXTERN	DAA_OFF
.EXTERN	DAA_ANS_SPK
.EXTERN	DAA_ANS_REC
.EXTERN	DAA_LIN_SPK
.EXTERN	DAA_LIN_REC
.EXTERN	LBEEP
.EXTERN	LLBEEP
.EXTERN	BBBEEP
.EXTERN	BBEEP
.EXTERN	BEEP

.EXTERN	EXIT_TOIDLE

.EXTERN	HOOK_ON
.EXTERN	HOOK_OFF
.EXTERN	VPMSG_CHK

.EXTERN	PUSH_FUNC
.EXTERN	PAUBEEP
.EXTERN	CLR_FUNC

.EXTERN	STOR_MSG
;.EXTERN	OGM_SELECT
.EXTERN	OGM_STATUS
.EXTERN	DGT_TAB
.EXTERN	SET_LED3
.EXTERN	SET_LED4
.EXTERN	STOR_VP
.EXTERN	LOCAL_PRO
.EXTERN	SET_TIMER
.EXTERN	CLR_TIMER
.EXTERN CLR_TIMER2
.EXTERN SET_TIMER2
;.EXTERN	SEND_DAT

.EXTERN	SEND_MSGNUM
.EXTERN	REC_START
.EXTERN REAL_DEL
.EXTERN	LINE_START
.EXTERN	LED_HLDISP
.EXTERN	BCVOX_INIT
;.EXTERN	FFW_MANAGE

.EXTERN	VPMSG_CHK
;.EXTERN	CLR_FLAG

.EXTERN	DAM_BIOSFUNC
.EXTERN	VPMSG_DEL
.EXTERN	VOL_TAB
.EXTERN	GC_CHK
.EXTERN	GET_VPTLEN
;----------------------------
.EXTERN	VP_DefOGM1
.EXTERN	VP_DefOGM2
;-------------------------------------------------------------------------------
;应答状态的六种退出方式：
;录音时：
;	1.录音时正常录音完毕后退回待机
;	2.录音时并机摘机退回待机
;	3.录音时遥控密码通过
;不录音时：
;	1.等待时超时退回待机
;	2.等待时并机摘机退回待机
;	3.等待时遥控密码通过
;-------------------------------------------------------------------------------
.LIST
;-------------------------------------------------------------------------------
.ORG	ADDR_SECOND
ANS_STATE:
	LAC	MSG
	XORL	CPARA_MINE		;接线按ON/OFF(相当于CPC)
	BS	ACZ,ANS_STATE_STOP

	LAC	MSG
	XORL	CMSG_KEY6S		;接线按ON/OFF(相当于CPC)
	BS	ACZ,ANS_STATE_STOP
	
	LAC	MSG
	XORL	CMSG_KEY7D		;VOL+++
	BS	ACZ,ANS_STATE_VOLA
	LAC	MSG
	XORL	CMSG_KEY8D		;VOL---
	BS	ACZ,ANS_STATE_VOLS
;-----
	LAC	PRO_VAR
	ANDK	0XF
	BS	ACZ,ANS_STATE0		;for initial
	SBHK	1
	BS	ACZ,ANS_STATE_REC	;for record(ANSWER AND RECORD ICM)
	SBHK	1
	BS	ACZ,ANS_STATE_LINE	;for line(ANSWER ONLY)
	SBHK	1
	BS	ACZ,ANS_STATE_EXIT	;for end(TimeOut/BTONE/CTONE/VOX_ON)

	RET
;---------------------------------------
ANS_STATE_STOP:
	LACL	CMSG_CPC
	CALL	STOR_MSG
	
	RET	
	
ANS_STATE0_CPC:
ANS_STATE_LINE_CPC:
	CALL	INIT_DAM_FUNC

	BS	B1,ICM_STATE_EXIT_END

ANS_STATE_VOLS:
	LACL	CMSG_VOLS
	CALL	STOR_MSG
	
	RET

ANS_STATE_VOLA:
	LACL	CMSG_VOLA
	CALL	STOR_MSG
	
	RET	
;=============================================================
ANS_STATE0:
	LAC	MSG
	XORL	CMSG_INIT		;INITIAL
	BS	ACZ,ANS_STATE_INIT
;ANS_STATE0_1:	
	LAC	MSG
	XORL	CVP_STOP		
	BS	ACZ,ICM_STATE0_VPSTOP	;CVP_STOP,OGM播放完毕
;ANS_STATE0_2:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,ANS_STATE0_DTMF
;ANS_STATE0_3:
	LAC	MSG
	XORL	CMSG_CPC		;接线后摘机(相当于CPC)
	BS	ACZ,ANS_STATE0_CPC

	RET
;---------------------------------------
ANS_STATE_INIT:
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	CLR_TIMER

	LACL	0xD700|CRVOX_LEVEL	;Set VOX
	CALL	DAM_BIOSFUNC
	LACL	0X7700|CRSILENCE_LEVEL	;Set silence threshold
	CALL	DAM_BIOSFUNC
		
	LACL	0XFFFF
	SAH	PSWORD_TMP
	
	BIT	EVENT,9		;answer off?
	BS	TB,ANS_STATE_INIT3
	BIT	ANN_FG,13	;memoful?
	BS	TB,ANS_STATE_INIT4
	BIT	EVENT,8		;answer only?
	BS	TB,ANS_STATE_INIT2

;---可以录音---OGM1
	LACL	0X8C88	;"PR"(PA)
	SAH	LED_L

	LACK	0X0010
	SAH	PRO_VAR

	CALL	OGM_STATUS

	LACK	0X07D
	CALL	STOR_VP		;延时1 second
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	CALL	LBEEP

	CALL	OGM_STATUS
	BZ	ACZ,ANS_STATE_INIT1
	
	CALL	INIT_DAM_FUNC
	LACK	0X07D
	CALL	STOR_VP		;延时1 second
	CALL	VP_DefOGM1
	CALL	LBEEP

ANS_STATE_INIT1:
	RET
;---不能录音---OGM2
ANS_STATE_INIT2:
	LACL	0X8C88	;"PR"(PA)
	SAH	LED_L
	
	LACK	0X0020
	SAH	PRO_VAR

	CALL	OGM_STATUS

	LACK	0X07D
	CALL	STOR_VP		;延时1 second
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	CALL	BEEP

	CALL	OGM_STATUS
	BZ	ACZ,ANS_STATE_INIT2_1
	
	CALL	INIT_DAM_FUNC
	LACK	0X07D
	CALL	STOR_VP		;延时1 second
	CALL	VP_DefOGM2
	CALL	BEEP
ANS_STATE_INIT2_1:	
	RET
;---------------------------------------
ANS_STATE_INIT3:		;off
	LACL	0XBFBF	;"--"(--)
	SAH	LED_L
	
	LACK	0X0020
	SAH	PRO_VAR

	CALL	OGM_STATUS

	LACK	0X07D
	CALL	STOR_VP		;延时1 second
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	CALL	LLBEEP

	CALL	OGM_STATUS
	BZ	ACZ,ANS_STATE_INIT3_1
	
	CALL	INIT_DAM_FUNC
	LACK	0X07D
	CALL	STOR_VP		;延时1 second
	CALL	VP_DefOGM2
	CALL	LLBEEP		;3s
ANS_STATE_INIT3_1:
	
	RET
ANS_STATE_INIT4:		;full
	LACL	0X8C88	;"PR"(PA)
	SAH	LED_L
	
	LACK	0X0020
	SAH	PRO_VAR

	CALL	OGM_STATUS

	LACK	0X07D
	CALL	STOR_VP		;延时1 second
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	CALL	BEEP
	CALL	BEEP
	CALL	BEEP

	CALL	OGM_STATUS
	BZ	ACZ,ANS_STATE_INIT4_1
	
	CALL	INIT_DAM_FUNC
	LACK	0X07D
	CALL	STOR_VP		;延时1 second
	CALL	VP_DefOGM2
	CALL	BEEP
	CALL	BEEP
	CALL	BEEP
ANS_STATE_INIT4_1:
	
	RET
;---------------------------------------
ICM_STATE0_VPSTOP:			;开始录音(ICM)/ON_LINE(only)
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_REC
	CALL	BCVOX_INIT

	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
;---	
	LAC	PRO_VAR
	SFR	4
	ANDK	0XF
	SBHK	1
	BS	ACZ,ICM_STATE0_VPSTOP1
	SBHK	1
	BS	ACZ,ICM_STATE0_VPSTOP2
	
	RET
;---PRO_VAR = 0X0010
ICM_STATE0_VPSTOP1:

	LACK	0X0001
	SAH	PRO_VAR
	
	CALL	VPMSG_CHK
	CALL	REC_START

	RET
ICM_STATE0_VPSTOP2:
	
	LACK	0X0002
	SAH	PRO_VAR

	CALL	LINE_START
	
	RET
;---------------for DTMF
ANS_STATE0_DTMF:
	LACK	0
	SAH	PRO_VAR1	;有按键计时清零(仅ANS ONLY时)
	
	CALL	BCVOX_INIT	;有键按下BCVOX要清零
	CALL	CLR_TIMER2	;只要有DTMF检测到就清该时钟
	
	LAC	DTMF_VAL
	XORL	0X0FE
	BS	ACZ,ANS_STATE0_DTMF_STOPOGM	;received "*" when playing OGM
	
	LAC	DTMF_VAL
	ANDK	0X0F
	CALL	PSWORD_CHK	;比较密码
	SAH	SYSTMP0
	ANDK	0X0F
	BS	ACZ,ANS_STATE0_PSWORD_OK

	LAC	SYSTMP0
	SFR	4
	ANDK	0X0F
	SBHK	CPSC
	BZ	SGN,ANS_STATE0_CPC

	RET
ANS_STATE0_DTMF_STOPOGM:
	LAC	PRO_VAR
	SFR	4
	ANDK	0XF
	SBHK	1
	BS	ACZ,ANS_STATE0_DTMF_STOPOGM1
	SBHK	1
	BS	ACZ,ANS_STATE0_DTMF_STOPOGM2
	
	RET
ANS_STATE0_DTMF_STOPOGM1:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	LBEEP
	RET
ANS_STATE0_DTMF_STOPOGM2:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	BEEP
	RET
;---------------------------------------
ANS_STATE_REC_PSWORD_OK:		;密码成功
	LAC	CONF
	ORL	1<<11
	CALL	DAM_BIOSFUNC	;若是录音过程,则删除之
ANS_STATE0_PSWORD_OK:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_REC

	LACL	CRMOT_OK
	CALL	STOR_MSG

	RET
;-------------------------------------------------------------------------------
ANS_STATE_REC:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,ANS_STATE_REC_DTMF
;ANS_STATE_REC_1:
	LAC	MSG
	XORL	CMSG_TMR		;time 1s
	BS	ACZ,ANS_STATE_REC_TMR
;ANS_STATE_REC_2:
	LAC	MSG
	XORL	CMSG_VOX		;VOX_ON 8s
	BS	ACZ,ANS_STATE_REC_VOX
;ANS_STATE_REC_3:
	LAC	MSG
	XORL	CMSG_CTONE		;CTONE 8s
	BS	ACZ,ANS_STATE_REC_CTONE
;ANS_STATE_REC_4:
	LAC	MSG
	XORL	CMSG_BTONE		;BTONE xs
	BS	ACZ,ANS_STATE_REC_BTONE
;ANS_STATE_REC_5:
	LAC	MSG
	XORL	CREC_FULL		;REC_FULL
	BS	ACZ,ICM_REC_FUL
;ANS_STATE_REC_6:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,ICM_FUL_EVP
;ANS_STATE_REC_7:
	LAC	MSG
	XORL	CMSG_CPC		;接线后摘机(相当于CPC)
	BS	ACZ,ANS_STATE_REC_CPC

	RET
	
;---------------------------------------
ANS_STATE_REC_DTMF:	;Record Mode
	
	CALL	BCVOX_INIT	;有键按下BCVOX要清零
	
	CALL	CLR_TIMER2	;只要有DTMF检测到就清该时钟
	
	LAC	DTMF_VAL
	ANDK	0X0F
	CALL	PSWORD_CHK
	SAH	SYSTMP0
	ANDK	0X0F
	BS	ACZ,ANS_STATE_REC_PSWORD_OK

	LAC	SYSTMP0
	SFR	4
	ANDK	0X0F
	SBHK	CPSC
	BZ	SGN,ANS_STATE_REC_CPC	;more than 10 times

	RET
;---------------------------------------
ANS_STATE_REC_CPC:		;录音时
	LAC	PRO_VAR1
	SBHK	2
	BZ	SGN,ANS_STATE_REC_CPC1
	
	LAC	CONF
	ORL	1<<11
	SAH	CONF
	CALL	DAM_BIOSFUNC
ANS_STATE_REC_CPC1:	
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACK	0X001
	CALL	STOR_VP

	
	LACK	0X0003
	SAH	PRO_VAR

	RET

;---------------------------------------
ANS_STATE_REC_VOX:		;由于后BTONE,CTONE,VOX要持续一段时间,要考虑小长度的录音删除问题
ANS_STATE_REC_CTONE:
	LAC	CONF
	ORK	20
	SAH	CONF		;切除静音/TONE声
ANS_STATE_REC_BTONE:
	CALL	INIT_DAM_FUNC
	CALL	VPMSG_CHK
	LAC	MSG_T
	CALL	GET_VPTLEN
	SBHK	3
	BZ	SGN,ANS_STATE_TONE
;---删除比3s短的录音
	LAC	MSG_T
	CALL	VPMSG_DEL
	CALL	GC_CHK
ANS_STATE_TONE:
	CALL	INIT_DAM_FUNC
	LACK	0X0003
	SAH	PRO_VAR

	CALL	DAA_SPK		;???????????????????
	CALL	BBEEP		;替换语音BB

	RET

;---
ANS_STATE_REC_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHL	CICM_LEN		;ICM录音时长
	BS	SGN,ICM_TMR_DET_END
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	BBEEP

	LACK	0X0003
	SAH	PRO_VAR

ICM_TMR_DET_END:
	RET
;-------
ICM_REC_FUL:			;录满退出
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	BBEEP
	
	LACK	0X0003
	SAH	PRO_VAR
	
	RET
ICM_FUL_EVP:
	LACK	0
	SAH	PRO_VAR1
	CALL	INIT_DAM_FUNC
	CALL	LINE_START
	
	RET

;========================================================================
ANS_STATE_LINE:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,ANS_STATE_LINE_DTMF
;ANS_STATE_LINE_1:
	LAC	MSG
	XORL	CMSG_TMR		;time 1s
	BS	ACZ,ANS_STATE_LINE_TMR
;ANS_STATE_LINE_2:
	
;ANS_STATE_LINE_4:
	LAC	MSG
	XORL	CMSG_BTONE		;BTONE 8s
	BS	ACZ,ANS_STATE_TONE
;ANS_STATE_LINE_5:	
	LAC	MSG
	XORL	CMSG_CPC		;接线后摘机(相当于CPC)
	BS	ACZ,ANS_STATE_LINE_CPC

	RET
;---------------------------------------
ANS_STATE_LINE_DTMF:	;Line Mode
	LACK	0
	SAH	PRO_VAR1	;有按键计时清零(仅ANS ONLY时)
	
	CALL	BCVOX_INIT	;有键按下BCVOX要清零
	CALL	CLR_TIMER2	;只要有DTMF检测到就清该时钟
	
	LAC	DTMF_VAL
	ANDK	0X0F
	CALL	PSWORD_CHK	;比较密码
	SAH	SYSTMP0
	ANDK	0X0F
	BS	ACZ,ANS_STATE0_PSWORD_OK
	
	LAC	SYSTMP0
	SFR	4
	ANDK	0X0F
	SBHK	CPSC
	BZ	SGN,ANS_STATE_LINE_CPC	;more than 10 times

	RET
;---------------------------------------
ANS_STATE_LINE_TMR:		;for memful/answer only/answer off
	LACL	CTMR_CTONE
	SAH	TMR_VOX
	SAH	TMR_CTONE

	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	20
	BS	SGN,LINE_TMR_DET_END

	LACK	0X0003
	SAH	PRO_VAR
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	BBEEP	;替换语音BB

LINE_TMR_DET_END:
	RET
;=================================================================
ANS_STATE_EXIT:
	LAC	MSG
	XORL	CVP_STOP		
	BS	ACZ,ICM_STATE_EXIT_END	;CVP_STOP,EXIT播放完毕
	
	RET
ICM_STATE_EXIT_END:		;退出答录状态
	CALL	INIT_DAM_FUNC
	CALL	HOOK_OFF
	CALL	CLR_FUNC	;先空
   	LACL	LOCAL_PRO	;进入本地操作
     	CALL	PUSH_FUNC
	
	LACL	CMODE9
	CALL	DAM_BIOSFUNC
	
	LACK	0
	SAH	PRO_VAR

	CALL	VPMSG_CHK
;---!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	SEND_MSGNUM
	CALL	EXIT_TOIDLE
;---!!!!!!!!!!!!!!!!!!!!!!!!!!

	LACL	CMSG_INIT
	CALL	STOR_MSG

	RET
;-------------------------------------------------------------------------------
;###############################################################################
;----------------------------------------------------------------------------
;       Function : PSWORD_CHK
;       Password check
;	Input  : ACCH = VALUE(DTMF_VAL)
;       Output : ACCH = x0 - password in ok(x = the count of key DTMF)
;                       xF - password fail
;-------------------------------------------------------------------------------
PSWORD_CHK:
        SAH	SYSTMP0
PSWORD_CHK1:
;---先把计数器PSWORD_TMP(15..12)加1后放到PSWORD_TMP(11..8)
	LAC     PSWORD_TMP
	ANDL	0XF0FF
        SAH     PSWORD_TMP
	
	LAC     PSWORD_TMP
	SFR	4
	ANDL	0X0F00
	ADHL	0X0100
	OR	PSWORD_TMP
	SAH	PSWORD_TMP
;---	
        LAC     PSWORD_TMP
        SFL     4
	OR	SYSTMP0
        SAH     PSWORD_TMP        ; PSWORD_TMP keep the new input digit string
;-------------------------------------------------------------------------------
        LAC     PSWORD_TMP
        XOR     PASSWORD
        ANDL	0X0FFF
        BS      ACZ,PSWORD_IN_OK
;---
PSWORD_NOT_IN:		;the intput not digital or wrong remote access code
	LAC	PSWORD_TMP
	SFR	8
	ANDL	0XF0
	ORK	0X0F
	
        RET	
PSWORD_IN_OK:
	LAC	PSWORD_TMP
	SFR	8
	ANDL	0XF0
	
        RET
;-------------------------------------------------------------------------------

;.INCLUDE	f_remote.ASM
;-------------------------------------------------------------------------------
.END
