.NOLIST
.INCLUDE	REG_D20.inc
.INCLUDE	MD20U.inc
.INCLUDE	CONST.inc

.GLOBAL	REMOTE_PRO
;-------------------------------------------------------------------------------
.EXTERN	GetOneConst
.EXTERN	ANNOUNCE_NUM
.EXTERN	INIT_DAM_FUNC
.EXTERN	DAA_LIN_SPK
.EXTERN	DAA_LIN_REC
.EXTERN	DAA_OFF

.EXTERN	DAM_BIOSFUNC

.EXTERN	BBBEEP
.EXTERN	BBEEP
.EXTERN	BEEP
.EXTERN	BCVOX_INIT

.EXTERN	CLR_FUNC
.EXTERN	CLR_TIMER
.EXTERN CLR_TIMER2

.EXTERN	EXIT_TOIDLE

.EXTERN	GC_CHK
.EXTERN	GET_VPTLEN
.EXTERN	HOOK_ON
.EXTERN	HOOK_OFF

.EXTERN	LINE_START
.EXTERN	LBEEP
.EXTERN	LLBEEP
.EXTERN	LOCAL_PRO

.EXTERN	OGM_SELECT
.EXTERN	OGM_STATUS
.EXTERN	PUSH_FUNC
.EXTERN	PAUBEEP

.EXTERN REAL_DEL
.EXTERN	REC_START

.EXTERN	SEND_DAT
.EXTERN	SEND_MSGNUM

.EXTERN	SET_LED3
.EXTERN	SET_LED4

.EXTERN	SET_TIMER
.EXTERN SET_TIMER2
.EXTERN	STOR_VP
.EXTERN	STOR_MSG

.EXTERN	VPMSG_CHK

.EXTERN	VOL_TAB
.EXTERN	VPMSG_CHK
.EXTERN	VPMSG_DEL
;-------------------------------------------------------------------------------
.EXTERN	VP_All
.EXTERN	VP_Announcement
.EXTERN	VP_AnswerOff
.EXTERN	VP_AnswerOn
.EXTERN	VP_DefOGM
.EXTERN	VP_DefOGM1
.EXTERN	VP_DefOGM2
.EXTERN	VP_Erased
.EXTERN	VP_EndOfMessages
.EXTERN	VP_Message
.EXTERN	VP_Messages
.EXTERN	VP_MemoryFull
.EXTERN	VP_CHKMemoryFull
.EXTERN	VP_NEW
.EXTERN	VP_YouHave
.EXTERN	VP_YouHaveNoMessages
;-------------------------------------------------------------------------------
.LIST
;-------------------------------------------------------------------------------
.ORG	ADDR_SECOND
REMOTE_PRO:
	LAC	MSG			;接线后按ON/OFF(相当于CPC)
	XORL	CMSG_KEY6S
	BS	ACZ,REMOTE_PRO_STOP

	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CPARA_MINE
	BS	ACZ,REMOTE_PRO_PMINE
	
	LAC	PRO_VAR
	ANDL	0X0F
	BS	ACZ,REMOTE_PRO0		;0 = IDEL
	SBHK	2
	BS	ACZ,REMOTE_PROPMSG	;2 = play message
	SBHK	1
	BS	ACZ,REMOTE_PROMREC	;3 = record MEMO
	SBHK	4
	BS	ACZ,REMOTE_PROOGM	;7 = record/play OGM
	SBHK	3
	BS	ACZ,REMOTE_PRO10	;10 = exit
	
	RET
;---------------
REMOTE_PRO_STOP:
REMOTE_PRO_PMINE:
	LACL	CMSG_CPC
	CALL	STOR_MSG	;当作CPC一样处理
	
	RET

;===============================================================================
REMOTE_PRO0:
	LAC	MSG
	XORL	CMSG_INIT		;INITIAL(发两声BEEP)
	BS	ACZ,REMOTE_PRO0_INIT
;REMOTE_PRO0_1:
	LAC	MSG
	XORL	CREV_DTMF		;receive DTMF signal
	BS	ACZ,REMOTE_PRO0_REV_DTMF
;REMOTE_PRO0_2:	
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,REMOTE_PRO0_STOPVP	;VP完
;REMOTE_PRO0_3:	
	LAC	MSG
	XORL	CMSG_BTONE
	BS	ACZ,REMOTE_PRO0_TONE
;REMOTE_PRO0_4:	
	LAC	MSG
	XORL	CMSG_CTONE
	BS	ACZ,REMOTE_PRO0_TONE
;REMOTE_PRO0_5:	
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,REMOTE_PRO0_TMR
;REMOTE_PRO0_6:		
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
		
	RET
REMOTE_PRO0_CPC:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACL	0X005
	CALL	STOR_VP
	CALL	VPMSG_CHK
	
	LACK	10
	SAH	PRO_VAR

	RET
REMOTE_PRO0_INIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	BBEEP		;BB
	CALL	VP_RemoteMenu
	CALL	CLR_TIMER
	
	RET
REMOTE_PRO0_STOPVP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_REC
	CALL	LINE_START
	
	LACK	0			;开始计时
	SAH	PRO_VAR1

	LACL	1000
	CALL	SET_TIMER
	
	CALL	BCVOX_INIT
	
	RET
	
REMOTE_PRO0_REV_DTMF:
	CALL	CLR_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	CALL	BCVOX_INIT
	
	LAC	DTMF_VAL
	SBHL	0XF0
	BS	ACZ,REMOTE_PRO0_ERAOLD		;0 --- delete all old messages
	SBHK	2
	BS	ACZ,REMOTE_PRO0_PLYMSG		;2---play message
	SBHK	2
	BS	ACZ,REMOTE_PRO0_PLYOGM		;4---play OGM
	SBHK	1
	BS	ACZ,REMOTE_PRO0_RECOGM		;5---record OGM
	SBHK	1
	BS	ACZ,REMOTE_PRO0_HOOKON		;6---stop/hook_on
	SBHK	2
	BS	ACZ,REMOTE_PRO0_PROOFF		;8---off
	SBHK	1
	BS	ACZ,REMOTE_PRO0_PROON		;9---on
	SBHK	6
	BS	ACZ,REMOTE_PRO0_RECMEMO		;#---
	
	RET
;---------------------------------------
REMOTE_PRO0_PLYNEW:
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	LACK	1
	SAH	PRO_VAR

	LACK	0
	SAH	MSG_ID

	LACL	0X001
	CALL	STOR_VP
	
	RET	
;---------------------------------------
REMOTE_PRO0_PLYMSG:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	
	CALL	VP_CHKMemoryFull	;If Memful play "VP_MemoryFull"
	CALL	VP_YouHave

	CALL	VPMSG_CHK		;进入播放子功能
	CALL	CLR_TIMER
	
	LACK	0X0002
	SAH	PRO_VAR	

	LACK	0
	SAH	MSG_ID

	BIT	ANN_FG,12
	BS	TB,LOCAL_PRO0_PLAY_NEW
	BIT	ANN_FG,14
	BS	TB,LOCAL_PRO0_PLAY_OLD

;REMOTE_PRO0_PLYMSG_NO:
	CALL	INIT_DAM_FUNC
	CALL	VP_YouHaveNoMessages
	CALL	BBEEP

	LACK	0X0
	SAH	PRO_VAR	
	
	RET
;-------play new messages
LOCAL_PRO0_PLAY_NEW:
	LAC	MSG_N
	SBHK	1
	BS	ACZ,LOCAL_PRO0_PLAY_ONENEW
	
	LAC	MSG_N
	CALL	ANNOUNCE_NUM
	CALL	VP_NEW
	CALL	VP_Messages
	
	RET
LOCAL_PRO0_PLAY_ONENEW:
	LAC	MSG_N
	CALL	ANNOUNCE_NUM
	CALL	VP_NEW
	CALL	VP_Message
	
	RET
;-------play old messages
LOCAL_PRO0_PLAY_OLD:
	LAC	MSG_T
	SBHK	1
	BS	ACZ,LOCAL_PRO0_PLAY_ONEALL

	LAC	MSG_T
	CALL	ANNOUNCE_NUM
	CALL	VP_Messages
	
	RET
LOCAL_PRO0_PLAY_ONEALL:
	LAC	MSG_T
	CALL	ANNOUNCE_NUM
	CALL	VP_Message
	
	RET

REMOTE_PRO0_ERAOLD:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	
	CALL	VPMSG_CHK
	LACK	0
	SAH	PRO_VAR
	
	LACL	0X6100
	CALL	DAM_BIOSFUNC
	LACL	0X6080
	CALL	DAM_BIOSFUNC
	CALL	GC_CHK
	
	CALL	VP_All
	CALL	VP_Messages
	CALL	VP_Erased	
	CALL	BBEEP		;BB

	RET

;---------------------------------------
REMOTE_PRO0_PLYOGM:
	BS	B1,REMOTE_PROOGM_REC_STOP
REMOTE_PRO0_RECOGM:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	VPMSG_CHK
	BIT	ANN_FG,13
	BS	TB,REMOTE_PROX_DTMF_MFUL
	
	LACK	0X0007
	SAH	PRO_VAR
	CALL	LBEEP		;Lbee...

	RET

REMOTE_PRO0_RECMEMO:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	VPMSG_CHK
	
	BIT	ANN_FG,13
	BS	TB,REMOTE_PROX_DTMF_MFUL
	
	LACK	0X0003
	SAH	PRO_VAR
	CALL	LBEEP		;Lbee...

	RET
REMOTE_PROX_DTMF_MFUL:		;mfull 直接退出
	CALL	BBBEEP
	CALL	VP_MemoryFull
	LACK	0
	SAH	PRO_VAR

	RET
;---------------------------------------
REMOTE_PRO0_INDOORMONITOR:
.if	0
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	LBEEP		;Lbee...
		
	LACK	0X0008
	SAH	PRO_VAR
.endif	
	RET
;---------------------------------------
REMOTE_PRO0_PROOFF:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	VP_AnswerOff
	CALL	BBEEP
	
	LAC	EVENT
	ORL	(1<<9)
	SAH	EVENT

	
	RET
;------
REMOTE_PRO0_PROOGMSELECT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	
	LAC	EVENT
	XORL	(1<<8)
	SAH	EVENT
	
	BIT	EVENT,8
	BS	TB,REMOTE_PRO0_PROOGM_2
;REMOTE_PRO0_PROOGM_1:
	CALL	VP_Announcement
	LACK	1
	CALL	ANNOUNCE_NUM

	CALL	VP_CHKMemoryFull	;If Memful play "VP_MemoryFull"
		
	CALL	BBEEP
	
	RET
REMOTE_PRO0_PROOGM_2:
	CALL	VP_Announcement
	LACK	2
	CALL	ANNOUNCE_NUM

	CALL	VP_CHKMemoryFull	;If Memful play "VP_MemoryFull"
	CALL	BBEEP
	
	RET	
;---------------------------------------
REMOTE_PRO0_PROON:
	BIT	EVENT,9
	BZ	TB,REMOTE_PRO0_PROOGMSELECT	;GCT Request(change OGM when TAD is on)2008-2-27 10:45

	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	VP_AnswerOn
	CALL	BBEEP

	LAC	EVENT
	ANDL	~(1<<9)
	SAH	EVENT

	RET

	
REMOTE_PRO0_REV_DTMF_A:
	CALL	INIT_DAM_FUNC	
	CALL	DAA_LIN_SPK
	
	LACL	0X005
	CALL	STOR_VP

	RET
REMOTE_PRO0_HOOKON:		;退出准备(!!!note HOOK on/off)
	BS	B1,REMOTE_PRO0_EXIT

;---
REMOTE_PRO0_EXIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK

	LACK	10
	SAH	PRO_VAR

	LACL	0X005
	CALL	STOR_VP

	RET
REMOTE_PRO0_TONE:
	BS	B1,REMOTE_PRO0_EXIT
REMOTE_PRO0_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	20		;20s无操作退出
	BZ	SGN,REMOTE_PRO0_EXIT
	
	RET	
;=======================================================================
;11111111111111111111111111111111111111111111111111111111111111111111111
;=======================================================================
;22222222222222222222222222222222222222222222222222222222222222222222222
REMOTE_PROPMSG:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROPMSG_CPC
	
	LAC	PRO_VAR
	SFR	4
	ANDK	0XF
	BS	ACZ,REMOTE_PROPMSG0		;playing
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG1_PAUSE	;pause

	RET
;---------------
REMOTE_PROPMSG_CPC:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACL	0X001
	CALL	STOR_VP
	
	CALL	REAL_DEL
	CALL	GC_CHK
	CALL	VPMSG_CHK
	
	LACK	10
	SAH	PRO_VAR
	
	RET
;---------------
REMOTE_PROPMSG0:
	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,REMOTE_PROPMSG0_0	;(0X0002)playing Vop(total message/new message)
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG0_1	;(0X0102)playing Message
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG0_2	;(0X0y22)playing Vop(end of message)
	
	RET
;-------------------------------------------------------------------------------
REMOTE_PROPMSG0_0:		;playing VOP
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROPMSG0_0_OVER
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROPMSG0_0_DTMF
;REMOTE_PROPMSG0_0_1:
	LAC	MSG
	XORL	CMSG_BTONE		;CMSG_BTONE
	BS	ACZ,REMOTE_PRO10_END
;REMOTE_PROPMSG0_0_2:	
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROPMSG1_TMR

	RET
;---------------------------------------
REMOTE_PROPMSG0_0_OVER:
	LACL	0X0102
	SAH	PRO_VAR
	BS	B1,REMOTE_PROPMSG0_1_OVER
REMOTE_PROPMSG0_0_DTMF:
	LAC	DTMF_VAL
	SBHL	0XF2
	BS	ACZ,REMOTE_PROPMSG0_0_PAUSE	;2---do pause
	SBHK	4
	BS	ACZ,REMOTE_PROPMSG0_1_STOP	;6---stop playing

	RET
REMOTE_PROPMSG0_0_PAUSE:
	LAC	CONF
	ORL	0X0100
	SAH	CONF
	CALL	DAM_BIOS
	
	LAC	PRO_VAR
	ORK	0X10
	SAH	PRO_VAR
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	RET

;-------------------------------------------------------------------------------
REMOTE_PROPMSG0_1:		;playing message
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROPMSG0_1_OVER
;REMOTE_PROPMSG0_1_0:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROPMSG0_1_DTMF
;REMOTE_PROPMSG0_1_1:
	LAC	MSG
	XORL	CMSG_BTONE		;CMSG_BTONE
	BS	ACZ,REMOTE_PRO10_END
;REMOTE_PROPMSG0_1_2:	
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROPMSG1_TMR

	RET
;---------------
REMOTE_PROPMSG1_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	
	RET

REMOTE_PROPMSG0_1_OVER:
	BIT	ANN_FG,12
	BS	TB,REMOTE_PROPMSG0_1_OVERNEW

	LAC	MSG_ID
	SBH	MSG_T
	BZ	SGN,REMOTE_PROPMSG0_1_STOP

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
REMOTE_PROPMSG0_1_LOADVP:
	CALL	INIT_DAM_FUNC
	CALL	VP_Message
	LAC	MSG_ID
	CALL	ANNOUNCE_NUM
	
	CALL	MSG_WEEK
	CALL	MSG_HOUR
	CALL	MSG_MIN
	CALL	MSG_AMPM

	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	RET
;---------------
REMOTE_PROPMSG0_1_OVERNEW:

	LAC	MSG_ID
	SBH	MSG_N
	BZ	SGN,REMOTE_PROPMSG0_1_STOP

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
		
REMOTE_PROPMSG0_1_LOADNEWVP:
	CALL	INIT_DAM_FUNC
	CALL	VP_Message
	LAC	MSG_ID
	CALL	ANNOUNCE_NUM
	
	CALL	MSG_WEEKNEW
	CALL	MSG_HOURNEW
	CALL	MSG_MINNEW
	CALL	MSG_AMPMNEW

	LAC	MSG_ID
	ORL	0XFD00
	CALL	STOR_VP

	RET
;---------------------------------------
REMOTE_PROPMSG0_1_DTMF:
	LAC	DTMF_VAL
	SBHL	0XF1
	BS	ACZ,REMOTE_PROPMSG0_1_PLYPRE	;1---skip to previous message
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG0_1_PAUSE	;2---do pause
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG0_1_NEXT	;3---skip to next message
	SBHK	3
	BS	ACZ,REMOTE_PROPMSG0_1_STOP	;6---stop play
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG0_1_ERAPLYING	;7---erase current message

	RET
;---------------------------------------
REMOTE_PROPMSG0_1_PLYPRE:		;前一个
	
	LAC	MSG_ID
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG0_1_PLYPRE_1 ;第一个吗?
	
	LAC	PRO_VAR1
	BZ	ACZ,REMOTE_PROPMSG0_1_PLYPRE_1
	
	LAC	MSG_ID
	SBHK	1
	SAH	MSG_ID	

	LACL	1000
	CALL	SET_TIMER
	LACK	1
	SAH	PRO_VAR1
	BS	B1,REMOTE_PROPALL_REPEAT
REMOTE_PROPMSG0_1_PLYPRE_1:
	;CALL	INIT_DAM_FUNC
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
;-------
REMOTE_PROPALL_REPEAT:
	BIT	ANN_FG,12
	BS	TB,REMOTE_PROPMSG0_1_LOADNEWVP
	BS	B1,REMOTE_PROPMSG0_1_LOADVP
;-------
REMOTE_PROPMSG0_1_NEXT:		;the next one
	;CALL	INIT_DAM_FUNC
	BS	B1,REMOTE_PROPMSG0_1_OVER
;-------
REMOTE_PROPMSG0_1_STOP:

	CALL	INIT_DAM_FUNC
	CALL	VP_EndOfMessages
	CALL	BBEEP
	CALL	VPMSG_CHK
	
	LACL	0X6100
	CALL	DAM_BIOSFUNC
	CALL	GC_CHK

	LACK	0
	SAH	PRO_VAR
	SAH	PRO_VAR1
	
	RET

REMOTE_PROPMSG0_1_PAUSE:
	LAC	CONF
	ORL	0X0100
	CALL	DAM_BIOSFUNC
	
	LAC	PRO_VAR
	ORK	0X010
	SAH	PRO_VAR
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	RET
REMOTE_PROPMSG0_1_ERAPLYING:
	LACL	0X0102
	SAH	PRO_VAR
	
	BIT	ANN_FG,12
	BS	TB,REMOTE_PROPMSG0_1_LOADNEWVP
	
	CALL	INIT_DAM_FUNC
	LAC	MSG_ID
	CALL	SET_DELMARK

	CALL	BEEP
	CALL	VP_Message
	CALL	VP_Erased
	
	RET
REMOTE_PROPMSG0_1_ERAPLYING_1:
	CALL	INIT_DAM_FUNC
	LAC	MSG_ID
	CALL	SET_DELMARKNEW
	
	CALL	BEEP
	CALL	VP_Message
	CALL	VP_Erased
	
	RET
;---------------------------------------
REMOTE_PROPMSG0_2:
	RET
;--------------------------------处理消息
REMOTE_PROPMSG1_PAUSE:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROPMSG1_PAUSE_DTMF
;REMOTE_PROPMSG1__PAUSE_1:
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROPMSG1_PAUSE_TMR
;REMOTE_PROPMSG1__PAUSE_2:
	LAC	MSG
	XORL	CMSG_BTONE		;CMSG_BTONE
	BS	ACZ,REMOTE_PRO10_END
	
	RET
;---------------
REMOTE_PROPMSG1_PAUSE_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	10
	BS	SGN,REMOTE_PROPMSG1_PAUSE_TMR_1
	
	CALL	INIT_DAM_FUNC
	CALL	BBEEP
	LACK	0
	SAH	PRO_VAR

REMOTE_PROPMSG1_PAUSE_TMR_1:	

	RET
;---------------------------------------
REMOTE_PROPMSG1_PAUSE_DTMF:
	LAC	DTMF_VAL
	SBHL	0XF1
	BS	ACZ,REMOTE_PROPMSG1_PAUSE_PLYPRE	;1---erase playing message
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG1_PAUSE_PLYING	;2---skip to previous message
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG1_PAUSE_NEXT		;3---skip to next message
	SBHK	3
	BS	ACZ,REMOTE_PROPMSG0_1_STOP		;6---stop
	SBHK	1
	BS	ACZ,REMOTE_PROPMSG1_PAUSE_DELETE	;7---delete current message

	RET
;---------------------------------------
REMOTE_PROPMSG1_PAUSE_PLYPRE:
	LAC	MSG_ID
	SBHK	1
	BZ	SGN,REMOTE_PROPMSG1_PAUSE_PLYPRE_DONE
	
	RET
REMOTE_PROPMSG1_PAUSE_PLYPRE_DONE:
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	BS	B1,REMOTE_PROPMSG0_1_PLYPRE
;---------------------------------------	
REMOTE_PROPMSG1_PAUSE_PLYING:
	LAC	CONF
	ANDL	~(1<<8)
	CALL	DAM_BIOSFUNC
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	CALL	CLR_TIMER
	LACK	1	;防止连续Previous误判
	SAH	PRO_VAR1

	RET
;---------------------------------------
REMOTE_PROPMSG1_PAUSE_NEXT:
	LAC	MSG_ID
	SBHK	1
	BZ	SGN,REMOTE_PROPMSG1_PAUSE_NEXT_DONE
;---MSG_ID less than 1,no previous message
	
	RET
REMOTE_PROPMSG1_PAUSE_NEXT_DONE:	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	CALL	CLR_TIMER
	LACK	0
	SAH	PRO_VAR1
	BS	B1,REMOTE_PROPMSG0_1_NEXT
;---------------------------------------
REMOTE_PROPMSG1_PAUSE_DELETE:	;playing message 
	LAC	MSG_ID
	BS	ACZ,REMOTE_PROPMSG1_PAUSE_DELETE_1
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	CALL	CLR_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	BS	B1,REMOTE_PROPMSG0_1_ERAPLYING
REMOTE_PROPMSG1_PAUSE_DELETE_1:
	RET
;---------------------------------------
;33333333333333333333333333333333333333333333333333333333333333333333333
REMOTE_PROMREC:
	LAC	PRO_VAR
	SFR	4
	BS	ACZ,REMOTE_PROMREC0	;play LBEEP
	SBHK	1
	BS	ACZ,REMOTE_PROMREC1	;record MEMO
	SBHK	1
	BS	ACZ,REMOTE_PROMREC2	;record end BEEP
	RET
;-------------------------------------------------------------------------------
REMOTE_PROMREC0:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROMREC0_VOPOVER

	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	RET
;---
REMOTE_PROMREC0_VOPOVER:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_REC
	LACK	0X0013
	SAH	PRO_VAR
	CALL	VPMSG_CHK

	CALL	REC_START

	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1

	RET
;-------------------------------------------------------------------------------
REMOTE_PROMREC1:
	LAC	MSG
	XORL	CMSG_TMR		;TIMER
	BS	ACZ,REMOTE_PROMREC1_TIMER
REMOTE_PROMREC1_1:
	LAC	MSG
	XORL	CREV_DTMF		;DTMF
	BS	ACZ,REMOTE_PROMREC1_DTMF
REMOTE_PROMREC1_2:	
	LAC	MSG
	XORL	CMSG_BTONE
	BS	ACZ,REMOTE_PROMREC1_BTONE
REMOTE_PROMREC1_3:	
	LAC	MSG
	XORL	CMSG_CTONE
	BS	ACZ,REMOTE_PROMREC1_CTONE
REMOTE_PROMREC1_4:
	LAC	MSG
	XORL	CREC_FULL		;REC_FULL
	BS	ACZ,REMOTE_PROMREC1_STOP
REMOTE_PROMREC1_5:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROMREC1_CPC
	
	RET

;---------------
REMOTE_PROMREC1_CPC:
	LAC	PRO_VAR1
	SBHK	2
	BZ	SGN,REMOTE_PROMREC1_CPC1
	
	LAC	CONF
	ORL	1<<11
	SAH	CONF
	CALL	DAM_BIOSFUNC
REMOTE_PROMREC1_CPC1:	
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACK	0X005
	CALL	STOR_VP

	CALL	VPMSG_CHK
	
	LACK	0X00A
	SAH	PRO_VAR

	RET

REMOTE_PROMREC1_CTONE:
REMOTE_PROMREC1_BTONE:
	CALL	INIT_DAM_FUNC
	CALL	VPMSG_CHK
	LAC	MSG_T
	CALL	GET_VPTLEN
	SBHK	3
	BZ	SGN,REMOTE_PROMREC1_END
;---删除比3s短的录音
	LAC	MSG_T
	CALL	VPMSG_DEL
	CALL	GC_CHK
REMOTE_PROMREC1_END:
	BS	B1,REMOTE_PRO0_TONE
REMOTE_PROMREC1_TIMER:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1	;时长不受限制
	SBHL	CMEM_LEN
	BZ	SGN,REMOTE_PROMREC1_STOP

	RET
;---------------------------------------

;---------------------------------------
REMOTE_PROMREC1_DTMF:

	LAC	DTMF_VAL
	SBHL	0XF6
	BS	ACZ,REMOTE_PROMREC1_DTMF_STOP	;"6"

	RET
;---------------------------------------
REMOTE_PROMREC1_DTMF_STOP:
REMOTE_PROMREC1_STOP:		;mfull/timer over
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
;---
	CALL	VPMSG_CHK
	LAC	MSG_T
	CALL	GET_VPTLEN
	SBHK	3
	BZ	SGN,REMOTE_PROMREC1_STOP1
;---删除比3s短的录音
	LAC	MSG_T
	CALL	VPMSG_DEL
	CALL	GC_CHK
REMOTE_PROMREC1_STOP1:
	CALL	BCVOX_INIT
	LACK	0
	SAH	PRO_VAR1
	CALL	CLR_TIMER
	
	CALL	BBEEP
	CALL	VPMSG_CHK
	
	LACK	0X0023
	SAH	PRO_VAR
	
	RET
;-------------------------------------------------------------------------------
REMOTE_PROMREC2:
	LAC	MSG
	XORL	CVP_STOP		
	BS	ACZ,REMOTE_PROMREC2_VPSTOP	;beep播放完毕
	
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC

	RET
;---------------------------------------
REMOTE_PROMREC2_VPSTOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	LACK	0X005
	CALL	STOR_VP

	LACK	0X0
	SAH	PRO_VAR
	SAH	PRO_VAR1
	
	RET
;=======================================================================
;44444444444444444444444444444444444444444444444444444444444444444444444
;REMOTE_PRO4:
	RET
;=======================================================================
;55555555555555555555555555555555555555555555555555555555555555555555555
;REMOTE_PRO5:
	RET
;=======================================================================
;66666666666666666666666666666666666666666666666666666666666666666666666
;REMOTE_PRO6:
	RET
;=======================================================================
;77777777777777777777777777777777777777777777777777777777777777777777777
REMOTE_PROOGM:
	LAC	PRO_VAR
	SFR	4
	ANDK	0XF
	BS	ACZ,REMOTE_PROOGM0	;play LBEEP
	SBHK	1
	BS	ACZ,REMOTE_PROOGM_REC	;record OGM
	SBHK	1
	BS	ACZ,REMOTE_PROOGM_PLY	;play OGM
	
	RET
;-------
REMOTE_PROOGM_REC:
	LAC	MSG
	XORL	CMSG_TMR		;TIMER
	BS	ACZ,REMOTE_PROOGM_REC_TMR
;REMOTE_PRO7_RECORD_1:
	LAC	MSG
	XORL	CREV_DTMF		;DTMF
	BS	ACZ,REMOTE_PROOGM_REC_DTMF
;REMOTE_PRO7_RECORD_2:	
	LAC	MSG
	XORL	CMSG_BTONE
	BS	ACZ,REMOTE_PROOGM_REC_BTONE
;REMOTE_PRO7_RECORD_3:	
	LAC	MSG
	XORL	CMSG_CTONE
	BS	ACZ,REMOTE_PROOGM_REC_CTONE
;REMOTE_PRO7_RECORD_4:	
	LAC	MSG
	XORL	CREC_FULL		;REC_FULL
	BS	ACZ,REMOTE_PROOGM_REC_STOP
;REMOTE_PRO7_RECORD_5:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROOGM_REC_CPC

	RET
;---------------
REMOTE_PROOGM_REC_CPC:
	BS	B1,REMOTE_PROMREC1_CPC
;---------------------------------------
;REMOTE_PRO7_RECORD_DTMFTIMER:
;	LAC	PRO_VAR2
;	ADHK	1
;	SAH	PRO_VAR2
	
;	RET	
	
REMOTE_PROOGM_REC_CTONE:
REMOTE_PROOGM_REC_BTONE:
	CALL	INIT_DAM_FUNC
	CALL	VPMSG_CHK
	LAC	MSG_T
	CALL	GET_VPTLEN
	SBHK	3
	BZ	SGN,REMOTE_PRO7_RECORD_END
;---删除比3s短的录音
	LAC	MSG_T
	CALL	VPMSG_DEL
	CALL	GC_CHK
REMOTE_PRO7_RECORD_END:
	BS	B1,REMOTE_PRO0_TONE
;---------------------------------------
REMOTE_PROOGM_REC_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHL	COGM_LEN
	BZ	SGN,REMOTE_PROOGM_REC_STOP

	RET

;---------------------------------------
REMOTE_PROOGM_REC_DTMF:	
	LAC	DTMF_VAL
	SBHL	0xF6
	BS	ACZ,REMOTE_PROOGM_REC_DTMF_STOP		;"6"

	RET
;---------------
REMOTE_PROOGM_REC_DTMF_STOP:
	LAC	PRO_VAR1
	SBHK	2
	BZ	SGN,REMOTE_PROOGM_REC_DTMF_STOP1
	
	LAC	CONF
	ORL	1<<11
	CALL	DAM_BIOSFUNC	;录音太短,直接删除
REMOTE_PROOGM_REC_DTMF_STOP1:	
	LAC	CONF
	OR	PRO_VAR2
	ADHK	1
	CALL	DAM_BIOSFUNC
	
REMOTE_PROOGM_REC_STOP:		;处理"#","mfull"
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	LACK	0X0027
	SAH	PRO_VAR
	
	CALL	GET_OGMID
	CALL	OGM_SELECT
	
	CALL	BEEP
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	
	CALL	GET_OGMID
	CALL	OGM_SELECT
	BZ	ACZ,MAIN_PRO0_PLAY_OGM1
;---default OGM	
	CALL	INIT_DAM_FUNC
	CALL	VP_DefOGM1

	CALL	GET_OGMID
	SBHK	COGM1_ID
	BS	ACZ,MAIN_PRO0_PLAY_OGM1

	CALL	INIT_DAM_FUNC
	CALL	VP_DefOGM2
MAIN_PRO0_PLAY_OGM1:

	RET	

;-------------------------------------------------------------------------------	
REMOTE_PROOGM0:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PRO7_VOPOVER
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	RET
;---------------------------------------
REMOTE_PRO7_VOPOVER:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_REC
	LACK	0X0017
	SAH	PRO_VAR
;---
	CALL	GET_OGMID
	CALL	OGM_SELECT
;-------delete the old OGM fisrt------------
	LAC	MSG_ID
	CALL	VPMSG_DEL
	CALL	GC_CHK
;---set user index data0"OGM_ID"------------
    	CALL	GET_OGMID
    	ORL	0X8D00
    	CALL	DAM_BIOSFUNC
;---	
	CALL	REC_START
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER

	RET
;---------------------------------------
REMOTE_PROOGM_PLY:
	LAC	MSG
	XORL	CVP_STOP		;CVP_STOP
	BS	ACZ,REMOTE_PROOGM_PLY_STOP
;REMOTE_PRO7_2_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROOGM_PLY_DTMF
;REMOTE_PRO7_2_2:	
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	RET
REMOTE_PROOGM_PLY_STOP:
	CALL	INIT_DAM_FUNC	
	CALL	BBEEP
	
	LACK	0
	SAH	PRO_VAR
	SAH	PRO_VAR1

	RET

REMOTE_PROOGM_PLY_DTMF:
	LAC	DTMF_VAL
	SBHL	0X0F6
	BS	ACZ,REMOTE_PROOGM_PLY_STOP	;'6'
	SBHK	1
	BS	ACZ,REMOTE_PROOGM_PLY_DTMF_7	;'7'

	RET

REMOTE_PROOGM_PLY_DTMF_7:
	CALL	INIT_DAM_FUNC
	CALL	GET_OGMID
	CALL	OGM_SELECT
;---delete the old OGM fisrt------------
	LAC	MSG_ID
	CALL	VPMSG_DEL
	CALL	GC_CHK
	
	CALL	BEEP
	CALL	VP_Message
	CALL	VP_Erased

	;LACK	0
	;SAH	PRO_VAR
	
	RET
;=======================================================================
;88888888888888888888888888888888888888888888888888888888888888888888888
;=======================================================================
;99999999999999999999999999999999999999999999999999999999999999999999999
;=======================================================================
;#######################################################################
REMOTE_PRO10:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,REMOTE_PRO10_END
	
	RET
REMOTE_PRO10_END:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF	
	CALL	HOOK_OFF

	CALL	CLR_FUNC	;先空
	LACL	LOCAL_PRO	;进入本地操作
     	CALL	PUSH_FUNC	
	LACK	0
	SAH	PRO_VAR

	LACL	CMODE9
	CALL	DAM_BIOSFUNC

	LACL	CMSG_INIT
	CALL	STOR_MSG

	CALL	VPMSG_CHK
;---!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	SEND_MSGNUM
	CALL	EXIT_TOIDLE
;---!!!!!!!!!!!!!!!!!!!!!!!!!!

	RET
;-------------------------------------------------------------------------------
;-------------------------------------------------------------------------------
;       Function : RMTFUNC_CHK
;       Password check
;	Input  : ACCH = VALUE(DTMF_VAL)
;       Output : ACCH = 0 - password in ok
;                       1 - password for mailbox 1
;                       2 - password for mailbox 2
;                       3 - password for mailbox 3
;                       0XFF - password fail
;-------------------------------------------------------------------------------
RMTFUNC_CHK:

	RET
;-------------------------------------------------------------------------------
;       Function : GET_OGMID
;	Input  : no
;       Output : ACCH = OGM_ID
;-------------------------------------------------------------------------------
GET_OGMID:
	LACK	COGM2_ID
	
	BIT	EVENT,8
	BS	TB,GET_OGMID_0

	LACK	COGM1_ID
GET_OGMID_0:
	RET
;-------------------------------------------------------------------------------
;---------------
;	input : no
;	output: no
;---------------
VP_RemoteMenu:
	LACL	0XFF00|59
	CALL	STOR_VP
	RET
;-------------------------------------------------------------------------------
.INCLUDE	l_ply.asm
;-------------------------------------------------------------------------------
.END
	