;-------------------------------------------------------------------------------
.NOLIST
.INCLUDE	REG_D20.inc
.INCLUDE	MD20U.inc
.INCLUDE	CONST.inc

.GLOBAL	LOCAL_PROTXT
;-------------------------------------------------------------------------------
.EXTERN	GetOneConst
.EXTERN	INIT_DAM_FUNC

.EXTERN	DAA_REC
.EXTERN	DAA_SPK
.EXTERN	DAA_ANS_REC
.EXTERN	DAA_ANS_SPK
.EXTERN	DAA_OFF
.EXTERN	LBEEP
.EXTERN	LLBEEP
.EXTERN	BBBEEP
.EXTERN	BBEEP
.EXTERN	BEEP

.EXTERN	HOOK_ON
.EXTERN	HOOK_OFF

.EXTERN	PUSH_FUNC
.EXTERN	PAUBEEP
.EXTERN	CLR_FUNC

.EXTERN	STOR_MSG
.EXTERN	OGM_SELECT
.EXTERN	OGM_STATUS
.EXTERN	DGT_TAB
.EXTERN	SEND_DAT
.EXTERN	SET_LED3
.EXTERN	SET_LED4
.EXTERN	STOR_VP
.EXTERN	LOCAL_PRO
.EXTERN	SET_TIMER
.EXTERN	SET_COMPS
.EXTERN	CLR_TIMER
.EXTERN	REC_START
.EXTERN	LINE_START
.EXTERN	LED_HLDISP
.EXTERN	BCVOX_INIT

.EXTERN	VPMSG_CHK
;.EXTERN	CLR_FLAG

.EXTERN	DAM_BIOSFUNC
.EXTERN	VPMSG_DEL
.EXTERN	VOL_TAB
.EXTERN	GC_CHK
;-------------------------------------------------------------------------------
.LIST
;-------------------------------------------------------------------------------
.ORG	ADDR_SECOND
LOCAL_PROTXT:			;PRO_VAR = 0Xyyy7
	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,LOCAL_PROTEST0	;idle
	SBHK	1
	BS	ACZ,LOCAL_PROTEST1	;MIC Recording
	SBHK	1
	BS	ACZ,LOCAL_PROTEST2	;LINE Recording
	SBHK	1
	BS	ACZ,LOCAL_PROTEST3	;PlayBackCurrentMessage
	SBHK	1
	BS	ACZ,LOCAL_PROTEST4	;QuiteMode(Line seize only)
	SBHK	1
	BS	ACZ,LOCAL_PROTEST5	;Ringer
	SBHK	1
	BS	ACZ,LOCAL_PROTEST6	;Del all messages(FormatFlash)
	SBHK	1
	BS	ACZ,LOCAL_PROTEST7	;---Exit---
	SBHK	1
	BS	ACZ,LOCAL_PROTEST8	;play all VOP
	SBHK	1
	BS	ACZ,LOCAL_PROTEST9	;VOX detect
	SBHK	1
	BS	ACZ,LOCAL_PROTESTA	;DTMF detect

	RET
;-------------------------------------------------------------------------------
LOCAL_PROTEST0:		;Idle
;---	
	LAC	MSG
	XORL	CTMODE_LREC		;line record
	BS	ACZ,LOCAL_PROTEST0_LINREC
;---	
	LAC	MSG
	XORL	CTMODE_MPLY		;PLAY all message to line
	BS	ACZ,LOCAL_PROTEST0_PLYMSG
;---	
	LAC	MSG
	XORL	CTMODE_PVOP		;play all VOP to line
	BS	ACZ,LOCAL_PROTEST0_PLYVOP
;---	
	LAC	MSG
	XORL	CTMODE_VOX		;line detect VOX
	BS	ACZ,LOCAL_PROTEST0_LINVOX
;---	
	LAC	MSG
	XORL	CTMODE_DTMF		;DTMF detect
	BS	ACZ,LOCAL_PROTEST0_LINDTMF
;---	
	LAC	MSG
	XORL	CTMODE_MEMR		;Memory Test
	BS	ACZ,LOCAL_PROTEST0_MEMTST
;---	
	LAC	MSG
	XORL	CTMODE_DFAT		;Factory default
	BS	ACZ,LOCAL_PROTEST0_DFAULT
;---------------
	LAC	MSG
	XORL	CMSG_KEY5D		;OGM
	BS	ACZ,LOCAL_PROTEST0_MICREC	;?????????????????????
	LAC	MSG
	XORL	CMSG_KEY3D		;DEL
	BS	ACZ,LOCAL_PROTEST0_QITMOD	;?????????????????????
	LAC	MSG
	XORL	CMSG_KEY7D		;VOL+
	BS	ACZ,LOCAL_PROTEST0_RNTMOD	;?????????????????????
	LAC	MSG
	XORL	CVP_STOP		;STOP
	BS	ACZ,LOCAL_PROTEST0_INIT	
;---------------
	LAC	MSG
	XORL	CTMODE_STOP		;STOP
	BS	ACZ,LOCAL_PROTEST0_EXTMOD
;---------------	
	RET
;---------------响应区
LOCAL_PROTEST0_INIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	CALL	HOOK_OFF
	CALL	VPMSG_CHK
	LACK	0X0007
	SAH	PRO_VAR

	RET
;---------------------------------------
LOCAL_PROTEST0_MICREC:
	CALL	INIT_DAM_FUNC
	CALL	DAA_REC
	CALL	SET_COMPS
;---Display "-0"
	LACL	0XBFC0
	SAH	LED_L
	
	CALL	VPMSG_CHK		;进入播放子功能
	LACK	0X0017
	SAH	PRO_VAR

	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1

	CALL	REC_START

	RET
;---------------------------------------
LOCAL_PROTEST0_LINREC:
	CALL	HOOK_ON
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_REC
	CALL	BCVOX_INIT
	CALL	VPMSG_CHK		;进入播放子功能
	LACK	0X0027
	SAH	PRO_VAR

	LACK	0
	SAH	PRO_VAR1
	LACL	100
	CALL	SET_TIMER	;为了查VOX

	CALL	SET_COMPS
	CALL	REC_START
	
	RET
;---------------------------------------
LOCAL_PROTEST0_PLYMSG:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	HOOK_ON
	LACK	0X005
	CALL	STOR_VP

	LACK	0X0037
	SAH	PRO_VAR

	CALL	VPMSG_CHK		;进入播放子功能

	LACK	0
	SAH	MSG_ID
	
	RET
;---------------------------------------
LOCAL_PROTEST0_PLYVOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	HOOK_ON
	LACK	0X005
	CALL	STOR_VP

	LACL	0X0087
	SAH	PRO_VAR		;进入播放子功能

	LACK	0
	SAH	MSG_ID

	RET
;---------------------------------------
LOCAL_PROTEST0_LINVOX:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_REC
	CALL	HOOK_ON
	
	LACL	300
	CALL	SET_TIMER
	
	LACL	0X0097
	SAH	PRO_VAR		;进入播放子功能
	
	CALL	LINE_START
	
	RET
;---------------------------------------
LOCAL_PROTEST0_LINDTMF:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_REC
	CALL	HOOK_ON
	
	LACL	100
	CALL	SET_TIMER
	
	LACL	0X00A7
	SAH	PRO_VAR		;进入播放子功能
	
	CALL	LINE_START
	
	RET
;---------------------------------------
	
LOCAL_PROTEST0_MEMTST:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	;CALL	HOOK_ON
	LACK	0X005
	CALL	STOR_VP
	CALL	SET_COMPS
	
	LACL	0X3003
	CALL	DAM_BIOSFUNC
;---	
	LACK	0X6E
	CALL	SEND_DAT
	LAC	RESP
	SFR	8
	ANDL	0X0FF
	CALL	SEND_DAT
	
	LACK	0X6F
	CALL	SEND_DAT
	LAC	RESP
	ANDL	0X0FF
	CALL	SEND_DAT
;---		
	LACK	0X70
	CALL	SEND_DAT
	LACK	0X70
	CALL	SEND_DAT
	
	RET
;---------------------------------------
LOCAL_PROTEST0_DFAULT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	;CALL	HOOK_ON
	LACK	0X005
	CALL	STOR_VP

	LACL	CMODE9|1
	CALL	DAM_BIOSFUNC	;清flash……
;---		
	LACK	0X70
	CALL	SEND_DAT
	LACK	0X70
	CALL	SEND_DAT
	
	RET
;---------------------------------------
LOCAL_PROTEST0_QITMOD:
	LACK	0X0047
	SAH	PRO_VAR
	CALL	HOOK_ON
	
	RET
;---------------------------------------
LOCAL_PROTEST0_RNTMOD:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	LACK	0X0005
	CALL	STOR_VP
	
	LACK	0X0057
	SAH	PRO_VAR
	
	LACL	100
	CALL	SET_TIMER

	LACK	0
	SAH	RING_ID
	
	SAH	PRO_VAR1	;铃声次数清零
	CALL	LED_HLDISP	;Display "count"

	RET
;---------------------------------------
LOCAL_PROTEST0_EXTMOD:
.if	0
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	LACK	0X0005
	CALL	STOR_VP

	LACK	0X0077
	SAH	PRO_VAR

	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
.else	
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	BBEEP
	LACK	0X0
	SAH	PRO_VAR
	
	CALL	CLR_TIMER
.endif	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROTEST1:			;MIC Recording
	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,LOCAL_PROTEST1_0
	SBHK	1
	BS	ACZ,LOCAL_PROTEST1_1
	
	RET
LOCAL_PROTEST1_0:	;---Record	
	LAC	MSG
	XORL	CTMODE_STOP		;Stop record
	BS	ACZ,LOCAL_PROTEST1_0_EXIT	
	
	RET
LOCAL_PROTEST1_0_EXIT:
	CALL	HOOK_ON
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	VPMSG_CHK
	
	LACL	0X0117
	SAH	PRO_VAR

	CALL	BEEP
	LAC	MSG_T
	ORL	0XFE00
	CALL	STOR_VP

	RET
;-------
LOCAL_PROTEST1_1:	;---Play
	LAC	MSG
	XORL	CVP_STOP		;Play end
	BS	ACZ,LOCAL_PROTEST1_1_EXIT	
	
	RET

LOCAL_PROTEST1_1_EXIT:	;退回到测试平台
	BS	B1,LOCAL_PROTEST0_INIT
;---------------------------------------
LOCAL_PROTESTX_EXIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	BEEP
	
	LACK	0X0007
	SAH	PRO_VAR
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROTEST2:			;LINE Recording
	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,LOCAL_PROTEST2_0
	SBHK	1
	BS	ACZ,LOCAL_PROTEST2_1

	RET
LOCAL_PROTEST2_0:
	LAC	MSG
	XORL	CTMODE_STOP		;Stop Record
	BS	ACZ,LOCAL_PROTEST2_0_EXIT
	
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,LOCAL_PROTEST2_0_TMR	
	
	RET
LOCAL_PROTEST2_0_EXIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	VPMSG_CHK
	
	LACL	1000
	CALL	SET_TIMER

	LACL	0X0127
	SAH	PRO_VAR
	
	CALL	BEEP
	LAC	MSG_T
	ORL	0XFE00
	CALL	STOR_VP

	RET
LOCAL_PROTEST2_0_TMR:
	BIT	RESP,6
	BS	TB,LOCAL_PROTEST2_0_TMRVOX1
	
	LACL	0XBFC7		;Display "-L"
	SAH	LED_L
	
	RET
LOCAL_PROTEST2_0_TMRVOX1:
	LACL	0XBFC1		;Display "-V"
	SAH	LED_L
		
	RET
;---------------
LOCAL_PROTEST2_1:
	LAC	MSG
	XORL	CVP_STOP		;Play end
	BS	ACZ,LOCAL_PROTEST1_1_EXIT
	
	LAC	MSG
	XORL	CTMODE_STOP		;Play end
	BS	ACZ,LOCAL_PROTEST1_1_EXIT	
	
	RET
LOCAL_PROTEST2_1_EXIT:		;退回到测试平台
	BS	B1,LOCAL_PROTEST0_INIT
;-------------------------------------------------------------------------------
LOCAL_PROTEST3:			;PlayBackCurrentMessage
	LAC	MSG
	XORL	CTMODE_STOP		;STOP
	BS	ACZ,LOCAL_PROTEST3_EXIT	
	
	LAC	MSG
	XORL	CVP_STOP		;STOP
	BS	ACZ,LOCAL_PROTEST3_OVER	
	
	RET

LOCAL_PROTEST3_OVER:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	LAC	MSG_ID
	SBH	MSG_T
	BZ	SGN,LOCAL_PROTEST3_EXIT

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
	
	CALL	BEEP
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	
	RET
LOCAL_PROTEST3_EXIT:
	BS	B1,LOCAL_PROTESTX_EXIT
;-------------------------------------------------------------------------------
LOCAL_PROTEST4:			;QuiteMode(Line seize only)
	LAC	MSG
	XORL	CTMODE_STOP		;STOP
	BS	ACZ,LOCAL_PROTEST4_EXIT	
	
	RET
LOCAL_PROTEST4_EXIT:
	BS	B1,LOCAL_PROTESTX_EXIT
;-------------------------------------------------------------------------------
LOCAL_PROTEST5:			;Ringer
	LAC	MSG
	XORL	CTMODE_STOP		;STOP
	BS	ACZ,LOCAL_PROTESTX_EXIT	
;---
	LAC	MSG
	XORL	CRING_IN
	BS	ACZ,LOCAL_PROTEST5_RING
	
	LAC	RING_ID
	ANDL	0XFF0F
	SAH	RING_ID		;防摘机

	RET
LOCAL_PROTEST5_RING:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	
	;LAC	PRO_VAR1
	CALL	LED_HLDISP	;Display "count"
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROTEST6:			;Del all messages(FormatFlash)
	LAC	MSG
	XORL	CTMODE_STOP		;STOP
	BS	ACZ,LOCAL_PROTESTX_EXIT	
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROTEST7:
	LAC	MSG
	XORL	CMSG_TMR		;STOP
	BS	ACZ,LOCAL_PROTEST7_TMR
	
	RET
LOCAL_PROTEST7_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	3
	BZ	SGN,LOCAL_PROTEST7_EXIT
	
	RET
LOCAL_PROTEST7_EXIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	CALL	BBEEP
	LACK	0X0
	SAH	PRO_VAR

	RET
;-------------------------------------------------------------------------------
LOCAL_PROTEST8:
	LAC	MSG
	XORL	CTMODE_STOP		;STOP
	BS	ACZ,LOCAL_PROTEST8_EXIT	
	
	LAC	MSG
	XORL	CVP_STOP		;STOP
	BS	ACZ,LOCAL_PROTEST8_OVER	
	
	RET
LOCAL_PROTEST8_OVER:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ANS_SPK
	LAC	MSG_ID
	SBHK	58
	BZ	SGN,LOCAL_PROTEST8_OVEREXIT

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
	
	CALL	BEEP
	LAC	MSG_ID
	ORL	0XFF00
	CALL	STOR_VP
	
	RET
LOCAL_PROTEST8_OVEREXIT:
	LACK	0X70
	CALL	SEND_DAT
	LACK	0X70
	CALL	SEND_DAT
	
	BS	B1,LOCAL_PROTESTX_EXIT
LOCAL_PROTEST8_EXIT:
	BS	B1,LOCAL_PROTESTX_EXIT
;-------------------------------------------------------------------------------
LOCAL_PROTEST9:
	LAC	MSG
	XORL	CTMODE_STOP		;STOP
	BS	ACZ,LOCAL_PROTEST9_EXIT	
	
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,LOCAL_PROTEST9_TMR
	
	RET
LOCAL_PROTEST9_EXIT:
	BS	B1,LOCAL_PROTESTX_EXIT
LOCAL_PROTEST9_TMR:
	BIT	RESP,6
	BS	TB,LOCAL_PROTEST9_TMRVOXOFF
	
	LACK	0X6D
	CALL	SEND_DAT
	LACK	0X01
	CALL	SEND_DAT
	
	RET
LOCAL_PROTEST9_TMRVOXOFF:	;Slince
	LACK	0X6D
	CALL	SEND_DAT
	LACK	0X00
	CALL	SEND_DAT
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROTESTA:
	LAC	MSG
	XORL	CTMODE_STOP		;STOP
	BS	ACZ,LOCAL_PROTESTA_EXIT	
	
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,LOCAL_PROTESTA_TMR
	
	RET
LOCAL_PROTESTA_EXIT:
	BS	B1,LOCAL_PROTESTX_EXIT
;---------------------------------------
LOCAL_PROTESTA_TMR:
	LAC	RESP
	ANDL	0X010F
	XORL	0X010F
	BS	ACZ,LOCAL_PROTESTA_TMR_D
	
	LAC	RESP
	ANDK	0X0F
	BS	ACZ,LOCAL_PROTESTA_TMR_NODTMF
	ADHL	DTMF_TAB
	CALL	GetOneConst
	SAH	DTMF_VAL
LOCAL_PROTESTA_TMR_1:
		
	LACK	0X6C
	CALL	SEND_DAT
	LAC	DTMF_VAL
	ANDK	0X0F
	CALL	SEND_DAT
	
	RET
;---------------
LOCAL_PROTESTA_TMR_D:
	LACL	0XFF
	SAH	DTMF_VAL
	BS	B1,LOCAL_PROTESTA_TMR_1
;---------------
LOCAL_PROTESTA_TMR_NODTMF:	;Slince
	
	RET
;-------------------------------------------------------------------------------
DTMF_TAB:
 	;no	1	2	3	4	5	6	7	8	
.DATA	0X00	0XF1	0XF2	0XF3	0XF4	0XF5	0XF6	0XF7	0XF8

	;9	*	0	#	A	B	C	D
.DATA	0XF9	0XFA	0XF0	0XFB	0XFC	0XFD	0XFE	0XFF  
;-------------------------------------------------------------------------------
.END
