.NOLIST
;-------------------------------------------------------------------------------
VOPIDX_DE_Sunday	.EQU	24+40
VOPIDX_DE_Uhr		.EQU	31+40	;hour
VOPIDX_DE_Null		.EQU	32+40	;0
VOPIDX_DE_und		.EQU	33+40	;and
VOPIDX_DE_ein		.EQU	34+40	;one
VOPIDX_DE_SpeischerVoll	.EQU	35+40	;MemoryIsFull
VOPIDX_DE_BitteTagUnd	.EQU	36+40	;PleaseSetTime
VOPIDX_DE_DefOGM1	.EQU	37+40
;---------------------------------------
VOPIDX_FR_Sunday	.EQU	24	;
VOPIDX_FR_heure		.EQU	31	;hour
VOPIDX_FR_zero		.EQU	32	;0
VOPIDX_FR_DefOGM1	.EQU	37

;-------------------------------------------------------------------------------
.END
