.NOLIST
.INCLUDE	REG_D20.inc
.INCLUDE	MD20U.inc
.INCLUDE	VOPidx.inc
.INCLUDE	CONST.inc
.INCLUDE	EXTERN.inc

.GLOBAL	LOCAL_PROMNU
;-------------------------------------------------------------------------------
.EXTERN	GetOneConst
;---------------------------------------
.LIST
;-------------------------------------------------------------------------------
.ORG	ADDR_SECOND
;-------------------------------------------------------------------------------
LOCAL_PROMNU:				;MENU设置状态要考虑的消息(PRO_VAR)
	LAC	MSG
	XORL	CRING_IN
	BS	ACZ,MAIN_PROX_RINGIN

	LAC	MSG
	XORL	CMSG_KEY6S
	BS	ACZ,MAIN_PRO9_X_STOP	;STOP
	LAC	MSG
	XORL	CMSG_EXIT
	BS	ACZ,MAIN_PRO9_X_STOP	;STOP

	LAC	MSG
	XORL	CMSG_HSOFF
	BS	ACZ,MAIN_PROX_RINGIN		;Handset off the base cradle	
	LAC	MSG
	XORL	CMSG_TMR2
	BS	ACZ,LOCAL_PROMNU_2TMR

	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_0		;(0Xyy04)wait for key release
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD		;(0Xyy14)psword set
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME		;(0Xyy24)time set
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_SELLANG	;(0Xyy34)Select language
	
	RET
;---------------------------------------
MAIN_PROX_RINGIN:
	CALL	INIT_DAM_FUNC
	LACK	0
	SAH	PRO_VAR

	CALL	PORT_HSPLYL
	CALL	PORT_PLYL

	LACL	CMSG_INIT
	CALL	STOR_MSG
	
	RET
;---------------------------------------
LOCAL_PROMNU_VPSTOP:

	LACK	0
	SAH	PRO_VAR1		;计数器清零(按键松开后BEEP结束)	
	CALL	DAA_OFF

	RET
;---------------------------------------
MAIN_PRO9_X_STOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBEEP		;BB

	CALL	CLR_TIMER
	CALL	CLR_TIMER2
	
	CALL	PORT_HSPLYL
	CALL	PORT_PLYL

	LACK	0X0
	SAH	PRO_VAR
	
	RET
;---------------------------------------
LOCAL_PROMNU_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	20
	BZ	SGN,MAIN_PRO9_TMROVER
	
	RET
;---------------------------------------
MAIN_PRO9_TMROVER:		;超时退出
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBEEP		;BB
	
	LACL	0X0424
	SAH	PRO_VAR

	CALL	VPMSG_CHK
	BIT	ANN_FG,12
	BS	TB,MAIN_PRO9_TMROVER_STOP1
	LAC	MSG_T
	CALL	LED_HLDISP	;VP总数

	RET			;调节完毕后正常退出
MAIN_PRO9_TMROVER_STOP1:
	LAC	MSG_N
	CALL	LED_HLDISP	;VP总数

	RET
;---------------------------------------
LOCAL_PROMNU_2TMR:
	LIPK	8
	IN	SYSTMP0,GPBD
	BIT	SYSTMP0,12
	BS	TB,LOCAL_PROMNU_2TMR_SPK	;查到SPK,立即退出
	BIT	SYSTMP0,5			;查到HS ,
	BS	TB,LOCAL_PROMNU_2TMR_HSCHK	;是挂机状态
	
	RET
;---------
LOCAL_PROMNU_2TMR_HSCHK:
	CALL	PORT_HSPLYL
	CALL	PORT_PLYH
	
	RET
;---------------------------------------
LOCAL_PROMNU_2TMR_SPK:		;查到SPK,立即退出
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACK	0X005
	CALL	STOR_VP

	CALL	PORT_HSPLYL
	CALL	PORT_PLYL
	CALL	CLR_TIMER
	CALL	CLR_TIMER2
	
	LACK	0X0
	SAH	PRO_VAR

	CALL	REAL_DEL
	CALL	GC_CHK
	
	CALL	VPMSG_CHK
	BIT	ANN_FG,12
	BS	TB,LOCAL_PROPLY_0_2_VPSTOP1
	
	LAC	MSG_T
	CALL	LED_HLDISP
	
	RET

LOCAL_PROPLY_0_2_VPSTOP1:
	LAC	MSG_N
	CALL	LED_HLDISP

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_0:				;wait for key released
	LAC	MSG
	XORL	CMSG_KEY2L		;Set time
	BS	ACZ,LOCAL_PROMNU_0_SETTIME
	LAC	MSG
	XORL	CANN_TIME
	BS	ACZ,LOCAL_PROMNU_0_PLAYTIME	;play the time
	LAC	MSG
	XORL	CMSG_SELL
	BS	ACZ,LOCAL_PROMNU_0_SELLANG
	RET
;---------------------------------------
LOCAL_PROMNU_0_SETTIME:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	
	CALL	CWEEK_GET
	SAH	MSG_N
	CALL	LED_HLDISP
	
	;CALL	VP_PleaseSetTime	;

	LACK	0X005
	CALL	STOR_VP
	LAC	MSG_N
	CALL	VP_WEEK
	
	LACL	0X0124
	SAH	PRO_VAR

	RET
;---------------------------------------
LOCAL_PROMNU_0_SELLANG:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	
	CALL	GET_LANGUAGE
	SAH	MSG_N
	
	LAC	MSG_N
	ADHL	LANG_TAB
	CALL	GetOneConst
	SAH	LED_L		;Display En/Fr/dE
	
	LACK	0X005
	CALL	STOR_VP
	LAC	MSG_N
	CALL	VP_SUNDAY
	
	LACL	0X0134
	SAH	PRO_VAR
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_PSWORD:	
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR

	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_PSWORD_0	;wait
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD_1	;adjust ps1
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD_2	;adjust ps2
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD_3	;adjust ps3
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD_DISP	;Display

	RET

LOCAL_PROMNU_PSWORD_0:
	LAC	MSG
	XORL	CMSG_KEY2S		;Announce time
	BS	ACZ,LOCAL_PROMNU_PSWORD_0_TIME
	
	RET
LOCAL_PROMNU_PSWORD_0_TIME:	
	LACL	0X0114
	SAH	PRO_VAR

	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER		;打开定时,按键清零,超时退出	

	RET
;-----------------------------------------------------------
LOCAL_PROMNU_PSWORD_1:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end
;LOCAL_PROMNU_PSWORD_1_1:		
	LAC	MSG
	XORL	CMSG_KEY5S
	BS	ACZ,MAIN_PRO9_1_X_REW	;REW(DEC)
;LOCAL_PROMNU_PSWORD_1_2:	
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_1_X_FFW	;FFW(INC)
;LOCAL_PROMNU_PSWORD_1_3:	
	LAC	MSG
	XORL	CMSG_KEY5P
	BS	ACZ,MAIN_PRO9_1_X_PREW	;REW
;LOCAL_PROMNU_PSWORD_1_4:	
	LAC	MSG
	XORL	CMSG_KEY2P
	BS	ACZ,MAIN_PRO9_1_X_PFFW	;FFW
;LOCAL_PROMNU_PSWORD_1_5:
	LAC	MSG
	XORL	CMSG_KEY1S
	BS	ACZ,LOCAL_PROMNU_PSWORD_1_PLAY	;PLAY	

	RET

LOCAL_PROMNU_PSWORD_1_PLAY:
	LAC	PASSWORD
	ANDL	0XF0FF
	SAH	PASSWORD

	LACL	0XB700
	SAH	MSG_ID		;中下线

	LAC	MSG_N
	SFL	8
	ANDL	0X0F00
	OR	PASSWORD
	SAH	PASSWORD
;---	
	LACK	0
	SAH	COUNT
	LAC	PASSWORD
	SFR	8
	ANDK	0X0F
	CALL	STORBYTE_DAT
	LACK	8
	SAH	COUNT
	LACL	0XFF
	CALL	STORBYTE_DAT	;以0XFF结尾

	LACK	1
	CALL	DEL_ONETEL
	CALL	TEL_GC_CHK
	CALL	GC_CHK
	
	LACK	0
	SAH	COUNT
	CALL	TELNUM_WRITE	;写入数据
	CALL	DAT_WRITE_STOP
;---
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP		;BEEP
	
	LACL	0X0214
	SAH	PRO_VAR

	LAC	PASSWORD
	SFR	4
	ANDK	0X0F
	SAH	MSG_N		;LOAD CURRENT VALUE(ps2)
	CALL	LED_HLDISP

	LAC	LED_L		;识别码
	ANDL	0X00FF
	OR	MSG_ID
	SAH	LED_L

	RET

MAIN_PRO9_1_X_REW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP
MAIN_PRO9_1_X_PREW:
	LAC	NEW1
	SAH	SYSTMP1
	LAC	NEW2
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_SUB
	SAH	MSG_N
	CALL	LED_HLDISP
	
	LAC	LED_L
	ANDL	0X00FF
	OR	MSG_ID
	SAH	LED_L
	
	RET
;---
MAIN_PRO9_1_X_FFW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP
MAIN_PRO9_1_X_PFFW:
	LAC	NEW1
	SAH	SYSTMP1
	LAC	NEW2
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	LED_HLDISP

	LAC	LED_L
	ANDL	0X00FF
	OR	MSG_ID
	SAH	LED_L

	RET

;-----------------------------------------------------------
LOCAL_PROMNU_PSWORD_2:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end

;MAIN_PRO9_1_2_1:		
	LAC	MSG
	XORL	CMSG_KEY5S
	BS	ACZ,MAIN_PRO9_1_X_REW	;REW
;MAIN_PRO9_1_2_2:	
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_1_X_FFW	;FFW
;MAIN_PRO9_1_2_3:	
	LAC	MSG
	XORL	CMSG_KEY5P
	BS	ACZ,MAIN_PRO9_1_X_PREW	;REW
;MAIN_PRO9_1_2_4:	
	LAC	MSG
	XORL	CMSG_KEY2P
	BS	ACZ,MAIN_PRO9_1_X_PFFW	;FFW
;MAIN_PRO9_1_2_5:
	LAC	MSG
	XORL	CMSG_KEY1S
	BS	ACZ,MAIN_PRO9_1_2_PLAY	;PLAY

	RET

MAIN_PRO9_1_2_PLAY:
	LAC	PASSWORD
	ANDL	0XFF0F
	SAH	PASSWORD

	LACL	0XB600
	SAH	MSG_ID


	LAC	MSG_N
	SFL	4
	ANDL	0X00F0
	OR	PASSWORD
	SAH	PASSWORD
;---
	LACK	1
	SAH	COUNT
	LAC	PASSWORD
	SFR	4
	ANDK	0X0F
	CALL	STORBYTE_DAT
	LACK	8
	SAH	COUNT
	LACL	0XFF
	CALL	STORBYTE_DAT	;以0XFF结尾

	LACK	1
	CALL	DEL_ONETEL
	CALL	TEL_GC_CHK
	CALL	GC_CHK
	
	LACK	0
	SAH	COUNT
	CALL	TELNUM_WRITE	;写入数据
	CALL	DAT_WRITE_STOP
;---保存完毕
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP		;BEEP
	
	LACL	0X0314
	SAH	PRO_VAR

	LAC	PASSWORD
	ANDK	0X0F
	SAH	MSG_N		;LOAD CURRENT VALUE(ps3)
	CALL	LED_HLDISP

	LAC	LED_L		;识别码
	ANDL	0X00FF
	OR	MSG_ID
	SAH	LED_L

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_PSWORD_3:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end

;LOCAL_PROMNU_PSWORD_3_1:		
	LAC	MSG
	XORL	CMSG_KEY5S
	BS	ACZ,MAIN_PRO9_1_X_REW	;REW
;LOCAL_PROMNU_PSWORD_3_2:	
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_1_X_FFW	;FFW
;LOCAL_PROMNU_PSWORD_3_3:	
	LAC	MSG
	XORL	CMSG_KEY5P
	BS	ACZ,MAIN_PRO9_1_X_PREW	;REW
;LOCAL_PROMNU_PSWORD_3_4:	
	LAC	MSG
	XORL	CMSG_KEY2P
	BS	ACZ,MAIN_PRO9_1_X_PFFW	;FFW
;LOCAL_PROMNU_PSWORD_3_5:
	LAC	MSG
	XORL	CMSG_KEY1S
	BS	ACZ,MAIN_PRO9_1_3_PLAY	;PLAY

	RET

MAIN_PRO9_1_3_PLAY:
	LAC	PASSWORD
	ANDL	0XFFF0
	SAH	PASSWORD

	LAC	MSG_N
	ANDK	0X00F
	OR	PASSWORD
	SAH	PASSWORD
;---
	LACK	2
	SAH	COUNT
	LAC	PASSWORD
	SFR	4
	ANDK	0X0F
	CALL	STORBYTE_DAT
	LACK	8
	SAH	COUNT
	LACL	0XFF
	CALL	STORBYTE_DAT	;以0XFF结尾

	LACK	1
	CALL	DEL_ONETEL
	CALL	TEL_GC_CHK
	CALL	GC_CHK
	
	LACK	0
	SAH	COUNT
	CALL	TELNUM_WRITE	;写入数据
	CALL	DAT_WRITE_STOP
;---
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP		;BEEP

	LACL	0X0414
	SAH	PRO_VAR

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_PSWORD_DISP:
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_PSWORD_DISP_TMR	;TMR
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP			;VP end

	RET
	
LOCAL_PROMNU_PSWORD_DISP_TMR:	
	LAC	PRO_VAR
	SFR	12
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_PSWORD0_DISP	;0X0414
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD1_DISP	;0X1414
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD2_DISP	;0X2414
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD3_DISP	;0X3414
	
	RET
LOCAL_PROMNU_PSWORD0_DISP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP
	
	LACL	0X1414
	SAH	PRO_VAR
	
	LAC	PASSWORD
	SFR	8
	ANDK	0X0F		;LOAD CURRENT VALUE(ps1)
	CALL	LED_HLDISP
	
	LAC	LED_L
	ANDL	0X00FF
	ORL	0XF700		;高位显示"下划线"
	SAH	LED_L
	
	RET
LOCAL_PROMNU_PSWORD1_DISP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP
	
	LACL	0X2414
	SAH	PRO_VAR
	
	LAC	PASSWORD
	SFR	4
	ANDK	0X0F		;LOAD CURRENT VALUE(ps2)
	CALL	LED_HLDISP

	LAC	LED_L
	ANDL	0X00FF
	ORL	0XB700		;高位显示"下中划线"
	SAH	LED_L

	RET
LOCAL_PROMNU_PSWORD2_DISP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP
	
	LACL	0X3414
	SAH	PRO_VAR
	
	LAC	PASSWORD
	ANDK	0X0F		;LOAD CURRENT VALUE(ps3)
	CALL	LED_HLDISP
	
	LAC	LED_L
	ANDL	0X00FF
	ORL	0XB600		;高位显示"下中上划线"
	SAH	LED_L
	
	RET
LOCAL_PROMNU_PSWORD3_DISP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBEEP
	
	LACK	0X0
	SAH	PRO_VAR
	
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME:			;adjust time
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR
	
	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_TIME_0	;wait
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_1	;week
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_2	;hour
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_3	;minute
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_4	;Announce time/time-out beep-end


	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME_0:
	LACL	0X0124
	SAH	PRO_VAR

	LAC	MSG
	CALL	STOR_MSG
	
	RET
;---------------------------------------
LOCAL_PROMNU_TIME_VPSTOP:
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
	CALL	DAA_OFF
	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME_1:		;adjust week
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_TIME_VPSTOP	;VP end
;LOCAL_PROMNU_TIME_1_1:
	LAC	MSG
	XORL	CMSG_KEY2D
	BS	ACZ,LOCAL_PROMNU_TIME_1_FFW	;TIME = FFW
;LOCAL_PROMNU_TIME_1_3:
	;LAC	MSG
	;XORL	CMSG_KEY2P
	;BS	ACZ,LOCAL_PROMNU_TIME_1_PFFW	;TIME = FFW
;LOCAL_PROMNU_TIME_1_5:
	LAC	MSG
	XORL	CMSG_KEY1D
	BS	ACZ,LOCAL_PROMNU_TIME_1_PLAY	;PLAY = CONFIRM
	
	RET

;---------------------------------------
LOCAL_PROMNU_TIME_1_FFW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACK	0
	SAH	PRO_VAR1
	
	LACK	0
	SAH	SYSTMP1
	LACK	6
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	
	CALL	LED_HLDISP
	
	LAC	MSG_N
	CALL	VP_WEEK
	
	RET
;---------------------------------------
LOCAL_PROMNU_TIME_1_PFFW:
	LACK	0
	SAH	SYSTMP1
	LACK	6
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	LED_HLDISP
	
	RET
;---------------------------------------
LOCAL_PROMNU_TIME_1_PLAY:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACK	0
	SAH	PRO_VAR1
	
	LAC	MSG_N
	CALL	WEEK_SET
	
	LACL	0X0224
	SAH	PRO_VAR
;---load the value
	CALL	CHOUR_GET
	SAH	MSG_N		;Display CURRENT VALUE

	CALL	GET_LANGUAGE
	BZ	ACZ,LOCAL_PROMNU_TIME_1_PLAY_NotEnglish
	
	LAC	MSG_N
	CALL	HOUR_ADJ
	SAH	MSG_T
	
	LAC	MSG_T
	ANDK	0X0F
	CALL	LED_HLDISP

	LAC	MSG_T		;Announce CURRENT hour
	ANDK	0X0F
	CALL	ANNOUNCE_NUM
	
	LAC	MSG_T		;Announce CURRENT AM/PM
	CALL	ANN_AMPM

	RET
LOCAL_PROMNU_TIME_1_PLAY_NotEnglish:
	LAC	MSG_N
	ANDK	0X7F
	CALL	LED_HLDISP

	LAC	MSG_N		;Announce CURRENT hour
	ANDK	0X7F
	CALL	ANNOUNCE_NUM

	CALL	ANN_HOUR
	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME_2:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_TIME_VPSTOP	;VP end
;MAIN_PRO9_2_2_1:
	LAC	MSG
	XORL	CMSG_KEY2D
	BS	ACZ,LOCAL_PROMNU_TIME_2_FFW	;FFW
;MAIN_PRO9_2_2_3:	
	LAC	MSG
	XORL	CMSG_KEY2P
	;BS	ACZ,LOCAL_PROMNU_TIME_2_PFFW	;PFFW
;MAIN_PRO9_2_2_5:
	LAC	MSG
	XORL	CMSG_KEY1D
	BS	ACZ,LOCAL_PROMNU_TIME_2_PLAY	;Play
	
	RET
;---------------------------------------
LOCAL_PROMNU_TIME_2_FFW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACK	0
	SAH	PRO_VAR1
	
	LACK	0
	SAH	SYSTMP1
	LACK	23
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N

	CALL	GET_LANGUAGE
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_2_FFW_FR
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_2_FFW_DE

	LAC	MSG_N
	CALL	HOUR_ADJ
	SAH	MSG_T
	
	LAC	MSG_T
	ANDK	0X0F
	CALL	LED_HLDISP

	LAC	MSG_T		;Announce CURRENT hour
	ANDK	0X0F
	CALL	ANNOUNCE_NUM
	
	LAC	MSG_T		;Announce CURRENT AM/PM
	CALL	ANN_AMPM

	RET
LOCAL_PROMNU_TIME_2_FFW_DE:
	LAC	MSG_N
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_2_FFW_DE_1HOUR
LOCAL_PROMNU_TIME_2_FFW_FR:
	LAC	MSG_N
	ANDK	0X7F
	CALL	LED_HLDISP

	LAC	MSG_N		;Announce CURRENT hour
	ANDK	0X7F
	CALL	ANNOUNCE_NUM

	CALL	ANN_HOUR
	
	RET
LOCAL_PROMNU_TIME_2_FFW_DE_1HOUR:
	LAC	MSG_N
	ANDK	0X7F
	CALL	LED_HLDISP

	LACL	0XFF00|VOPIDX_NL_ein
	CALL	STOR_VP

	CALL	ANN_HOUR
	
	RET
;---------------------------------------
LOCAL_PROMNU_TIME_2_PFFW:
	LACK	0
	SAH	SYSTMP1
	LACK	23
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	LED_HLDISP
	
	RET
;---------------------------------------
LOCAL_PROMNU_TIME_2_PLAY:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACK	0
	SAH	PRO_VAR1

	LAC	MSG_N
	CALL	HOUR_SET
	
	LACL	0X0324
	SAH	PRO_VAR
;---Load the value
	CALL	CMIN_GET
	SAH	MSG_N		;CURRENT VALUE
	CALL	LED_HLDISP

	LAC	MSG_N		;Announce CURRENT VALUE
	CALL	ANNOUNCE_NUM

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME_3:	
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_TIME_VPSTOP	;VP end	
;LOCAL_PROMNU_TIME_3_1:
	LAC	MSG
	XORL	CMSG_KEY2D
	BS	ACZ,LOCAL_PROMNU_TIME_3_FFW	;FFW
;LOCAL_PROMNU_TIME_3_3:	
	LAC	MSG
	XORL	CMSG_KEY2P
	;BS	ACZ,LOCAL_PROMNU_TIME_3_PFFW	;FFW
;LOCAL_PROMNU_TIME_3_5:
	LAC	MSG
	XORL	CMSG_KEY1D
	BS	ACZ,LOCAL_PROMNU_TIME_3_PLAY	;Play

	RET
;---------------------------------------
LOCAL_PROMNU_TIME_3_FFW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACK	0
	SAH	PRO_VAR1
	
	LACK	0
	SAH	SYSTMP1
	LACK	59
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	LED_HLDISP
	
	LAC	MSG_N
	CALL	ANNOUNCE_NUM
	
	RET
;---------------------------------------
LOCAL_PROMNU_TIME_3_PFFW:
	LACK	0
	SAH	SYSTMP1
	LACK	59
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	LED_HLDISP
	
	RET
;---------------------------------------
LOCAL_PROMNU_0_PLAYTIME:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	
	BIT	ANN_FG,4
	BS	TB,LOCAL_PROMNU_TIME_3_PLAY_1	;设置过时间吗?
	
	LACL	0X0424
	SAH	PRO_VAR
	
	
	CALL	VP_PleaseSetTime
	
	BS	B1,LOCAL_PROMNU_TIME_3_PLAY_2
;---------------------------------------	
LOCAL_PROMNU_TIME_3_PLAY:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACK	0
	SAH	PRO_VAR1
	
	LAC	ANN_FG
	ORK	1<<4
	SAH	ANN_FG	;time have set

	LAC	MSG_N
	CALL	MIN_SET
	LACK	0
	CALL	SEC_SET
LOCAL_PROMNU_TIME_3_PLAY_1:
	
	CALL	CWEEK_GET
	CALL	VP_WEEK
	CALL	CHOUR_VP
	CALL	CMIN_VP
	CALL	CAMPM_VP
	CALL	BBEEP
LOCAL_PROMNU_TIME_3_PLAY_2:	
	LACL	0X0424
	SAH	PRO_VAR

	CALL	VPMSG_CHK
	BIT	ANN_FG,12
	BS	TB,LOCAL_PROMNU_TIME_STOP1
	LAC	MSG_T
	CALL	LED_HLDISP	;VP总数

	RET			;调节完毕后正常退出
LOCAL_PROMNU_TIME_STOP1:
	LAC	MSG_N
	CALL	LED_HLDISP	;VP总数

	RET
;---------------------------------------
LOCAL_PROMNU_TIME_4:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_TIME_4_VPSTOP

	RET
LOCAL_PROMNU_TIME_4_VPSTOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	CALL	BEEP		;BB

	CALL	CLR_TIMER
	CALL	CLR_TIMER2
	
	CALL	PORT_HSPLYL
	CALL	PORT_PLYL

	LACK	0X0
	SAH	PRO_VAR
	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_SELLANG:	
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR

	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_SELLANG_0	;reserved
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_SELLANG_1	;select
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_SELLANG_2	;vop confirm
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_SELLANG_1:
;LOCAL_PROMNU_SELLANG_1_0:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP		;VP end
;LOCAL_PROMNU_SELLANG_1_1:		
	LAC	MSG
	XORL	CMSG_KEY5D
	BS	ACZ,LOCAL_PROMNU_1_X_REW	;REW(select)
;LOCAL_PROMNU_SELLANG_1_2:	
	LAC	MSG
	XORL	CMSG_KEY2D
	BS	ACZ,LOCAL_PROMNU_1_X_FFW	;FFW(confirm)
;LOCAL_PROMNU_SELLANG_1_3:

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_SELLANG_0:
	RET
;---------------------------------------
LOCAL_PROMNU_1_X_REW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK

	LACK	0
	SAH	SYSTMP1
	LACK	2
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	
	LAC	MSG_N
	ADHL	LANG_TAB
	CALL	GetOneConst
	SAH	LED_L		;Display En/Fr/dE
	
	LACK	0X005
	CALL	STOR_VP
	LAC	MSG_N
	CALL	VP_SUNDAY
	
	RET
;---------------------------------------
LOCAL_PROMNU_1_X_FFW:
	CALL	INIT_DAM_FUNC
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;---stor language data
	LACL	TEL_RAM
	SAH	ADDR_D		;保存地址
	SAH	ADDR_S		;提取地址
	LACK	0
	SAH	OFFSET_S

	LACK	4
	SAH	OFFSET_D
	LAC	MSG_N
	CALL	STORBYTE_DAT
;---write into flash
	LACK	CGROUP_DATT
	CALL	SET_TELGROUP
	LACK	10
	SAH	COUNT
	CALL	TELNUM_WRITE
	CALL	DAT_WRITE_STOP
;---delate old data	
LOCAL_PROMNU_1_X_DELOLD:
	CALL	GET_TELT	;delete the data until only
	SBHK	2
	BS	SGN,LOCAL_PROMNU_1_X_DELOLD_END
	LACL	0XE501
	CALL	DAM_BIOSFUNC
	CALL	TEL_GC_CHK
	BS	B1,LOCAL_PROMNU_1_X_DELOLD
LOCAL_PROMNU_1_X_DELOLD_END:		
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	
	CALL	DAA_SPK

	LACK	0X005
	CALL	STOR_VP
	LAC	MSG_N
	CALL	VP_SUNDAY
	
	LAC	MSG_N
	CALL	STOR_LANGUAGE
	
	LACL	0X0234
	SAH	PRO_VAR
	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_SELLANG_2:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_SELLANG_2_VPSTOP

	RET
LOCAL_PROMNU_SELLANG_2_VPSTOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	CALL	BEEP		;BB

	CALL	CLR_TIMER
	CALL	CLR_TIMER2
	
	CALL	PORT_HSPLYL
	CALL	PORT_PLYL

	LACK	0X0
	SAH	PRO_VAR
	RET
;-------------------------------------------------------------------------------
;	Function : CHOUR_VP
;	
;	Generate a VP
;-------------------------------------------------------------------------------
CHOUR_VP:
	LACL	0X8200
	CALL	DAM_BIOSFUNC
	SAH	SYSTMP1

	CALL	GET_LANGUAGE
	SBHK	1
	BS	ACZ,CHOUR_VP_FR
	SBHK	1
	BS	ACZ,CHOUR_VP_DE

	LAC	SYSTMP1
	BS	ACZ,CHOUR_VP_12_0
	SBHK	12
	BS	ACZ,CHOUR_VP_12_0
	BS	SGN,CHOUR_VP_LESS12
	
	CALL	ANNOUNCE_NUM	;13..23
	
	RET
CHOUR_VP_12_0:			;0,12
	LACK	12
	CALL	ANNOUNCE_NUM

	RET

CHOUR_VP_LESS12:		;1..11
	LAC	SYSTMP1
	CALL	ANNOUNCE_NUM

	RET
;---------------------------------------
CHOUR_VP_DE:
	LAC	SYSTMP1
	SBHK	1
	BS	ACZ,CHOUR_VP_DE_1HOUR
CHOUR_VP_FR:
	LAC	SYSTMP1
	CALL	ANNOUNCE_NUM
	CALL	ANN_HOUR
	
	RET
CHOUR_VP_DE_1HOUR:
	LACL	0XFF00|VOPIDX_NL_ein
	CALL	STOR_VP
	CALL	ANN_HOUR
	
	RET
;-------------------------------------------------------------------------------
;	Function : CMIN_VP
;	
;	Generate a VP
;-------------------------------------------------------------------------------
CMIN_VP:
	LACL	0X8100
	CALL	DAM_BIOSFUNC
	BS	ACZ,CMIN_VP_1		;不报0分
	CALL	ANNOUNCE_NUM
CMIN_VP_1:
	LACK	0X005
	CALL	STOR_VP
	RET
;---------------------------------------
CAMPM_VP:	
	LACL	0X8200
	CALL	DAM_BIOSFUNC
	BS	ACZ,CURR_MIN_AM
	SBHK	12
	BZ	SGN,CURR_MIN_PM
CURR_MIN_AM:

	CALL	VP_AM	;AM
	RET
CURR_MIN_PM:

	CALL	VP_PM	;PM
	RET
;-------------------------------------------------------------------------------
;	Input	:ACCH(0..23)
;	Output	:ACCH(7..4)=1/0,ACCH(3..0)=1..12
;-------------------------------------------------------------------------------
HOUR_ADJ:
	SAH	SYSTMP0
	BS	ACZ,HOUR_ADJ_0		;0
	SBHK	12
	BS	SGN,HOUR_ADJ_1_11	;1..11
	BS	ACZ,HOUR_ADJ_12		;12
;HOUR_ADJ_13_23:			;13..23
	LAC	SYSTMP0
	SBHK	12
	ORK	0X10
	
	RET
HOUR_ADJ_0:
	LACK	(0X00)|12
	RET
HOUR_ADJ_12:
	LACK	(0X10)|12
	RET
HOUR_ADJ_1_11:
	LAC	SYSTMP0
	RET
;-------------------------------------------------------------------------------
;	Input	:ACCH(0..23)
;	Output	:ACCH(7..4)=1/0,ACCH(3..0)=1..12
;-------------------------------------------------------------------------------
ANN_AMPM:
	SAH	SYSTMP0
	ANDK	0X070
	BS	ACZ,ANN_AM
ANN_PM:
	CALL	VP_PM	;PM
	RET	
ANN_AM:
	CALL	VP_AM	;AM
	RET

;---------------
;	input : ACCH = WEEK(0/1/2/3/4/5/6)
;	output: no
;---------------
VP_SUNDAY:
	SAH	SYSTMP0
	SBHK	1
	BS	ACZ,VP_SUNDAY_FR
	SBHK	1
	BS	ACZ,VP_SUNDAY_DE
	
	LACL	0XFF00|VOPIDX_EN_Sunday
	CALL	STOR_VP
	RET
VP_SUNDAY_FR:
	LACL	0XFF00|VOPIDX_FR_Sunday
	CALL	STOR_VP
	RET
VP_SUNDAY_DE:
	LACL	0XFF00|VOPIDX_NL_Sunday
	CALL	STOR_VP
	RET
;-------------------------------------------------------------------------------

;===============================================================================
	
.END

