;-------------------------------------------------------------------------------
.NOLIST
.INCLUDE	REG_D20.inc
.INCLUDE	MD20U.inc
.INCLUDE	VOPidx.inc
.INCLUDE	CONST.inc
.INCLUDE	EXTERN.inc

.GLOBAL	REMOTE_PRO
;-------------------------------------------------------------------------------
;---------------------------------------
.EXTERN	GetOneConst

;-------------------------------------------------------------------------------
.LIST
.ORG	ADDR_SECOND
;-------------------------------------------------------------------------------
REMOTE_PRO:
	LAC	MSG			;接线后按ON/OFF(相当于CPC)
	XORL	CMSG_KEY6S
	BS	ACZ,REMOTE_PRO_STOP

	LAC	MSG			;HandSet off(处理同CPC)
	XORL	CMSG_HSOFF
	BS	ACZ,REMOTE_PRO_STOP
	LAC	MSG
	XORL	CMSG_HFON		;HandFree on(处理同CPC)
	BS	ACZ,REMOTE_PRO_STOP

	LAC	PRO_VAR
	ANDL	0X0F
	BS	ACZ,REMOTE_PRO0		;0 = IDEL
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW	;1 = play new
	SBHK	1
	BS	ACZ,REMOTE_PROPALL	;2 = play all
	SBHK	1
	BS	ACZ,REMOTE_PROMREC	;3 = record MEMO
	SBHK	4
	BS	ACZ,REMOTE_PROOGM	;7 = record/play OGM
	SBHK	1
	BS	ACZ,REMOTE_PROROMMONITOR	;8 = room monitor
	SBHK	1
	BS	ACZ,REMOTE_PRO9		;9 = reserved
	SBHK	1
	BS	ACZ,REMOTE_PRO10	;10 = exit
	
	RET
;---------------
REMOTE_PRO_STOP:
REMOTE_PRO_PMINE:
	LACL	CMSG_CPC
	CALL	STOR_MSG	;当作CPC一样处理
	
	RET

;-------------------------------------------------------------------------------
REMOTE_PRO0:
	LAC	MSG
	XORL	CMSG_INIT		;INITIAL(发两声BEEP)
	BS	ACZ,REMOTE_PRO0_INIT
;REMOTE_PRO0_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PRO0_REV_DTMF
;REMOTE_PRO0_2:	
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,REMOTE_PRO0_STOPVP	;VP完
;REMOTE_PRO0_3:	
	LAC	MSG
	XORL	CMSG_BTONE
	BS	ACZ,REMOTE_PRO0_TONE
;REMOTE_PRO0_4:	
	LAC	MSG
	XORL	CMSG_CTONE
	BS	ACZ,REMOTE_PRO0_TONE
;REMOTE_PRO0_5:	
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,REMOTE_PRO0_TMR
;REMOTE_PRO0_6:		
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
		
	RET
REMOTE_PRO0_CPC:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACL	0X005
	CALL	STOR_VP
	CALL	VPMSG_CHK
	
	LACK	10
	SAH	PRO_VAR

	RET
REMOTE_PRO0_INIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	BBEEP		;BB
	
	RET
REMOTE_PRO0_STOPVP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_REC
	CALL	LINE_START
	
	LACK	0			;开始计时
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	CALL	BCVOX_INIT
	
	RET
	
REMOTE_PRO0_REV_DTMF:
	CALL	CLR_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	CALL	BCVOX_INIT
	
	LAC	DTMF_VAL
	CALL	RMTFUNC_CHK
	BS	ACZ,REMOTE_PRO0_INDOORMONITOR	;0&#---in door monitor
	SBHK	1
	BS	ACZ,REMOTE_PRO0_PLYNEW		;2&5---play new
	SBHK	1
	BS	ACZ,REMOTE_PRO0_PLYALL		;2&#---play all
	SBHK	1
	BS	ACZ,REMOTE_PRO0_ERAOLD		;3&#---erase all
	SBHK	4
	BS	ACZ,REMOTE_PRO0_RECOGM		;7&#---record/play OGM
	SBHK	1
	BS	ACZ,REMOTE_PRO0_RECMEMO		;8&#---record memo
	SBHK	1
	BS	ACZ,REMOTE_PRO0_PROONOFF	;9&#---on/off
	SBHK	6
	BS	ACZ,REMOTE_PRO0_REV_DTMF_B	;#&#---
	
	RET

REMOTE_PRO0_PLYNEW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	CLR_FLAG
	
	CALL	VPMSG_CHK
	BIT	ANN_FG,12
	BS	TB,REMOTE_PRO0_PLYNEW_1

	CALL	BBBEEP		;BBB
	
	LACK	0
	SAH	PRO_VAR
	RET
REMOTE_PRO0_PLYNEW_1:
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	LACK	1
	SAH	PRO_VAR

	LACK	0
	SAH	MSG_ID

	LACL	0X005
	CALL	STOR_VP
	
	RET	
	
REMOTE_PRO0_PLYALL:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	VPMSG_CHK

	LACK	0
	SAH	MSG_ID
	
	BIT	ANN_FG,14
	BS	TB,REMOTE_PRO0_REV_DTMF_2_1

	CALL	BBBEEP		;BBB
	LACK	0
	SAH	PRO_VAR
	
	BS	B1,REMOTE_PRO0_REV_DTMF_2_END
REMOTE_PRO0_REV_DTMF_2_1:
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	LACK	2
	SAH	PRO_VAR

	LACL	0X005
	CALL	STOR_VP
REMOTE_PRO0_REV_DTMF_2_END:
	
	RET
;---------------------------------------
REMOTE_PRO0_ERAOLD:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	VPMSG_CHK
	LACK	0
	SAH	PRO_VAR
	
	LACL	0X6100
	CALL	DAM_BIOSFUNC
	
	LACL	0X6080
	CALL	DAM_BIOSFUNC

	CALL	VPMSG_CHK
	BIT	ANN_FG,14
	BS	TB,REMOTE_PRO0_REV_DTMF_3_1

	CALL	BBBEEP		;BBB
	
	RET
REMOTE_PRO0_REV_DTMF_3_1:	
	CALL	BBEEP		;BB

	RET
;---------------------------------------
REMOTE_PRO0_RECOGM:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	
	CALL	OGM_SELECT	;Delete old first
	LAC	MSG_ID
	CALL	VPMSG_DEL
	CALL	GC_CHK
	
	CALL	VPMSG_CHK
	
	BIT	ANN_FG,13
	BS	TB,REMOTE_PRO0_RECOGM_MFUL
	
	LACK	0X0007
	SAH	PRO_VAR
	CALL	LBEEP		;Lbee...
	
	RET
REMOTE_PRO0_RECOGM_MFUL:
	CALL	INIT_DAM_FUNC
	CALL	BBBEEP
	CALL	VP_MemoryFull
	LACK	0X0017
	SAH	PRO_VAR
	
	RET
;---------------------------------------
REMOTE_PRO0_RECMEMO:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	
	BIT	ANN_FG,13
	BS	TB,REMOTE_PRO0_RECMEMO_MFUL
	
	LACK	0X0003
	SAH	PRO_VAR
	CALL	LBEEP		;Lbee...

	RET
REMOTE_PRO0_RECMEMO_MFUL:		;mfull 直接退出
	CALL	BBBEEP
	CALL	VP_MemoryFull
	LACK	0
	SAH	PRO_VAR

	RET

REMOTE_PRO0_INDOORMONITOR:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	LBEEP		;Lbee...
		
	LACK	0X0008
	SAH	PRO_VAR
	
	RET

REMOTE_PRO0_PROONOFF:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	LAC	EVENT
	XORL	1<<9
	SAH	EVENT

	BIT	EVENT,9
	BS	TB,REMOTE_PRO0_PROOFF
;REMOTE_PRO0_PROON:
	CALL	BEEP
	CALL	BEEP
	
	RET
REMOTE_PRO0_PROOFF:
	CALL	BEEP
	CALL	BEEP
	CALL	BEEP
	
	RET
	
REMOTE_PRO0_REV_DTMF_A:
	CALL	INIT_DAM_FUNC	
	CALL	DAA_LIN_SPK
	
	LACL	0X005
	CALL	STOR_VP

	RET
REMOTE_PRO0_REV_DTMF_B:		;退出准备
	
	RET
;---
REMOTE_PRO0_EXIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
		
	LACK	10
	SAH	PRO_VAR

	LACL	0X005
	CALL	STOR_VP

	RET
REMOTE_PRO0_TONE:
	BS	B1,REMOTE_PRO0_EXIT
REMOTE_PRO0_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	;SBHK	10
	SBHK	20		;20s无操作退出
	BZ	SGN,REMOTE_PRO0_EXIT
	
	RET	
;=======================================================================
;11111111111111111111111111111111111111111111111111111111111111111111111
REMOTE_PROPNEW:				;播放新message
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROPNEW_CPC
	
	LAC	PRO_VAR
	SFR	4
	ANDK	0XF
	BS	ACZ,REMOTE_PROPNEW0
	SBHK	1
	BS	ACZ,REMOTE_PROX_PAUSE		;功能暂停
	SBHK	1
	BS	ACZ,REMOTE_PROXTMR_PAUSE	;时间暂停
	
	RET
;---------------
REMOTE_PROPNEW_CPC:
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACL	0X005
	CALL	STOR_VP
	
	CALL	REAL_DEL
	CALL	GC_CHK
	CALL	VPMSG_CHK
	
	LACK	10
	SAH	PRO_VAR
	
	RET
;---------------
REMOTE_PROPNEW0:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROPNEW_OVER
;REMOTE_PROPNEW0_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROPNEW_DTMF
;REMOTE_PROPNEW0_2:
	LAC	MSG
	XORL	CMSG_BTONE		;CMSG_BTONE
	BS	ACZ,REMOTE_PRO10_END
;REMOTE_PROPNEW0_3:
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROPNEW0_TMR
;REMOTE_PROPNEW0_4:	
	
	
	RET
;---------------处理消息
REMOTE_PROPNEW0_TMR:
REMOTE_PROPX_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHL	160		;2分40秒
	;SBHL	16
	BZ	SGN,REMOTE_PROPX_TMRPASUE
	
	RET
REMOTE_PROPX_TMRPASUE:
	LAC	CONF
	ORL	1<<8
	CALL	DAM_BIOSFUNC
	
	LACL	500
	CALL	PAUBEEP		;BEEP Prompt

	LAC	PRO_VAR
	ORK	0X20
	SAH	PRO_VAR
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	RET

REMOTE_PROPNEW_OVER:
	LAC	MSG_ID
	SBH	MSG_T
	BZ	SGN,REMOTE_PROX_PLYSTOP
;REMOTE_PRO1_PLAY_OVER1:

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
	
	LAC	FILE_ID			;next message
	ADHK	1
	SAH	FILE_ID

	CALL	FFW_MANAGE	
	BZ	ACZ,REMOTE_PROX_PLYSTOP	;没新的了
	BS	B1,REMOTE_PROX_LOADVP
		
;---------------------------------------
REMOTE_PROPNEW_DTMF:	
	LAC	DTMF_VAL
	CALL	RMTFUNC_CHK
	SBHK	3
	BS	ACZ,REMOTE_PROX_ERAPLYING	;3#---erase playing message
	SBHK	3
	BS	ACZ,REMOTE_PROPNEW_PLYPRE	;6#---skip to previous message
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW_NEXT		;7#---skip to next message
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW_REPEAT	;8#---repeat message
	SBHK	6
	BS	ACZ,REMOTE_PROX_DO_PAUSE	;*#---remote prompt
	SBHK	1
	BS	ACZ,REMOTE_PROX_PLYSTOP	;##---hang off	
	
	RET
;---------------
REMOTE_PROX_ERAPLYING:
	CALL	INIT_DAM_FUNC
	LAC	MSG_ID
	CALL	SET_DELMARK
	CALL	INIT_DAM_FUNC
	LACK	0X025
	CALL	STOR_VP
	;CALL	BEEP
	
	RET
;-------
REMOTE_PROPNEW_PLYPRE:
	CALL	INIT_DAM_FUNC

	LAC	MSG_ID
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW_PLYPRE_1

	LAC	MSG_ID
	SBHK	1
	SAH	MSG_ID	
	
	LAC	FILE_ID
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW_PLYPRE_1
	SAH	FILE_ID
	
	CALL	REW_MANAGE
REMOTE_PROPNEW_PLYPRE_1:
	BS	B1,REMOTE_PROX_LOADVP
;-------
REMOTE_PROPNEW_REPEAT:
	CALL	INIT_DAM_FUNC
	BS	B1,REMOTE_PROX_LOADVP
;-------
REMOTE_PROPNEW_NEXT:
	CALL	INIT_DAM_FUNC
	BS	B1,REMOTE_PROPNEW_OVER
;-------
REMOTE_PROX_DO_PAUSE:
	LAC	CONF
	ORL	0X0100
	SAH	CONF
	CALL	DAM_BIOS
	
	LAC	PRO_VAR
	ORK	0X10
	SAH	PRO_VAR
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	RET

REMOTE_PROX_PAUSE:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROX_PAUSE_DTMF
REMOTE_PROX_PAUSE_1:
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROX_PAUSE_TIMER
	
	RET
;---------------
REMOTE_PROX_PAUSE_DTMF:
	LAC	DTMF_VAL
	CALL	RMTFUNC_CHK
	SBHK	3
	BS	ACZ,REMOTE_PROX_ERAPLYING	;3#---erase playing message
	SBHK	3
	BS	ACZ,REMOTE_PROPNEW_PLYPRE	;6#---skip to previous message
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW_NEXT		;7#---skip to next message
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW_REPEAT	;8#---repeat message
	SBHK	6
	BS	ACZ,REMOTE_PROX_DO_PAUSE	;*#---play again
	SBHK	1
	BS	ACZ,REMOTE_PROX_PLYSTOP		;##---hang off	
	
	RET
;---------------
REMOTE_PROX_PAUSE_TIMER:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	10
	BS	SGN,REMOTE_PROX_PAUSE_TIMER_1
	
	CALL	INIT_DAM_FUNC
	CALL	BBEEP
	LACK	0
	SAH	PRO_VAR

REMOTE_PROX_PAUSE_TIMER_1:	
	RET
REMOTE_PROX_PAUSE_PLY:
	LAC	CONF
	ANDL	~(1<<8)
	CALL	DAM_BIOSFUNC
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	RET
;-------------------------------------------------------------------------------
REMOTE_PROXTMR_PAUSE:		;时间暂停
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROXTMR_PAUSE_DTMF
REMOTE_PROXTMR_PAUSE_1:
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROXTMR_PAUSE_TIMER

	RET
;---------------
REMOTE_PROXTMR_PAUSE_DTMF:
	LAC	CONF
	ANDL	~(1<<8)
	CALL	DAM_BIOSFUNC
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	LACK	0
	SAH	PRO_VAR1

	RET
REMOTE_PROXTMR_PAUSE_TIMER:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	8
	BZ	SGN,REMOTE_PROXTMR_PAUSE_TIMER_EXIT
	
	RET
REMOTE_PROXTMR_PAUSE_TIMER_EXIT:
	CALL	INIT_DAM_FUNC

	LACL	0X6100
	SAH	CONF
	CALL	DAM_BIOS

	BS	B1,REMOTE_PRO0_EXIT

;=======================================================================
;22222222222222222222222222222222222222222222222222222222222222222222222
REMOTE_PROPALL:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROPALL_CPC
	
	LAC	PRO_VAR
	SFR	4
	ANDK	0XF
	BS	ACZ,REMOTE_PROPALL0		;播放
	SBHK	1
	BS	ACZ,REMOTE_PROX_PAUSE		;功能暂停
	SBHK	1
	BS	ACZ,REMOTE_PROXTMR_PAUSE	;时间暂停

	RET
;---------------------------------------
REMOTE_PROPALL_CPC:
	BS	B1,REMOTE_PROPNEW_CPC
;-------------------------------------------------------------------------------
REMOTE_PROPALL0:	
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROPALL_OVER
REMOTE_PROPALL0_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROPALL_DTMF
REMOTE_PROPALL0_2:
	LAC	MSG
	XORL	CMSG_BTONE		;CMSG_BTONE
	BS	ACZ,REMOTE_PRO10_END
REMOTE_PROPALL0_3:	
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROPALL0_TMR
	
	
	RET
;---------------------------------------
REMOTE_PROPALL0_TMR:
	BS	B1,REMOTE_PROPX_TMR
;---------------------------------------
REMOTE_PROPALL_OVER:	
	LAC	MSG_ID
	SBH	MSG_T
	BZ	SGN,REMOTE_PROX_PLYSTOP

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
	
	LAC	FILE_ID			;next message
	ADHK	1
	SAH	FILE_ID
REMOTE_PROX_LOADVP:
	CALL	BEEP

	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
	
	LAC	MSG_ID		;Check timer set or not
	ORL	0XA500
	CALL	DAM_BIOSFUNC
	BS	ACZ,REMOTE_PROX_LOADVP_END
		
	CALL	MSG_WEEK
	CALL	MSG_HOUR
	CALL	MSG_MIN
	CALL	MSG_AMPM
REMOTE_PROX_LOADVP_END:
	RET
;---------------------------------------
REMOTE_PROPALL_DTMF:	
	LAC	DTMF_VAL
	CALL	RMTFUNC_CHK
	SBHK	3
	BS	ACZ,REMOTE_PROX_ERAPLYING	;3#---erase playing message
	SBHK	3
	BS	ACZ,REMOTE_PROPALL_PLYPRE	;6#---skip to previous message
	SBHK	1
	BS	ACZ,REMOTE_PROPALL_NEXT		;7#---skip to next message
	SBHK	1
	BS	ACZ,REMOTE_PROPALL_REPEAT	;8#---repeat message
	SBHK	6
	BS	ACZ,REMOTE_PROX_DO_PAUSE	;*#---do pause
	SBHK	1
	BS	ACZ,REMOTE_PROX_PLYSTOP		;##---hang off	
	
	RET
;---------------------------------------
REMOTE_PROPALL_PLYPRE:		;前一个
	CALL	INIT_DAM_FUNC

	LAC	MSG_ID
	SBHK	1
	BS	ACZ,REMOTE_PROPALL_PLYPRE_1 ;第一个吗?
	
	LAC	MSG_ID
	SBHK	1
	SAH	MSG_ID	
	
	LAC	FILE_ID
	SBHK	1
	BS	ACZ,REMOTE_PROPALL_PLYPRE_1
	SAH	FILE_ID
REMOTE_PROPALL_PLYPRE_1:
	BS	B1,REMOTE_PROX_LOADVP
;---------------------------------------
REMOTE_PROPALL_REPEAT:		;重复当前的一个
	CALL	INIT_DAM_FUNC
	BS	B1,REMOTE_PROX_LOADVP
;---------------------------------------
REMOTE_PROPALL_NEXT:		;下一个
	CALL	INIT_DAM_FUNC
	BS	B1,REMOTE_PROPALL_OVER
;---------------------------------------
REMOTE_PROX_PLYSTOP:
	CALL	INIT_DAM_FUNC
	CALL	BBEEP		;BB
	CALL	VPMSG_CHK
	
	LACL	0X6100
	SAH	CONF
	CALL	DAM_BIOS

	LACK	0
	SAH	PRO_VAR
	SAH	PRO_VAR1
	
	RET
;=======================================================================
;33333333333333333333333333333333333333333333333333333333333333333333333
REMOTE_PROMREC:
	LAC	PRO_VAR
	SFR	4
	BS	ACZ,REMOTE_PROMREC0	;play LBEEP
	SBHK	1
	BS	ACZ,REMOTE_PROMREC1	;record MEMO
	SBHK	1
	BS	ACZ,REMOTE_PROMREC2	;record end BEEP
	RET
;---------------------------------------
REMOTE_PROMREC0:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROMREC0_OVER
	
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	RET
;---	
REMOTE_PROMREC0_OVER:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_REC
	LACK	0X0013
	SAH	PRO_VAR
	CALL	VPMSG_CHK

	CALL	REC_START

	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1

	RET
REMOTE_PROMREC1:
	LAC	MSG
	XORL	CMSG_TMR		;TIMER
	BS	ACZ,REMOTE_PROMREC1_TIMER
	LAC	MSG
	XORL	CMSG_TMR2		;TIMER2
	BS	ACZ,REMOTE_PROMREC1_TIMER2
REMOTE_PROMREC1_1:
	LAC	MSG
	XORL	CREV_DTMFS		;DTMF
	BS	ACZ,REMOTE_PROMREC1_DTMFS
	LAC	MSG
	XORL	CREV_DTMF		;DTMF
	BS	ACZ,REMOTE_PROMREC1_DTMF
REMOTE_PROMREC1_2:	
	LAC	MSG
	XORL	CMSG_BTONE
	BS	ACZ,REMOTE_PROMREC1_BTONE
REMOTE_PROMREC1_3:	
	LAC	MSG
	XORL	CMSG_CTONE
	BS	ACZ,REMOTE_PROMREC1_CTONE
REMOTE_PROMREC1_4:
	LAC	MSG
	XORL	CREC_FULL		;REC_FULL
	BS	ACZ,REMOTE_PROMREC1_STOP
REMOTE_PROMREC1_5:
	;LAC	MSG
	;XORL	CDTMF_TMR1		;DTMF TIMER
	;BS	ACZ,REMOTE_PROMREC1_DTMFTIMER	
REMOTE_PROMREC1_6:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROMREC1_CPC
	
	RET

;---------------
REMOTE_PROMREC1_CPC:
	LAC	PRO_VAR1
	SBHK	2
	BZ	SGN,REMOTE_PROMREC1_CPC1
	
	LAC	CONF
	ORL	1<<11
	SAH	CONF
	CALL	DAM_BIOSFUNC
REMOTE_PROMREC1_CPC1:	
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACK	0X005
	CALL	STOR_VP

	CALL	VPMSG_CHK
	
	LACK	0X00A
	SAH	PRO_VAR

	RET

REMOTE_PROMREC1_DTMFTIMER:
	LAC	PRO_VAR2
	ADHK	1
	SAH	PRO_VAR2
	
	RET
REMOTE_PROMREC1_CTONE:
REMOTE_PROMREC1_BTONE:
	CALL	INIT_DAM_FUNC
	CALL	VPMSG_CHK
	LAC	MSG_T
	CALL	GET_VPTLEN
	SBHK	3
	BZ	SGN,REMOTE_PROMREC1_END
;---删除比3s短的录音
	LAC	MSG_T
	CALL	VPMSG_DEL
	CALL	GC_CHK
REMOTE_PROMREC1_END:
	BS	B1,REMOTE_PRO0_TONE
REMOTE_PROMREC1_TIMER:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1	;时长不受限制
	
	RET

REMOTE_PROMREC1_TIMER2:
	LAC	PRO_VAR2
	ADHK	1
	SAH	PRO_VAR2
	
	RET
;---------------------------------------
REMOTE_PROMREC1_DTMFS:
	LAC	DTMF_VAL
	XORL	0XF8
	BS	ACZ,REMOTE_PROMREC1_8DTMF	;pressed "8"

	RET
REMOTE_PROMREC1_8DTMF:		;是8就计时清0
	LACK	0
	SAH	PRO_VAR2
	LACL	400
	CALL	SET_TIMER2
	
	RET
;---------------------------------------
REMOTE_PROMREC1_DTMF:
	
	LAC	DTMF_VAL
	CALL	RMTFUNC_CHK
	SBHK	8
	BS	ACZ,REMOTE_PROMREC1_DTMF_STOP	;pressed "8","#"

	RET
;---------------------------------------
REMOTE_PROMREC1_DTMF_STOP:
	LAC	CONF
	OR	PRO_VAR2
	ADHK	1
	;SAH	CONF
	CALL	DAM_BIOSFUNC
REMOTE_PROMREC1_STOP:		;mfull/timer over
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK

	CALL	CLR_TIMER2
;---
	CALL	VPMSG_CHK
	LAC	MSG_T
	CALL	GET_VPTLEN
	SBHK	3
	BZ	SGN,REMOTE_PROMREC1_STOP1
;---删除比3s短的录音
	LAC	MSG_T
	CALL	VPMSG_DEL
	CALL	GC_CHK
REMOTE_PROMREC1_STOP1:
		
	CALL	BEEP
	LACK	0X003F		;延时
	CALL	STOR_VP

	CALL	VPMSG_CHK
	
	LACK	0X0023
	SAH	PRO_VAR
	
	RET
;-------------------------------------------------
REMOTE_PROMREC2:
	LAC	MSG
	XORL	CVP_STOP		
	BS	ACZ,REMOTE_PROMREC2_VPSTOP	;beep播放完毕
	
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC

	RET
REMOTE_PROMREC2_VPSTOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	BBEEP

	LACK	0X0
	SAH	PRO_VAR
	SAH	PRO_VAR1
	
	RET
;=======================================================================
;44444444444444444444444444444444444444444444444444444444444444444444444
;REMOTE_PRO4:
	RET
;=======================================================================
;55555555555555555555555555555555555555555555555555555555555555555555555
;REMOTE_PRO5:
	RET
;=======================================================================
;66666666666666666666666666666666666666666666666666666666666666666666666
;REMOTE_PRO6:
	RET
;=======================================================================
;77777777777777777777777777777777777777777777777777777777777777777777777
REMOTE_PROOGM:
	LAC	PRO_VAR
	SFR	4
	BS	ACZ,REMOTE_PROOGM0	;play LBEEP
	SBHK	1
	BS	ACZ,REMOTE_PROOGM_REC	;record OGM
	SBHK	1
	BS	ACZ,REMOTE_PROOGM_PLY	;play OGM
	
	RET
;-------------------------------------------------------------------------------
REMOTE_PROOGM_REC:
	LAC	MSG
	XORL	CMSG_TMR		;TIMER
	BS	ACZ,REMOTE_PROOGM_REC_TMR
	LAC	MSG
	XORL	CMSG_TMR2		;TIMER2
	BS	ACZ,REMOTE_PROOGM_REC_TMR2
;REMOTE_PRO7_RECORD_1:
	LAC	MSG
	XORL	CREV_DTMFS		;DTMFS
	BS	ACZ,REMOTE_PROOGM_REC_DTMFS
	LAC	MSG
	XORL	CREV_DTMF		;DTMF
	BS	ACZ,REMOTE_PROOGM_REC_DTMF
;REMOTE_PRO7_RECORD_2:	
	LAC	MSG
	XORL	CMSG_BTONE
	BS	ACZ,REMOTE_PROOGM_REC_BTONE
;REMOTE_PRO7_RECORD_3:	
	LAC	MSG
	XORL	CMSG_CTONE
	BS	ACZ,REMOTE_PROOGM_REC_CTONE
;REMOTE_PRO7_RECORD_4:	
	LAC	MSG
	XORL	CREC_FULL		;REC_FULL
	BS	ACZ,REMOTE_PROOGM_REC_MFUL
;REMOTE_PRO7_RECORD_5:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROOGM_REC_CPC
;REMOTE_PRO7_RECORD_6:
	LAC	MSG			;Beep/Memfull
	XORL	CVP_STOP
	BS	ACZ,REMOTE_PROOGM_REC_STOP

	RET
;---------------------------------------
REMOTE_PROOGM_REC_CPC:
	BS	B1,REMOTE_PROMREC1_CPC
;---------------------------------------
REMOTE_PROOGM_REC_MFUL:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	BBBEEP
	CALL	VP_MemoryFull
	
	RET	
;---------------------------------------	
REMOTE_PROOGM_REC_CTONE:
REMOTE_PROOGM_REC_BTONE:
	CALL	INIT_DAM_FUNC
	CALL	VPMSG_CHK
	LAC	MSG_T
	CALL	GET_VPTLEN
	SBHK	3
	BZ	SGN,REMOTE_PRO7_RECORD_END
;---删除比3s短的录音
	LAC	MSG_T
	CALL	VPMSG_DEL
	CALL	GC_CHK
REMOTE_PRO7_RECORD_END:
	BS	B1,REMOTE_PRO0_TONE
;---------------------------------------
REMOTE_PROOGM_REC_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	60
	BZ	SGN,REMOTE_PROOGM_REC_STOP

	RET
;---------------------------------------
REMOTE_PROOGM_REC_TMR2:
	LAC	PRO_VAR2
	ADHK	1
	SAH	PRO_VAR2
	
	RET
;---------------------------------------
REMOTE_PROOGM_REC_DTMFS:
	CALL	BCVOX_INIT
	
	LAC	DTMF_VAL
	XORL	0XF7
	BS	ACZ,REMOTE_PROOGM_REC_7DTMFS	;pressed "7","#"

	RET
;---------------------------------------
REMOTE_PROOGM_REC_7DTMFS:
	LACK	0
	SAH	PRO_VAR2
	LACL	400
	CALL	SET_TIMER2

	RET
;---------------------------------------
REMOTE_PROOGM_REC_DTMF:	
	LAC	DTMF_VAL
	CALL	RMTFUNC_CHK
	SBHK	7
	BS	ACZ,REMOTE_PROOGM_REC_DTMF_STOP		;pressed "7","#"

	RET
;---------------------------------------
REMOTE_PROOGM_REC_DTMF_STOP:
	LAC	PRO_VAR1
	SBHK	2
	BZ	SGN,REMOTE_PROOGM_REC_DTMF_STOP1
	
	LAC	CONF
	ORL	1<<11
	CALL	DAM_BIOSFUNC	;录音太短,直接删除
REMOTE_PROOGM_REC_DTMF_STOP1:	
	LAC	CONF
	OR	PRO_VAR2
	ADHK	1
	CALL	DAM_BIOSFUNC
	
REMOTE_PROOGM_REC_STOP:		;处理"#","mfull"

	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	LACK	0X0027
	SAH	PRO_VAR
	
	CALL	CLR_TIMER2
	
	CALL	OGM_SELECT
	
	CALL	BEEP
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP

	CALL	OGM_SELECT
	BZ	ACZ,MAIN_PRO0_PLAY_OGM1
	
	CALL	INIT_DAM_FUNC
	CALL	BEEP
	CALL	VP_DefOGM
	
MAIN_PRO0_PLAY_OGM1:

	RET	

;-------------------------------------------------------------------------------	
REMOTE_PROOGM0:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PRO7_PLAY_OVER
	
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	RET
;---------------------------------------
REMOTE_PRO7_PLAY_OVER:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_REC
	LACK	0X0017
	SAH	PRO_VAR
;---
	CALL	OGM_SELECT
;-------delete the old OGM fisrt------------
	;LAC	MSG_ID
	;CALL	VPMSG_DEL
	;CALL	GC_CHK
;---set user index data0"OGM_ID"------------
    	LAC	MSG_N
    	ORL	0X8D00
    	CALL	DAM_BIOSFUNC
;---	
	CALL	REC_START
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER

	RET
;---------------------------------------
REMOTE_PROOGM_PLY:
	LAC	MSG
	XORL	CVP_STOP		;CVP_STOP
	BS	ACZ,REMOTE_PROOGM_PLY_STOP
;REMOTE_PRO7_2_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROOGM_PLY_DTMF
;REMOTE_PRO7_2_2:	
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	RET
REMOTE_PROOGM_PLY_STOP:
	CALL	INIT_DAM_FUNC	
	CALL	BBEEP
	
	LACK	0
	SAH	PRO_VAR
	SAH	PRO_VAR1

	RET

REMOTE_PROOGM_PLY_DTMF:
	LAC	DTMF_VAL
	CALL	RMTFUNC_CHK
	SBHK	3
	BS	ACZ,REMOTE_PROOGM_PLY_DTMF_3	;"3","#"
	SBHK	12
	BS	ACZ,REMOTE_PROOGM_PLY_STOP	;#

	RET

REMOTE_PROOGM_PLY_DTMF_3:
	CALL	INIT_DAM_FUNC
	CALL	OGM_SELECT
;---delete the old OGM fisrt------------
	LAC	MSG_ID
	CALL	VPMSG_DEL
	CALL	GC_CHK

	CALL	BBEEP		;BB
	LACK	0
	SAH	PRO_VAR
	
	RET
;=======================================================================
;88888888888888888888888888888888888888888888888888888888888888888888888
REMOTE_PROROMMONITOR:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,REMOTE_PRO8_VOPLAY
	SBHK	1
	BS	ACZ,REMOTE_PROROMMONITING
	
	RET
;---------------------------------------
REMOTE_PROROMMONITING:

;REMOTE_PRORMONIT_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PRORMONIT_DTMF
;REMOTE_PRORMONIT_2:
	LAC	MSG
	XORL	CMSG_TMR		;TIMER
	BS	ACZ,REMOTE_PRORMONIT_TIMER
;REMOTE_PRORMONIT_3:	

	RET
;---------------处理消息
REMOTE_PRORMONIT_DTMF:
	LAC	DTMF_VAL
	CALL	RMTFUNC_CHK
	BS	ACZ,REMOTE_PRORMONIT_RESTART	;"0","#"
	SBHK	5
	BS	ACZ,REMOTE_PRORMONIT_STOP	;"5","#"

	RET

REMOTE_PRORMONIT_RESTART:
	LACK	0
	SAH	PRO_VAR1

	RET

REMOTE_PRORMONIT_STOP:
	CALL	INIT_DAM_FUNC
	CALL	BCVOX_INIT
	
	LACK	0
	SAH	PRO_VAR
	SAH	PRO_VAR1
	
	LACL	CMSG_INIT
	CALL	STOR_MSG

	RET

REMOTE_PRORMONIT_TIMER:
	LACL	CTMR_CTONE	;---不让产生VOX,CTONE消息,可产生BTONE
	SAH	TMR_VOX
	SAH	TMR_CTONE
	
	LAC	PRO_VAR1	;计时
	ADHK	1
	SAH	PRO_VAR1
	SBHK	30		;30s计时
	BZ	SGN,REMOTE_PRORMONIT_STOP
		
	RET
;-------
REMOTE_PRO8_VOPLAY:
	LAC	MSG
	XORL	CVP_STOP			;CVP_STOP
	BS	ACZ,REMOTE_PRO8_VOPLAY_END
	
	RET	
REMOTE_PRO8_VOPLAY_END:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ROMMOR_ON
	CALL	LINE_START
	
	LACK	0X0018
	SAH	PRO_VAR
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1


	RET	
;=======================================================================
;99999999999999999999999999999999999999999999999999999999999999999999999
REMOTE_PRO9:	
	LACK	0
	SAH	PRO_VAR
	
	LACL	CMSG_INIT
	CALL	STOR_MSG
	RET
;=======================================================================
;#######################################################################
REMOTE_PRO10:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,REMOTE_PRO10_END
	
	RET
REMOTE_PRO10_END:
	CALL	INIT_DAM_FUNC	
	CALL	CLR_FUNC	;先空
	LACL	LOCAL_PRO	;进入本地操作
     	CALL	PUSH_FUNC	
	LACK	0
	SAH	PRO_VAR

	LACL	CMODE9
	CALL	DAM_BIOSFUNC

	;LACL	0X0018
	;CALL	STOR_VP		;延时192ms
	LACL	CMSG_INIT
	CALL	STOR_MSG

	CALL	DAA_OFF	
	CALL	HOOK_OFF

	RET
;-------------------------------------------------------------------------------
;----------------------------------------------------------------------------
;       Function : RMTFUNC_CHK
;       Password check
;	Input  : ACCH = VALUE(DTMF_VAL)
;       Output : ACCH = 0 - password in ok
;                       1 - password for mailbox 1
;                       2 - password for mailbox 2
;                       3 - password for mailbox 3
;                       0XFF - password fail
;-------------------------------------------------------------------------------
RMTFUNC_CHK:
        SAH	SYSTMP0
;RMTFUNC_CHK1:
        LAC     PSWORD_TMP
        SFL	8
	OR	SYSTMP0
        SAH     PSWORD_TMP	;PSWORD_TMP keep the new input digit string
        
        LAC     PSWORD_TMP
	SAH     SYSTMP0
	
	LACK	0
	SAH	PSWORD_TMP
;-------------------------------------------------------------------------------
	LAC     SYSTMP0
        XORL	0XF0FF		;"0","#"
        BS      ACZ,RMTFUNC_0_POU_OK
        LAC     SYSTMP0
        XORL	0XF2F5		;"2","5"
        BS      ACZ,RMTFUNC_2_5_OK
        LAC     SYSTMP0
        XORL	0XF2FF		;"2","#"
        BS      ACZ,RMTFUNC_2_POU_OK
        LAC     SYSTMP0
        XORL	0XF3FF		;"3","#"
        BS      ACZ,RMTFUNC_3_POU_OK
        LAC     SYSTMP0
        XORL	0XF5FF		;"5","#"
        BS      ACZ,RMTFUNC_5_POU_OK
        LAC     SYSTMP0
        XORL	0XF6FF		;"6","#"
        BS      ACZ,RMTFUNC_6_POU_OK
        LAC     SYSTMP0
        XORL	0XF7FF		;"7","#"
        BS      ACZ,RMTFUNC_7_POU_OK
        LAC     SYSTMP0
        XORL	0XF8FF		;"8","#"
        BS      ACZ,RMTFUNC_8_POU_OK
        LAC     SYSTMP0
        XORL	0XF9FF		;"9","#"
        BS      ACZ,RMTFUNC_9_POU_OK
        LAC     SYSTMP0
        XORL	0XFEFF		;"*","#"
        BS      ACZ,RMTFUNC_AST_POU_OK
        LAC     SYSTMP0
        XORL	0XFFFF		;"#","#"
        BS      ACZ,RMTFUNC_POU_POU_OK
;---
RMTFUNC_NOT_IN:		;the intput not digital or wrong remote access code
	LAC     SYSTMP0
	SAH     PSWORD_TMP
	
        LACL    0XFF
        RET	
RMTFUNC_INDMONITOR_OK:
RMTFUNC_0_POU_OK:
	LACK	0

        RET
RMTFUNC_2_5_OK:

	LACK	1
        RET
RMTFUNC_2_POU_OK:
	LACK	2
	RET
RMTFUNC_3_POU_OK:
	LACK	3
	RET
RMTFUNC_5_POU_OK:
	LACK	5
	RET
RMTFUNC_6_POU_OK:
	
	LACK	6
	RET
RMTFUNC_7_POU_OK:

	LACK	7
	RET
RMTFUNC_8_POU_OK:

	LACK	8
	RET
RMTFUNC_9_POU_OK:

	LACK	9
	RET
RMTFUNC_AST_POU_OK:
	
	LACK	0XE
	RET
RMTFUNC_POU_POU_OK:

	LACK	0XF
	RET
;-------------------------------------------------------------------------------
.INCLUDE	l_ply.asm
;-------------------------------------------------------------------------------
.END
	