/***************************************
Ω‚ ÕASCII
***************************************/
ASC_REG	==	INT_TEMP0

ASCII_NUM:
	DISI
	MOV	ASC_REG,A
	SUB	A,@32
	JPZ	ASCII_NUM_SPACE
	SUBA	ASC_REG,@58
	JPNC	ASCII_NUM_NUM
	JMP	ASCII_NUM_ERROR
ASCII_NUM_SPACE:
	MOV	A,@0X10
	JMP	ASCII_RET
ASCII_NUM_NUM:
	SUBA	ASC_REG,@48
	JMP	ASCII_RET
ASCII_NUM_ERROR:
	MOV	A,@0X10
	JMP	ASCII_RET

ASCII_CH:
	DISI
	MOV	ASC_REG,A
	SUB	A,@32
	JPZ	ASCII_CH_SPACE
	SUBA	ASC_REG,@58
	JPNC	ASCII_CH_NUM
	SUBA	ASC_REG,@91
	JPNC	ASCII_CH_CLETTER
	SUBA	ASC_REG,@123
	JPNC	ASCII_CH_SLETTER
	JMP	ASCII_CH_ERROR			; ERROR
ASCII_CH_SPACE:
	MOV	A,@CH_BLANK
	JMP	ASCII_RET
ASCII_CH_NUM:
	SUBA	ASC_REG,@48
	JMP	ASCII_RET
ASCII_CH_CLETTER:
	SUBA	ASC_REG,@65
	ADD	A,@CH_A
	JMP	ASCII_RET
ASCII_CH_SLETTER:
	SUBA	ASC_REG,@97
	ADD	A,@CH_A
	JMP	ASCII_RET
ASCII_CH_ERROR:
	MOV	A,@CH_BLANK

ASCII_RET:
	ENI
	RET
