
INITIAL:
	MOV	_FSR,@0X70			; 3.5826MHz
	DISI
	WDTC
	PAGEIO	0
	BANK	0
	
	MOV	_RE,@0X01			; set lcd 1/8 duty 1/4 bias
	MOV	_RE,@0X06			; set lcd display enable

	CIDBANK	0
	CALL	CLR_LCD_RAM
	CIDBANK	1
	CALL	CLR_LCD_RAM
	CIDBANK	2
	CALL	CLR_LCD_RAM
	CIDBANK	3
	CALL	CLR_LCD_RAM
	BANK	0
	CALL	CLR_REG
	BANK	1
	CALL	CLR_REG
	BANK	2
	CALL	CLR_REG
	BANK	3
	CALL	CLR_REG
	BANK	0
	
	IOW	_IOC5,@0X0F
	IOW	_IOC6,@0X00
	IOW	_IOC8,@0X00
	IOW	_IOC9,@0X00
;	
	;IOW	_IOCA,@0XF0			; port7 as normal port, set p5,p6,p9 for lcd
	IOW	_IOCA,@0XFA
	SRAM	_RB,6
	SRAM	_RB,7				; set p8 for lcd
	
	IOW	_IOC7,@0X18
	MOV	_R7,@0XFF			; p7.5 = 1
	
	SRAM	_RE,3				; set /WURING enable
	
	PAGEIO	1
	IOW	_IOCE,@0X0C
	IOW	_IOCB,@0X80			; count1
	IOW	_IOCC,@0XEF			; count2
	PAGEIO	0
	
; ---------- dtmf open -----------
	SRAM	_PPSR,3				; open the PWDN to receive the dtmf data
	CRAM	_RB,4
	CRAM	_RB,5				; tone detection present time 5ms
	
	CRAM	_STATUS,5			; close the tone genarater1
	CRAM	_STATUS,6			; close the tone genarater2

; ---------- fsk open ------------
	SRAM	_FSR,3				; /FSKPWR = 1
	
	IOW	_IOCF,@0XB0			; DTMF,CONT2,CONT1  ENABLE. fsk disable
	MOV	_ISR,@0
	MOV	FSK_FG,@0
	MOV	SYS_FG,@0
	MOV	STAMP_FG,@0
	
	MOV	A,@2
	CONTW

; ---------- INFO INIT ------------
	BANK	1
	MOV	R1_LCD_CONTRAST,@0X03		; LCD对比度3，
	MOV	R1_CODE23,@0X0			; CODE=000
	ANDA	R1_LCD_CONTRAST,@0X0F
	CALL	LCD_CONTRAST_APPLY
	BANK	0
	MOV	LCALL12,@0XFF
	MOV	LCALL34,@0XFF			; 区域码：无
	MOV	LCALL5,@0XFF

; ---------- time init ------------
	CLR	SEC_REG
	CLR	MIN_REG
	CLR	HOUR_REG
	CLR	WEEK_REG
	MOV	DAY_REG,@1
	MOV	MONTH_REG,@1
	MOV	YEAR_REG,@0

	CALL	#BLANK_LCD
	CRAM	SYS_FG,LANGUAGE
	
	CIDBANK	0
	MOV	_RC,@LCD_CTRL
	MOV	_RD,@0X80
	PAGE	#VGA_STAMP
	
	CALL	CLR_STAMP
	CALL	CLR_NUM1
	CALL	CLR_NUM2
	CALL	CLR_STR
	/*
	MOV	A,@STYLE_CENTER			; 居中显示
	CALL	VGA_STR
	MOV	A,@(WD_INITIAL)
	CALL	VGA_STRING
	MOV	A,@CH_END
	CALL	VGA_STR
	*/
	PAGE	#($)
	CALL	#VIEW_STR
	
	SRAM	STAMP_FG,STAMP_SLASH		; 日期之间的斜杠，固定亮。
	SRAM	SYS_FG,STAMP
	SRAM	SYS_FG,SYS_CLOCK
	CRAM	SYS_FG,LOCK_TOPLINE
	
	ENI
	MOV	TMR_DELAY,@250
	CALL	WAIT_FLASH
	
	
	BANK	1
	RET

CLR_LCD_RAM:
	CLR	TEMP0
CLR_LCD_RAM_LOOP:
	MOV	_RC,TEMP0
	CLR	_RD
	INC	TEMP0
	SUBA	TEMP0,@0XFF
	JPNZ	CLR_LCD_RAM_LOOP
	MOV	_RC,TEMP0
	CLR	_RD
	RET

CLR_REG:
	AND	_RSR,@0XC0
	ADD	_RSR,@0X0F
CLR_REG_LOOP:
	INC	_RSR
	CLR	_R0
	ANDA	_RSR,@0X3F
	SUB	A,@0X3F
	JPNZ	CLR_REG_LOOP
	RET

BLANK_LCD:
	MOV	TEMP0,@0
BLANK_LCD_LOOP:
	MOV	A,TEMP0
	IOW	_IOCB
	MOV	A,@0
	IOW	_IOCC
	INC	TEMP0
	SUBA	TEMP0,@0X28
	JPNZ	BLANK_LCD_LOOP1
	MOV	TEMP0,@0X40
BLANK_LCD_LOOP1:
	SUBA	TEMP0,@0X68
	JPNZ	BLANK_LCD_LOOP
	
	RET

/*****************************
LCD对比度
*****************************/
LCD_CONTRAST_APPLY:
	
	AND	A,@0X0F
;	ADD	A,@2				; OTP
	ADD	A,@0XFF				; 仿真
	MOV	TEMP0,A
	CLRC
	RLC	TEMP0
	IOR	_IOCA
	AND	A,@0XF1
	ADD	A,TEMP0
	IOW	_IOCA
	
	RET


/*****************************
等待FLASH初始化
*****************************/
WAIT_FLASH:
	;CALL	#LCD_VIEW
	
	BANK	0
	CIDBANK	1
	
	;MOV	TMR_NAME,@40			; 等待初始化20秒
	MOV	TMR_NAME,@20
WAIT_FLASH_LOOP:
	MOV	A,SER_FLAG
	JPNZ	WAIT_FLASH_OK
	MOV	A,TMR_NAME
	JPNZ	WAIT_FLASH_LOOP
WAIT_FLASH_TIMEOUT:
	PAGE	#VGA_STR
	MOV	A,@(STYLE_CENTER)
	CALL	VGA_STR
	MOV	A,@WD_INITIAL
	CALL	VGA_STRING
	MOV	A,@CH_BLANK
	CALL	VGA_STR
	MOV	A,@CH_T
	CALL	VGA_STR
	MOV	A,@CH_I
	CALL	VGA_STR
	MOV	A,@CH_M
	CALL	VGA_STR
	MOV	A,@CH_E
	CALL	VGA_STR
	MOV	A,@CH_O
	CALL	VGA_STR
	MOV	A,@CH_U
	CALL	VGA_STR
	MOV	A,@CH_T
	CALL	VGA_STR
	MOV	A,@CH_END
	CALL	VGA_STR
	PAGE	#($)
	CALL	#VIEW_STR
	BANK	0
	MOV	TMR_DELAY,@250
	MOV	A,TMR_DELAY
	JPNZ	$-2
	JMP	WAIT_FLASH_RET
WAIT_FLASH_OK:
	CLR	SEC_REG
	MOV	TMR_NAME,@4
WAIT_FLASH_OK_LOOP:
	CALL	#STCP_CHK
	
	PAGE	#(VGA_STR)
	MOV	A,@STYLE_CENTER			; 居中显示
	CALL	VGA_STR
	MOV	A,@(WD_INITIAL)
	CALL	VGA_STRING
	MOV	A,@CH_END
	CALL	VGA_STR
	PAGE	#($)
	
	CALL	#VIEW_STR
	
	BANK	0
	MOV	A,TMR_NAME
	JPNZ	WAIT_FLASH_OK_LOOP
WAIT_FLASH_RET:
	RET

/*
WAIT_FLASH:
	CALL	#LCD_VIEW
	
	CIDBANK	1
	BANK	0
	MOV	TMR_NAME,@4
	JPB	SER_FLAG,7,WAIT_FLASH_OK
	JPB	SER_FLAG,4,WAIT_FLASH_OK
	MOV	_RC,@(TCP_ADDR+0)
	JPB	_RD,7,WAIT_FLASH_OK
	;JPB	SER_FLAG,7,WAIT_FLASH_OK
	
	MOV	A,TMR_DELAY
	JPNZ	WAIT_FLASH
	INC	BANK0_TEMP0
	SUBA	BANK0_TEMP0,@10
	JPZ	WAIT_FLASH_TIMEOUT		; 等待FLASH超时
	CALL	#SEND_DESIRE
	JPNZ	WAIT_FLASH_RET
	MOV	A,@0X88
	CALL	#STORE_SER
	MOV	A,@0X88				; 初始化请求
	CALL	#STORE_SER
	MOV	A,@CH_END
	CALL	#STORE_SER
	CALL	#SER_BUF_CHK
	MOV	TMR_DELAY,@250
	JMP	WAIT_FLASH
WAIT_FLASH_TIMEOUT:
	PAGE	#VGA_STR
	MOV	A,@(STYLE_CENTER)
	CALL	VGA_STR
	MOV	A,@WD_INITIAL
	CALL	VGA_STRING
	MOV	A,@CH_BLANK
	CALL	VGA_STR
	MOV	A,@CH_T
	CALL	VGA_STR
	MOV	A,@CH_I
	CALL	VGA_STR
	MOV	A,@CH_M
	CALL	VGA_STR
	MOV	A,@CH_E
	CALL	VGA_STR
	MOV	A,@CH_O
	CALL	VGA_STR
	MOV	A,@CH_U
	CALL	VGA_STR
	MOV	A,@CH_T
	CALL	VGA_STR
	MOV	A,@CH_END
	CALL	VGA_STR
	PAGE	#($)
	JMP	WAIT_FLASH_RET
WAIT_FLASH_OK:
WAIT_FLASH_OK_LOOP:
	CALL	#STCP_CHK
	;CALL	#DEL_FINISHED
	BANK	0
	MOV	A,TMR_NAME
	JPNZ	WAIT_FLASH_OK_LOOP
WAIT_FLASH_RET:
	RET
*/