.NOLIST
;-------------------------------------------------------------------------------
VOPIDX_EN_Sunday	.EQU	24
VOPIDX_EN_AM		.EQU	31
VOPIDX_EN_PM		.EQU	32
VOPIDX_EN_oh		.EQU	33
VOPIDX_EN_TimeIsNotSet	.EQU	34
;VOPIDX_EN_MemoryIsFull	.EQU	35
VOPIDX_EN_DefOGM1	.EQU	36
;VOPIDX_EN_DefOGM2	.EQU	38
;---------------------------------------
;DE_START		.EQU	40
;VOPIDX_DE_Sunday	.EQU	DE_START+24
;VOPIDX_DE_Uhr		.EQU	DE_START+31	;hour
;VOPIDX_DE_Null		.EQU	DE_START+32	;0
;VOPIDX_DE_und		.EQU	DE_START+33	;and
;VOPIDX_DE_ein		.EQU	DE_START+34	;one
;VOPIDX_DE_SpeischerVoll	.EQU	DE_START+35	;MemoryIsFull
;VOPIDX_DE_BitteTagUnd	.EQU	DE_START+36	;PleaseSetTime
;VOPIDX_DE_DefOGM1	.EQU	DE_START+37
;---------------------------------------
NL_START		.EQU	40
VOPIDX_NL_Sunday	.EQU	NL_START+24
VOPIDX_NL_Uhr		.EQU	NL_START+31	;hour
VOPIDX_NL_Null		.EQU	NL_START+32	;0
VOPIDX_NL_und		.EQU	NL_START+33	;and
VOPIDX_NL_ein		.EQU	NL_START+34	;one
VOPIDX_NL_SpeischerVoll	.EQU	NL_START+35	;MemoryIsFull
VOPIDX_NL_BitteTagUnd	.EQU	NL_START+36	;PleaseSetTime
VOPIDX_NL_DefOGM1	.EQU	NL_START+37
;---------------------------------------
FR_START		.EQU	116
VOPIDX_FR_One		.EQU	FR_START+1	;1
VOPIDX_FR_Sunday	.EQU	FR_START+24
VOPIDX_FR_heure		.EQU	FR_START+31	;hour
VOPIDX_FR_zero		.EQU	FR_START+32	;0
VOPIDX_FR_DefOGM1	.EQU	FR_START+37
VOPIDX_FR_Et		.EQU	FR_START+38	;and

;-------------------------------------------------------------------------------
.END
