.LIST
;//-----------------------------------------------------------------------
MAIN:
	CALL	INITIAL
;//--------------------- STAND-BY ROUTINES -------------------------------
STAND_BY:
        CALL	INT_BIOS		;DAM_BIOS软中断
	CALL	GET_MSG			;GET MESSAGE
	BS	ACZ,STAND_BY
	SAH	MSG
	
	CALL	SYS_MSG
	BS	ACZ,STAND_BY		;系统消息

	CALL	GET_FUNC		;应用定向
	CALA
	
        BS	B1,STAND_BY
;-------------------------------主程序----------------------------------
MAIN_PRO:
	LAC	PRO_VAR
	ANDL	0X0F
	BS	ACZ,MAIN_PRO0
	SBHK	1
	BS	ACZ,MAIN_PRO1
	SBHK	1
	BS	ACZ,MAIN_PRO2
	SBHK	1
	BS	ACZ,MAIN_PRO3
	SBHK	1
	BS	ACZ,MAIN_PRO4
	SBHK	1
	BS	ACZ,MAIN_PRO5
	SBHK	1
	BS	ACZ,MAIN_PRO6
	SBHK	1
	BS	ACZ,MAIN_PRO7
	SBHK	1
	BS	ACZ,MAIN_PRO8
	
	RET
;======================================================消息生成区
MAIN_PRO0:	;空闲状态要考虑的消息:

	LAC	MSG
	XORL	CMSG_INIT		;INITIAL
	BS	ACZ,MAIN_PRO0_INIT
;---
MAIN_PRO0_1:
	LAC	MSG
	XORL	CMSG_KEY1S
	BS	ACZ,MAIN_PRO0_PLAY
;---
MAIN_PRO0_2:
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO0_TIME
;---
MAIN_PRO0_3:
	LAC	MSG
	XORL	CMSG_KEY3S
	BS	ACZ,MAIN_PRO0_PLAY_OGM
MAIN_PRO0_3_1:
	LAC	MSG
	XORL	CMSG_KEY3L
	BS	ACZ,MAIN_PRO0_RECO_OGM
;---
MAIN_PRO0_4:
	LAC	MSG
	XORL	CMSG_KEY4L
	BS	ACZ,MAIN_PRO0_RECO_MSG
;---
MAIN_PRO0_5:
	LAC	MSG
	XORL	CMSG_KEY5L
	BS	ACZ,MAIN_PRO0_ERAS_MSG
;---
MAIN_PRO0_6:
	LAC	MSG
	XORL	CMSG_KEY6S
	BS	ACZ,MAIN_PRO0_ONOFF
;---
MAIN_PRO0_7:
	LAC	MSG
	XORL	CMSG_KEY7L
	BS	ACZ,MAIN_PRO0_MBOX
;---
MAIN_PRO0_9:
	LAC	MSG
	XORL	CMSG_KEY9L
	BS	ACZ,MAIN_PRO0_MENU
;---
MAIN_PRO0_10:
	LAC	MSG
	XORL	CMSG_KEYAS
	BS	ACZ,MAIN_PRO0_VOLA
MAIN_PRO0_10_1:
	LAC	MSG
	XORL	CMSG_KEYAL
	BS	ACZ,MAIN_PRO0_VOLA
;---
MAIN_PRO0_11:
	LAC	MSG
	XORL	CMSG_KEYBS
	BS	ACZ,MAIN_PRO0_VOLS
;---
MAIN_PRO0_13:	
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,MAIN_PRO0_VOIC_END
MAIN_PRO0_14:	
	LAC	MSG
	XORL	CMSG_TESTD		;test
	BS	ACZ,MAIN_PRO0_TEST
	;LAC	MSG
	;XORL	CMSG_TEST		;test
	;BS	ACZ,MAIN_PRO0_TEST

;---
	RET
;-------------------------------;消息处理
MAIN_PRO0_INIT:
	CALL	HOOK_OFF
	CALL	DAA_OFF		;要考虑加入的功能(11.18)
	CALL	INIT_DAM_FUNC
	CALL	MSG_CHK
	
	CALL	TMPNUM_DEL	;删除临时来电号码(如果有)
	CALL	TEL_GC_CHK
	CALL	GC_CHK
	CALL	MSG_CHK
	CALL	LED_STATUS	;有NEW MESSAGES吗?
;---
	CALL	GET_FILEID
	SAH	FILE_ID		;stor vp use_dat()
;---	
	CALL	REC_EEND
	CALL	PLY_EEND
	CALL	REMT_EEND
	
	RET
;-------
MAIN_PRO0_PLAY:	
	LACL	CNO_NMSG
	CALL	STOR_MSG	;LED不要闪烁了(进入放音)
	
	CALL	PLY_EEXE
	
	CALL	INIT_DAM_FUNC
	
	;LACL	0XD000
	;SAH	CONF
	;CALL	DAM_BIOS
	
	;LACL	0XD200
	;SAH	CONF
	;CALL	DAM_BIOS
	
	LACK	1
	SAH	PRO_VAR			;进入播放子功能

	;CALL	MANAGE			;set new flag to new message
	CALL	CLR_FLAG
	CALL	MSG_CHK
	
	;LAC	MSG_ID
	;ANDL	0XFF00
	;SAH	MSG_ID
	
	LAC	MSG_T
	ADHK	1
	;OR	MSG_ID
	SAH	MSG_ID

	BIT	ANN_FG,12
	BS	TB,MAIN_PRO0_PLAY1
	BIT	ANN_FG,14
	BS	TB,MAIN_PRO0_PLAY2

	LACL	0X0080		;1.0s mute
	CALL	STOR_VP
	CALL	BBBEEP		;替换语音BBB
	LACK	0
	SAH	PRO_VAR	
	
	BS	B1,MAIN_PRO0_PLAY_END
;---
MAIN_PRO0_PLAY1:

	LACL	0X005
	CALL	STOR_VP			;替换语音		
	BS	B1,MAIN_PRO0_PLAY_END
;-
MAIN_PRO0_PLAY2:

	LACL	0X0010
	CALL	STOR_VP			;替换语音	
	BS	B1,MAIN_PRO0_PLAY_END	
MAIN_PRO0_PLAY_END:
	CALL	DAA_SPK
	RET				
;-------	
MAIN_PRO0_TIME:
	
	RET
;-------
MAIN_PRO0_PLAY_OGM:
	CALL	PLY_EEXE
	CALL	INIT_DAM_FUNC
	
	LACK	4
	SAH	PRO_VAR			;进入播放OGM子功能
	
	;CALL	OGM_STATUS
	LAC	MSG_N
	CALL	OGM_CHK
	
	LAC	MSG_ID
	ANDL	0X0FF
	ORL	0XFE00
	CALL	STOR_VP
	
	LAC	MSG_N
	CALL	OGM_CHK
	BS	ACZ,MAIN_PRO0_PLAY_OGM1
	
	CALL	INIT_DAM_FUNC
	
	LAC	MSG_N
	CALL	SELECT_OGM
	
	LACL	0X0040		;0.5s mute
	CALL	STOR_VP
	LAC	LANGUAGE
	SFR	4		;OGM vp
	ANDK	0X0F
	ORL	0XFF00
	CALL	STOR_VP
MAIN_PRO0_PLAY_OGM1:		
	CALL	DAA_SPK
	
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	RET
;-------
MAIN_PRO0_RECO_OGM:
	CALL	INIT_DAM_FUNC
	CALL	REC_EEXE
	
	LACL	0X015
	SAH	PRO_VAR

	CALL	LBEEP
	
	CALL	DAA_SPK
	
	BIT	ANN_FG,13	;check memoful?
	BZ	TB,MAIN_PRO0_RECO_OGM1
	
	CALL	INIT_DAM_FUNC
	
	LACK	0
	SAH	PRO_VAR
	
	CALL	BBBEEP		;memory full(BBB)
MAIN_PRO0_RECO_OGM1:	
	RET
MAIN_PRO0_RECO_MSG:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	LBEEP
	CALL	REC_EEXE
	
	LACL	0X013
	SAH	PRO_VAR
	
	BIT	ANN_FG,13	;check memoful?
	BZ	TB,MAIN_PRO0_RECO_MSG1
	
	CALL	INIT_DAM_FUNC
	
	LACK	0
	SAH	PRO_VAR
	CALL	BBBEEP		;memory full(BBB)
MAIN_PRO0_RECO_MSG1:		
	RET
;-------
MAIN_PRO0_ERAS_MSG:
	CALL	MSG_CHK
	LAC	MSG_T
	BS	ACZ,MAIN_PRO0_ERAS_MSG1
	
	LACL	0X6100
	SAH	CONF
	CALL	DAM_BIOS
	
	LACL	0X6080
	SAH	CONF
	CALL	DAM_BIOS
	
	CALL	TELNUMALL_DEL	;删除没有对应message的电话号码

	CALL	DAA_SPK
	CALL	BBEEP
	
	BS	B1,MAIN_PRO0_ERAS_MSG_END
MAIN_PRO0_ERAS_MSG1:	
	
	CALL	BBBEEP
	CALL	DAA_SPK
MAIN_PRO0_ERAS_MSG_END:	
	RET
MAIN_PRO0_ONOFF:

	;CALL	INIT_DAM_FUNC
	;CALL	GC_CHK
	
	;CALL	DAA_OFF
	
	RET
MAIN_PRO0_MBOX:
	RET
MAIN_PRO0_MENU:
	RET
MAIN_PRO0_VOLA:
	
	RET
MAIN_PRO0_VOLS:
	RET
MAIN_PRO0_VOIC_END:
	LACL	CMSG_INIT
	CALL	STOR_MSG
	RET
MAIN_PRO0_TEST:
	CALL	INIT_DAM_FUNC
	CALL	HOOK_ON
	CALL	DAA_LIN_RECORD
	LACL	0X20FF			;beep(initial)
	CALL	STOR_VP

	LACK	0x06
	SAH	PRO_VAR
	
	RET		
;===================================================================	
MAIN_PRO1:	;播放(MSG)状态要考虑的消息:
	LAC	MSG
	XORL	CSEG_PAUSE		;pause
	BS	ACZ,MAIN_PRO1_PLAY_PAUSE
MAIN_PRO1_1:
	LAC	MSG
	XORL	CMSG_KEY5S		;erase
	BS	ACZ,MAIN_PRO1_PLAY_ERASE
MAIN_PRO1_2:
MAIN_PRO1_3:
	LAC	MSG
	XORL	CMSG_KEY6S		;ON/OFF(stop)
	BS	ACZ,MAIN_PRO1_PLAY_STOP
MAIN_PRO1_4:
MAIN_PRO1_5:
	LAC	MSG
	XORL	CMSG_KEYAS		;VOL+
	BS	ACZ,MAIN_PRO1_PLAY_VOLA
MAIN_PRO1_6:
MAIN_PRO1_7:
	LAC	MSG
	XORL	CMSG_KEYBS		;VOL-
	BS	ACZ,MAIN_PRO1_PLAY_VOLS
MAIN_PRO1_8:
MAIN_PRO1_9:
	LAC	MSG
	XORL	CMSG_KEYCS		;FFW
	BS	ACZ,MAIN_PRO1_PLAY_FFW
MAIN_PRO1_10:
MAIN_PRO1_11:
	LAC	MSG
	XORL	CMSG_KEY8S		;REW
	BS	ACZ,MAIN_PRO1_PLAY_REW
MAIN_PRO1_12:
MAIN_PRO1_13:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,MAIN_PRO1_PLAY_OVER
			
	RET
;-------消息处理
MAIN_PRO1_PLAY_PAUSE:
	LAC	CONF
	ANDL	0XF000
	XORL	0X2000
	BZ	ACZ,MAIN_PRO1_PLAY_PAUSE1
	
	LACK	2
	SAH	PRO_VAR
	
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	SRAM	CONF,8
	CALL	DAM_BIOS
	
	RET
MAIN_PRO1_PLAY_PAUSE1:		;若是BEEP,则循环再发
	LACL	CSEG_PAUSE
	CALL	STOR_MSG
	
	RET
MAIN_PRO1_PLAY_ERASE:

	CALL	INIT_DAM_FUNC
	
	CALL	DEL_VPMSG
	
	LAC	FILE_ID
	CALL	GET_USRDAT
	CALL	GET_TELID
	CALL	TELNUM_DEL

	CALL	BEEP
	
	RET
MAIN_PRO1_PLAY_STOP:
	CALL	INIT_DAM_FUNC
	
	CALL	SETOLD_VPMSG
	
	LACL	0X6100
	SAH	CONF
	CALL	DAM_BIOS

	CALL	BBEEP		;替换语音BB
	CALL	DAA_SPK
	
	LACK	0
	SAH	PRO_VAR
	
	RET
MAIN_PRO1_PLAY_VOLA:
	RET
MAIN_PRO1_PLAY_VOLS:
	RET
MAIN_PRO1_PLAY_FFW:
	CALL	INIT_DAM_FUNC
	
	CALL	SETOLD_VPMSG
	
	LACL	CVP_STOP
	CALL	STOR_MSG
	
	RET
;-------

MAIN_PRO1_PLAY_REW:		;从
	CALL	INIT_DAM_FUNC
	
	CALL	SETOLD_VPMSG

	LAC	MSG_ID
	ADH	FILE_LEN
	ANDL	0X0FF
	SBH	MSG_T
	BZ	SGN,MAIN_PRO1_PLAY_REW_1 ;第一个吗?

	LAC	MSG_ID
	ADH	FILE_LEN
	ADHK	1
	SAH	MSG_ID
MAIN_PRO1_PLAY_REW_1:	
	BIT	ANN_FG,12
	BZ	TB,MAIN_PRO1_PLAY_REW_2

	CALL	FFW_MANAGE
	
MAIN_PRO1_PLAY_REW_2:

	CALL	BEEP		;替换语音B	
	
.IF	TEXT_m58	
	CALL	SEND_INIT
.ENDIF
	LAC	MSG_ID
	CALL	GET_RVPLEN
	CALL	GET_VPMSG

	CALL	DAA_SPK
		
	RET
;-------
MAIN_PRO1_PLAY_OVER:
	CALL	INIT_DAM_FUNC

	LAC	MSG_ID
	ANDL	0X0FF
	SBHK	1
	BS	ACZ,MAIN_PRO1_PLAY_OVER_1
	BZ	SGN,MAIN_PRO1_PLAY_OVER1
	
;===
MAIN_PRO1_PLAY_OVER_1:	
	LACL	0X6100
	SAH	CONF
	CALL	DAM_BIOS

	CALL	BBEEP

	CALL	DAA_SPK
	
	LACK	0
	SAH	PRO_VAR
	
	RET
MAIN_PRO1_PLAY_OVER1:

	LAC	MSG_ID			;next message
	SBHK	1
	SAH	MSG_ID
	
	BIT	ANN_FG,12
	BZ	TB,MAIN_PRO1_PLAY_OVER2

	CALL	REW_MANAGE
	BZ	ACZ,MAIN_PRO1_PLAY_OVER_1	;THE LAST ONE	
MAIN_PRO1_PLAY_OVER2:
	CALL	DAA_SPK
	CALL	BEEP
.IF	TEXT_m58	
	CALL	SEND_INIT
.ENDIF
	LAC	MSG_ID
	CALL	GET_VPLEN
	CALL	GET_VPMSG

	RET		
;=================================================================================
MAIN_PRO2:	;暂停(MSG)状态要考虑的消息:
	LAC	MSG
	XORL	CMSG_KEY1S		;PLAY
	BS	ACZ,MAIN_PRO_PLAY_ID
MAIN_PRO2_1:
	LAC	MSG
	XORL	CMSG_KEY6S		;stop
	BS	ACZ,MAIN_PRO1_PLAY_STOP
MAIN_PRO2_2:
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,MAIN_PRO2_TMR
	
	RET
MAIN_PRO2_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	8
	BS	ACZ,MAIN_PRO1_PLAY_STOP
	BZ	SGN,MAIN_PRO1_PLAY_STOP
	
	RET
;-------
MAIN_PRO_PLAY_ID:
	LAC	PRO_VAR
	ANDL	0XFFF0
	ORK	1
	SAH	PRO_VAR
	
	CRAM	CONF,8
	CALL	DAM_BIOS
MAIN_PRO_PLAY_ID_END:
	RET

;=================================================================================
MAIN_PRO3:	;录音(MSG)状态要考虑的消息:
	LAC	PRO_VAR
	SFR	4
	BS	ACZ,MAIN_PRO3_2
MAIN_PRO3_1:	
	
MAIN_PRO3_1_1:	
	LAC	MSG
	XORL	CVP_STOP		;end of the voice prompt and begin to record
	BS	ACZ,MAIN_PRO3_RECMEMO
MAIN_PRO3_1_2:	
	LAC	MSG
	XORL	CMSG_KEY6S		;press STOP key when playing voice prompt
	BS	ACZ,MAIN_PRO3_REC_END1
	
	RET
;---	
MAIN_PRO3_2:	
	LAC	MSG
	XORL	CMSG_KEY6S		;ON/OFF
	BS	ACZ,MAIN_PRO3_REC_END
MAIN_PRO3_2_1:
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,MAIN_PRO3_REC_TMR
MAIN_PRO3_2_2:
	LAC	MSG
	XORL	CREC_FULL		;REC_FULL
	BS	ACZ,MAIN_PRO3_REC_FUL
MAIN_PRO3_2_3:
	LAC	MSG
	XORL	CVP_STOP		;RECFULL BEEP VP END
	BS	ACZ,MAIN_PRO3_RECFUL_VPEND
	
	RET
;-------处理消息
MAIN_PRO3_REC_END1:
	LACK	0
	SAH	PRO_VAR
	
	LACL	CMSG_INIT
	CALL	STOR_MSG
	RET

MAIN_PRO3_RECMEMO:

	CALL	MSG_CHK
;????????????????????????????????????????????????	
	;CALL	TELNUM_WRITE	;????????????????
	;CALL	GET_FILEID	;????????????????
	;SAH	BUF1		;????????????????
	;CALL	GET_TELT	;????????????????
	;ORL	0XE700		;????????????????
	;SAH	CONF		;????????????????
	;CALL	DAM_BIOS	;????????????????
;????????????????????????????????????????????????
	;CALL	GET_FILEID
	LAC	FILE_ID
	CALL	SET_USRDAT
	
MAIN_PRO3_REC:		;for MEMO/OGM record
MAIN_PRO5_REC:
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	CALL	DAA_RECORD
	
	CALL	REC_START
	
	RET
MAIN_PRO3_REC_END:
	LAC	PRO_VAR1
	SBHK	3
	BZ	SGN,MAIN_PRO3_REC_END_2	;要求同时满足录音时间t>1s&&t>VPLEN才能保留
;MAIN_PRO3_REC_END_1:
	SRAM	CONF,11
	CALL	DAM_BIOS	
	CALL	INIT_DAM_FUNC

	LACK	0
	SAH	PRO_VAR

	CALL	BBEEP
	
	CALL	DAA_SPK	
	
	RET
MAIN_PRO3_REC_END_2:
	LAC	CONF
	ANDL	0XFFC0		;不准掐尾
	SAH	CONF
	CALL	INIT_DAM_FUNC
	
	CALL	GET_TOTALMSG
	CALL	GET_MSGMSG
	CALL	WRITE_MEMOMSG
	
	CALL	GET_TOTALMSG
	CALL	GET_USRDAT
	CALL	COL_ICMTEL

	CALL	TMPNUM_DEL

	LACL	0X9150			;disable setting old mark
	SAH	CONF
	CALL	DAM_BIOS

	CALL	BEEP
	
	CALL	MSG_CHK
	
	LACK	8
	SAH	PRO_VAR
	CALL	PLY_EEXE
	
	LAC	MSG_T
	CALL	GET_VPLEN
	CALL	GET_VPMSG
	CALL	DAA_SPK	
	
	RET
MAIN_PRO3_REC_TMR:
	LAC	CONF
	ANDL	0XFFC0
	SAH	CONF		;防止掐尾
	
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	
	RET
;-------
MAIN_PRO3_REC_FUL:		;for memo record
	LACL	0X1040		;不准掐尾
	SAH	CONF
	CALL	INIT_DAM_FUNC	;stop recording
	
	CALL	GC_CHK
	CALL	MSG_CHK
	BIT	ANN_FG,13
	BZ	TB,MAIN_PRO3_REC_FUL1

	CALL	BBBEEP
	CALL	DAA_SPK	
	CALL	HOOK_ON
	
	LACK	0
	SAH	PRO_VAR
		
	RET
MAIN_PRO3_REC_FUL1:
	CALL	REC_START
	
	RET
MAIN_PRO3_RECFUL_VPEND:
	CALL	HOOK_OFF
	CALL	DAA_OFF
	CALL	REC_EEND
	
	RET
	
;================================================================================
MAIN_PRO4:	;播放(OGM)状态要考虑的消息:
	LAC	MSG
	XORL	CMSG_KEY5S		;ERASE
	BS	ACZ,MAIN_PRO4_EXE1
MAIN_PRO4_1:
	LAC	MSG
	XORL	CMSG_KEY6S		;ON/OFF(stop)
	BS	ACZ,MAIN_PRO4_EXE2
MAIN_PRO4_2:
	LAC	MSG
	XORL	CVP_STOP		;play end
	BS	ACZ,MAIN_PRO4_ENDPLY
MAIN_PRO4_3:
	LAC	MSG
	XORL	CMSG_TMR		;play end
	BS	ACZ,MAIN_PRO4_TMR
	RET
;-------响应按键,消息转换
MAIN_PRO4_EXE1:
	LAC	MSG_ID
	ANDL	0X0FF
	ORL	0X2080
	SAH	CONF
	CALL	DAM_BIOS
	
	LACL	0X6100
	SAH	CONF
	CALL	DAM_BIOS
	
	CALL	INIT_DAM_FUNC
	
	LACK	0
	SAH	PRO_VAR

	CALL	BBEEP		;替换语音BB
	
	RET
MAIN_PRO4_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	
	RET
MAIN_PRO4_EXE2:
	;LAC	PRO_VAR1
	;SBHK	2
	;BZ	SGN,MAIN_PRO4_ENDPLY	;播放时间小于2秒就不响应停止命令
	;CALL	PLY_EEXE
	;RET
MAIN_PRO4_ENDPLY:
	CALL	INIT_DAM_FUNC
	
	LACK	0
	SAH	PRO_VAR
	CALL	BBEEP		;加语音BB

	RET
;================================================================================
MAIN_PRO5:	;录音(OGM)状态要考虑的消息:
	LAC	PRO_VAR
	SFR	4
	BS	ACZ,MAIN_PRO5_4
	
	LAC	MSG
	;XORL	CMSG_KEY3S		;released OGM key when playing voice prompt
	XORL	CMSG_KEY6S
	BS	ACZ,MAIN_PRO3_REC_END1
MAIN_PRO5_1:	
	LAC	MSG
	XORL	CVP_STOP		;end of the voice prompt and begin to record
	BS	ACZ,MAIN_PRO5_2
	RET
MAIN_PRO5_2:
	;CALL	OGM_STATUS
	LAC	MSG_N
	CALL	OGM_CHK
;-------delete the old OGM----------------	
	LAC	MSG_ID
	ANDL	0X0FF
	ORL	0X2080
	SAH	CONF
	CALL	DAM_BIOS
	
	LAC	CONF
	ANDL	0X007F
	ORL	0X6100
	SAH	CONF
	CALL	DAM_BIOS
	
    	LAC	MSG_N
    	ORL	0X7500
    	SAH	CONF
    	CALL	DAM_BIOS		;set user index data0"OGM_ID"
	BS	B1,MAIN_PRO5_REC
;---	
MAIN_PRO5_4:	
	LAC	MSG
	XORL	CMSG_KEY6S		;ON/OFF
	BS	ACZ,MAIN_PRO5_5
MAIN_PRO5_4_1:
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,MAIN_PRO5_6	
MAIN_PRO5_4_2:
	LAC	MSG
	XORL	CREC_FULL		;REC_FULL
	BS	ACZ,MAIN_PRO5_REC_FUL
	
	RET
MAIN_PRO5_5:
	
	LAC	PRO_VAR1
	SBHK	3
	BS	ACZ,MAIN_PRO5_5_1
	BZ	SGN,MAIN_PRO5_5_1
	SRAM	CONF,11
	CALL	DAM_BIOS
MAIN_PRO5_5_1:	
	LAC	CONF
	ANDL	0XF000			;不准掐尾
	SAH	CONF
	CALL	INIT_DAM_FUNC
	
	LACK	0
	SAH	PRO_VAR
	
	LACL	CMSG_KEY3S		;停止录音(OGM)相当于播放(OGM)
	CALL	STOR_MSG
		
	RET
MAIN_PRO5_6:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	120
	BS	ACZ,MAIN_PRO5_5
	BZ	SGN,MAIN_PRO5_5
	
	RET
MAIN_PRO5_REC_FUL:		;for OGM record
	CALL	CLR_TIMER
	
	LACL	0X1000		;不准掐尾
	SAH	CONF
	CALL	INIT_DAM_FUNC		;stop recording
	
	CALL	BBEEP		;录音满语音BB
	CALL	DAA_SPK	
	CALL	HOOK_ON
	
	LACK	0
	SAH	PRO_VAR
	
	RET
;-------------------------------------------------------------------------------
MAIN_PRO6:	;???TestMode
	LAC	MSG
	XORL	CVP_STOP		;play end
	BS	ACZ,MAIN_PRO6_VPSTOP
	
	LAC	MSG
	XORL	CMSG_TEST
	BS	ACZ,MAIN_PRO6_ETEST

	RET
MAIN_PRO6_VPSTOP:
	LACL	0X20FF
	CALL	STOR_VP
	
	RET
MAIN_PRO6_ETEST:
	CALL	INIT_DAM_FUNC
	LACL	CMSG_INIT
	CALL	STOR_MSG
	
	LACK	0
	SAH	PRO_VAR

	RET
;-------------------------------------------------------------------------------
MAIN_PRO7:	;音量设置状态要考虑的消息:
	
	RET
;---------------
MAIN_PRO8:	;回放MEMO状态要考虑的消息:
	LAC	MSG
	XORL	CMSG_KEY6S		;ON/OFF(stop)
	BS	ACZ,MAIN_PRO8_2_1
MAIN_PRO8_1:
	LAC	MSG
	XORL	CMSG_KEY5S		;eraser
	BS	ACZ,MAIN_PRO8_1_1
MAIN_PRO8_2:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,MAIN_PRO8_2_1
			
	RET
;---
MAIN_PRO8_1_1:
	CALL	INIT_DAM_FUNC
	
	LAC	MSG_T
	ORL	0X6000
	SAH	CONF
	CALL	DAM_BIOS
	
	LACL	0X9050
	SAH	CONF
	CALL	DAM_BIOS
	
	LACK	0
	SAH	PRO_VAR
	CALL	BBEEP	;替换语音BB	
	
	RET
;---
MAIN_PRO8_2_1:
	CALL	INIT_DAM_FUNC
	
	LACL	0X9050
	SAH	CONF
	CALL	DAM_BIOS
	
	LACK	0
	SAH	PRO_VAR
	CALL	BBEEP	;替换语音BB
	
	RET
;-----------

;=========================================================================

	
.END

