.NOLIST
.INCLUDE	include/REG_D22.inc
.INCLUDE	include/MD22U.inc
.INCLUDE	include/CONST.inc

.GLOBAL	LOCAL_PROTEL
;-------------------------------------------------------------------------------
.EXTERN	GetOneConst

.EXTERN	INIT_DAM_FUNC

.EXTERN	BCVOX_INIT
.EXTERN	BBBEEP
.EXTERN	BBEEP
.EXTERN	BEEP

.EXTERN	CLR_FUNC
.EXTERN	CLR_TIMER

.EXTERN	DAA_SPK
.EXTERN	DAA_REC
.EXTERN	DAA_OFF
.EXTERN	DAM_BIOSFUNC
.EXTERN	DAM_BIOSFUNC1
.EXTERN	DELAY
.EXTERN	DGT_TAB
.EXTERN	DGT_HEX
.EXTERN	DspStop
.EXTERN	HEX_DGT

.EXTERN	GC_CHK
.EXTERN	TEL_GC_CHK
.EXTERN	GETBYTE_DAT

.EXTERN	LBEEP

.EXTERN	LINE_START
.EXTERN	LOCAL_PRO

.EXTERN	OGM_SELECT

.EXTERN	PUSH_FUNC

;.EXTERN	REAL_DEL
.EXTERN	REC_START

.EXTERN	SET_PLYPSA
.EXTERN	SET_TIMER

.EXTERN	SEND_DAT
;.EXTERN	SEND_MFULL
.EXTERN	SEND_MSGNUM
;.EXTERN	SEND_RECSTART
.EXTERN	SEND_TEL
.EXTERN	SET_DECLTEL
.EXTERN	STOR_MSG
.EXTERN	STOR_VP
.EXTERN	STORBYTE_DAT

.EXTERN	TELNUM_WRITE
.EXTERN	TELNUM_READ

.EXTERN	VPMSG_CHK
.EXTERN	VPMSG_DEL

;---
.LIST
;-------------------------------------------------------------------------------
.ORG	ADDR_SECOND
;-------------------------------------------------------------------------------
LOCAL_PROTEL:
;---find
	LAC	MSG
	XORL	CFIND_ANSWCID
	BS	ACZ,LOCAL_PROTEL_FINDANSWCID
	LAC	MSG
	XORL	CFIND_MISSCID
	BS	ACZ,LOCAL_PROTEL_FINDMISSCID
	LAC	MSG
	XORL	CFIND_DTEL
	BS	ACZ,LOCAL_PROTEL_FINDDTEL
	LAC	MSG
	XORL	CFIND_PBOOK
	BS	ACZ,LOCAL_PROTEL_FINDBOOK
	LAC	MSG
	XORL	CFIND_NUM
	BS	ACZ,LOCAL_PROTEL_FINDNUM
;---delete
	LAC	MSG
	XORL	CDEL_MISSCID
	BS	ACZ,LOCAL_PROTEL_DELMISSCID
	LAC	MSG
	XORL	CDEL_ANSWCID
	BS	ACZ,LOCAL_PROTEL_DELANSWCID
	LAC	MSG
	XORL	CDEL_DTEL
	BS	ACZ,LOCAL_PROTEL_DELDTEL
	LAC	MSG
	XORL	CDEL_PBOOK
	BS	ACZ,LOCAL_PROTEL_DELBOOK
;---Save
	LAC	MSG
	XORL	CSAVE_PBOOK
	BS	ACZ,LOCAL_PROTEL_SAVEBOOK
	LAC	MSG
	XORL	CSAVE_DTEL
	BS	ACZ,LOCAL_PROTEL_SAVEDTEL
;---Other
	LAC	MSG
	XORL	CDAM_UPDATE
	BS	ACZ,LOCAL_PROTEL_DAMUPDATE
	LAC	MSG
	XORL	CMSG_FMAT
	BS	ACZ,LOCAL_PROTEL_FMAT
;---Nother to do with flash
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROTEL_TMR
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROTEL_VPSTOP
	LAC	MSG
	XORL	CMSG_STOP
	BS	ACZ,LOCAL_PROTEL_STOP
;-------
;为了避免频繁的搬运FLASH里的程序模块，只有在此功能区无响应的
;消息出现时才取出此功能区,再在idle状态下响应该功能。
	LAC	MSG
	CALL	STOR_MSG	;idle 状态下响应的功能

	LACK	0
	SAH	PRO_VAR

	RET
;---------------------------------------
LOCAL_PROTEL_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	
	RET
;---------------------------------------
LOCAL_PROTEL_VPSTOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	CALL	LINE_START

	RET
LOCAL_PROTEL_STOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBEEP
	
	LACK	0
	SAH	PRO_VAR

	RET
;---------------------------------------
LOCAL_PROTEL_FINDANSWCID:
	CALL	INIT_DAM_FUNC
	
	LACK	CGROUP_ANSWCID
	CALL	SET_TELGROUP
	
	LAC	OGM_ID
	BS	ACZ,LOCAL_PROTEL_FINDANSWCID_END
	BS	SGN,LOCAL_PROTEL_FINDANSWCID_END
	
	CALL	GET_TELT
	ADHK	1
	SBH	OGM_ID
	SAH	MSG_ID		;查找时将倒序进行
	BS	ACZ,LOCAL_PROTEL_FINDANSWCID_END
	BS	SGN,LOCAL_PROTEL_FINDANSWCID_END

;---Read TEL with specified TEL-ID
	LACL	CidData
	SAH	ADDR_D
	LACK	0
	SAH	OFFSET_D
	
	LAC	MSG_ID
	CALL	TELNUM_READ
;--Ignore New flag 
	LACL	CidData
	SAH	ADDR_D
	LACK	57
	SAH	OFFSET_D
	LACK	0
	CALL	STORBYTE_DAT
;---!!!!!将号码返回送给MCU
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;---total
	CALL	GET_TELT
	CALL	SEND_ANSWCID
	
	LACK	5
	CALL	DELAY	
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;---
	LACL	CidData
	SAH	ADDR_S
	LACK	0
	SAH	OFFSET_S
	LACK	58
	SAH	COUNT

	CALL	SEND_TEL
	LACK	0X04	;tell MCU:MCU searched TEL-number send ok
	CALL	SEND_TELOK
;---
LOCAL_PROTEL_FINDANSWCID_END:
	CALL	LINE_START
	
	RET
;---------------------------------------
LOCAL_PROTEL_FINDMISSCID:		;find CID with specific TEL-ID
	CALL	INIT_DAM_FUNC
	
	LACK	CGROUP_MISSCID
	CALL	SET_TELGROUP
	
	LAC	OGM_ID
	BS	ACZ,LOCAL_PROTEL_FINDMISSCID_END
	BS	SGN,LOCAL_PROTEL_FINDMISSCID_END
	
	CALL	GET_TELT
	ADHK	1
	SBH	OGM_ID
	SAH	MSG_ID		;查找时将倒序进行
	BS	ACZ,LOCAL_PROTEL_FINDMISSCID_END
	BS	SGN,LOCAL_PROTEL_FINDMISSCID_END
;---Read TEL with specified TEL-ID
	LACL	CidData
	SAH	ADDR_D
	LACK	0
	SAH	OFFSET_D
	
	LAC	MSG_ID
	CALL	TELNUM_READ
;--Read New flag 
	LACL	CidData
	SAH	ADDR_D
	LACK	57
	SAH	OFFSET_D

	LAC	MSG_ID
	CALL	GET_TELUSRID1
	CALL	STORBYTE_DAT
;---Set New flag(0)
	LAC	MSG_ID		;Set index-1 = 0(new flag)
	;ORL	0X0000
	CALL	SET_TELUSRID1
;---!!!!!将号码返回送给MCU
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;---total
	CALL	GET_TELT
	CALL	SEND_MISSCID
;---new 
	CALL	GET_TELN
	CALL	SEND_NEWCID
	
	LACK	5
	CALL	DELAY	
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;---
	LACL	CidData
	SAH	ADDR_S
	LACK	0
	SAH	OFFSET_S
	LACK	58
	SAH	COUNT

	CALL	SEND_TEL
	LACK	0X04	;tell MCU:MCU searched TEL-number send ok
	CALL	SEND_TELOK
;---
LOCAL_PROTEL_FINDMISSCID_END:
	CALL	LINE_START
	
	RET
;---------------------------------------
LOCAL_PROTEL_FINDDTEL:		;find dial-TEL with specific TEL-ID
	CALL	INIT_DAM_FUNC
	
	LACK	CGROUP_DIAL
	CALL	SET_TELGROUP
	
	LAC	OGM_ID
	BS	ACZ,LOCAL_PROTEL_FINDDTEL_END	;非法序号
	BS	SGN,LOCAL_PROTEL_FINDDTEL_END	;非法序号
.if	1	
	CALL	GET_TELT
	ADHK	1
	SBH	OGM_ID
	SAH	MSG_ID		;查找时将倒序进行
.else
	LAC	OGM_ID
	SAH	MSG_ID
.endif	
	LAC	MSG_ID
	BS	ACZ,LOCAL_PROTEL_FINDDTEL_END	;非法序号
	BS	SGN,LOCAL_PROTEL_FINDDTEL_END	;非法序号
;---Read TEL with specified TEL-ID
	LACL	CidData
	SAH	ADDR_D
	LACK	0
	SAH	OFFSET_D
		
	LAC	MSG_ID
	CALL	TELNUM_READ
;---!!!!!将号码返回送给MCU
	LACL	CidData
	SAH	ADDR_S
	LACK	0
	SAH	OFFSET_S
	LACK	58
	SAH	COUNT

	CALL	SEND_TEL
	LACK	0X04	;tell MCU:MCU searched TEL-number send ok
	CALL	SEND_TELOK
;---
LOCAL_PROTEL_FINDDTEL_END:
	CALL	LINE_START
	
	RET

;---------------------------------------
LOCAL_PROTEL_FINDBOOK:		;find phonebook with specific TEL-ID
	CALL	INIT_DAM_FUNC

	LACK	CGROUP_PBOOK
	CALL	SET_TELGROUP
	
	CALL	GET_TELT
	SBH	OGM_ID
	BS	SGN,LOCAL_PROTEL_FINDBOOK_END	;check if vaild TEL-ID(the number of total TEL must greater than TEL-ID)
;---读出指定的条目,并放到指定的位置
	LACL	CidData
	SAH	ADDR_D
	LACK	0
	SAH	OFFSET_D
			
	LAC	OGM_ID
	SAH	MSG_ID
	CALL	TELNUM_READ
;---!!!!!将号码返回送给MCU
	LACL	CidData
	SAH	ADDR_S
	LACK	0
	SAH	OFFSET_S
	LACK	58
	SAH	COUNT

	CALL	SEND_TEL
	LACK	0X04		;tell MCU:MCU searched TEL-number send ok
	CALL	SEND_TELOK
;---
LOCAL_PROTEL_FINDBOOK_END:
	CALL	LINE_START
;---
	RET

;-----------------------------------------------------------
LOCAL_PROTEL_DELANSWCID:
	CALL	INIT_DAM_FUNC
;!!!
	LACK	1		;Tell MCU:DSP busy
	CALL	SEND_DSPSTAT
;!!!
	LACK	CGROUP_ANSWCID
	CALL	SET_TELGROUP
	
	LAC	OGM_ID
	BS	ACZ,LOCAL_PROTEL_DELALLANSWCID
	
	CALL	GET_TELT
	ADHK	1
	SBH	OGM_ID
	SAH	MSG_ID		;删除时将倒序进行
	CALL	DEL_ONETEL
LOCAL_PROTEL_DELANSWCID_END:
	CALL	TEL_GC_CHK
;!!!!!!!!!!!!!!!
;!!!
	LACK	0		;Tell MCU:DSP idle
	CALL	SEND_DSPSTAT
;!!!
;---total Answered cid
	LACK	CGROUP_ANSWCID
	CALL	SET_TELGROUP
	CALL	GET_TELT
	CALL	SEND_ANSWCID
;!!!!!!!!!!!!!!!
	CALL	LINE_START

	RET
LOCAL_PROTEL_DELALLANSWCID:
	CALL	GET_TELT
	BS	ACZ,LOCAL_PROTEL_DELANSWCID_END
	LACL	0XE501
	CALL	DAM_BIOSFUNC
	
	BS	B1,LOCAL_PROTEL_DELALLANSWCID	
;-----------------------------------------------------------
LOCAL_PROTEL_DELMISSCID:		;delete CID with specific TEL-I
	CALL	INIT_DAM_FUNC
;!!!
	LACK	1		;Tell MCU:DSP busy
	CALL	SEND_DSPSTAT
;!!!
	LACK	CGROUP_MISSCID
	CALL	SET_TELGROUP
	
	LAC	OGM_ID
	BS	ACZ,LOCAL_PROTEL_DELALLMISSCID
	
	CALL	GET_TELT
	ADHK	1
	SBH	OGM_ID
	SAH	MSG_ID		;删除时将倒序进行
	CALL	DEL_ONETEL
LOCAL_PROTEL_DELMISSCID_END:
	CALL	TEL_GC_CHK
;!!!!!!!!!!!!!!!
;!!!
	LACK	0		;Tell MCU:DSP idle
	CALL	SEND_DSPSTAT
;!!!
;---total cid
	LACK	CGROUP_MISSCID
	CALL	SET_TELGROUP
	CALL	GET_TELT
	CALL	SEND_MISSCID
;---new cid
	CALL	GET_TELN
	CALL	SEND_NEWCID
;!!!!!!!!!!!!!!!
	CALL	LINE_START

	RET
LOCAL_PROTEL_DELALLMISSCID:
	CALL	GET_TELT
	BS	ACZ,LOCAL_PROTEL_DELMISSCID_END
	LACL	0XE501
	CALL	DAM_BIOSFUNC
	
	BS	B1,LOCAL_PROTEL_DELALLMISSCID
;-----------------------------------------------------------
LOCAL_PROTEL_DELDTEL:		;delete dialed-TEL with specific TEL-ID
	CALL	INIT_DAM_FUNC
		
	LACK	CGROUP_DIAL
	CALL	SET_TELGROUP

	LAC	OGM_ID
	BS	ACZ,LOCAL_PROTEL_DELALLDTEL
	BS	SGN,LOCAL_PROTEL_DELALLDTEL
.if	1	
	CALL	GET_TELT
	ADHK	1
	SBH	OGM_ID
	SAH	MSG_ID		;删除时将倒序进行
.else
	LAC	OGM_ID
	SAH	MSG_ID
.endif	
	LAC	MSG_ID
	BS	ACZ,LOCAL_PROTEL_DELALLDTEL
	BS	SGN,LOCAL_PROTEL_DELALLDTEL

	LAC	MSG_ID	
	CALL	DEL_ONETEL
	
LOCAL_PROTEL_DELDTEL_END:
	CALL	TEL_GC_CHK
	CALL	GET_TELT
	CALL	SEND_DIALCID
	CALL	LINE_START
	
	RET
LOCAL_PROTEL_DELALLDTEL:
	CALL	GET_TELT
	BS	ACZ,LOCAL_PROTEL_DELDTEL_END
	LACL	0XE501
	CALL	DAM_BIOSFUNC
	BS	B1,LOCAL_PROTEL_DELALLDTEL
;-----------------------------------------------------------
LOCAL_PROTEL_DELBOOK:		;delete phonebook with specific TEL-ID
	CALL	INIT_DAM_FUNC
;!!!
	LACK	1		;Tell MCU:DSP busy
	CALL	SEND_DSPSTAT
;!!!
	LACK	CGROUP_PBOOK
	CALL	SET_TELGROUP

	LAC	OGM_ID
	BS	ACZ,LOCAL_PROTEL_DELALLBOOK
	CALL	DEL_ONETEL
	CALL	TEL_GC_CHK
LOCAL_PROTEL_DELBOOK_END:
;!!!
	LACK	0		;Tell MCU:DSP idle
	CALL	SEND_DSPSTAT
;!!!
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	GET_TELT
	CALL	SEND_PBOOK
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	LINE_START

	RET
LOCAL_PROTEL_DELALLBOOK:	;Del all phonebook
	CALL	GET_TELT
	BS	ACZ,LOCAL_PROTEL_DELBOOK_END
	LACL	0XE501
	CALL	DAM_BIOSFUNC
	CALL	TEL_GC_CHK
	
	BS	B1,LOCAL_PROTEL_DELALLBOOK
;-----------------------------------------------------------
LOCAL_PROTEL_FINDNUM:		;find phonebook-TEL with specific TEL-NUM
	CALL	INIT_DAM_FUNC
	
	LACK	CGROUP_PBOOK
	CALL	SET_TELGROUP

	CALL	COMP_ALLTELNUM			;从电话本中找到有相同号码的条目
	BS	ACZ,LOCAL_PROTEL_FINDNUM_END	;电话本里没有找到相同号码的条目,直接开始比较CID
	SAH	SYSTMP1
;---读出比较得到的条目,将收到的CID覆盖
	LACL	CidData
	SAH	ADDR_D
	LACK	0
	SAH	OFFSET_D
	LAC	SYSTMP1
	CALL	TELNUM_READ
LOCAL_PROTEL_FINDNUM_END:	;---!!!!!将号码返回送给MCU

	LACL	CidData
	SAH	ADDR_S
	LACK	0
	SAH	OFFSET_S
	LACK	58
	SAH	COUNT
	CALL	SEND_TEL
	LACK	0X04	;tell MCU:MCU searched TEL-number send ok
	CALL	SEND_TELOK
	
	CALL	LINE_START

	RET
;-----------------------------------------------------------
LOCAL_PROTEL_SAVEBOOK:		;save phonebook-TEL into flash
	CALL	INIT_DAM_FUNC
	
	LAC	OGM_ID
	BS	ACZ,LOCAL_PROTEL_SAVEBOOK_0
	SBHK	1
	BS	ACZ,LOCAL_PROTEL_SAVETEL_M1
	SBHK	1
	BS	ACZ,LOCAL_PROTEL_SAVETEL_M2
	SBHK	1
	BS	ACZ,LOCAL_PROTEL_SAVETEL_M3
	
	RET
LOCAL_PROTEL_SAVEBOOK_0:
	LACK	CGROUP_PBOOK
	CALL	SET_TELGROUP

	LACL	CidData
	SAH	ADDR_S
	CALL	COMP_ALLTELNUM			;从电话本中找到有相同号码的条目
	BS	ACZ,LOCAL_PROTEL_SAVEBOOK_0_1	;电话本里没有找到相同号码的条目,直接开始比较CID
	SAH	SYSTMP1
	CALL	DEL_ONETEL	;删除找到的号码
	CALL	TEL_GC_CHK
LOCAL_PROTEL_SAVEBOOK_WRITE:
;---------------------------------------
	LACL	CidData
	SAH	ADDR_S
	LACK	0
	SAH	OFFSET_S
	LACK	57
	SAH	COUNT

	CALL	TELNUM_WRITE
	CALL	DAT_WRITE_STOP
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	GET_TELT
	CALL	SEND_PBOOK
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	LINE_START

	RET
LOCAL_PROTEL_SAVEBOOK_0_1:
	CALL	GET_TELT
	SBHK	CMAX_PBOOK	;The MAX. number of Phone-book
	BS	SGN,LOCAL_PROTEL_SAVEBOOK_EXE
;---CMAX_PBOOK TEL exist,delete oldest one
	LACK	1
	CALL	DEL_ONETEL
	CALL	TEL_GC_CHK
LOCAL_PROTEL_SAVEBOOK_EXE:

	BS	B1,LOCAL_PROTEL_SAVEBOOK_WRITE
;---------------------------------------
LOCAL_PROTEL_SAVETEL_M1:
	LACK	CGROUP_M1
	CALL	SET_TELGROUP
	BS	B1,LOCAL_PROTEL_DELOLD
LOCAL_PROTEL_SAVETEL_M2:
	LACK	CGROUP_M2
	CALL	SET_TELGROUP
	BS	B1,LOCAL_PROTEL_DELOLD
LOCAL_PROTEL_SAVETEL_M3:
	LACK	CGROUP_M3
	CALL	SET_TELGROUP
	;BS	B1,LOCAL_PROTEL_DELOLD
LOCAL_PROTEL_DELOLD:
;---Delete old first
	CALL	GET_TELT
	SBHK	1
	BS	SGN,LOCAL_PROTEL_SAVETEL	;All old TEL deleted
;---more than 1	
	LACL	0XE501		;delete old one,Make sure only one TEL exist
	CALL	DAM_BIOSFUNC
	CALL	TEL_GC_CHK
	BS	B1,LOCAL_PROTEL_DELOLD
LOCAL_PROTEL_SAVETEL:	
;---Save new TEL
	LACL	CidData
	SAH	ADDR_S
	LACK	0
	SAH	OFFSET_S
	LACK	57
	SAH	COUNT
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	TELNUM_WRITE
	CALL	DAT_WRITE_STOP
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	LAC	OGM_ID		;
	CALL	SET_TELUSRID1
	
	CALL	LINE_START
		
	RET
;-----------------------------------------------------------
LOCAL_PROTEL_SAVEDTEL:		;save dialed-TEL into flash
	CALL	INIT_DAM_FUNC
	LACK	CGROUP_DIAL
	CALL	SET_TELGROUP
	
	CALL	GET_TELT
	SBHK	CMAX_DIALCID	;The MAX. number off miss-CID
	BS	SGN,LOCAL_PROTEL_SAVEDTEL_EXE
;---CMAX_DIALCID TEL exist,delete oldest one
	LACK	1
	CALL	DEL_ONETEL
	CALL	TEL_GC_CHK
LOCAL_PROTEL_SAVEDTEL_EXE:
;---------------------------------------
	LACL	CidData
	SAH	ADDR_S
	LACK	0
	SAH	OFFSET_S
	LACK	58
	SAH	COUNT

	CALL	TELNUM_WRITE
	CALL	DAT_WRITE_STOP
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!		
	CALL	GET_TELT
	CALL	SEND_DIALCID
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	LINE_START
	
	RET
;---------------------------------------
LOCAL_PROTEL_DAMUPDATE:		;Write new data into flash
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACK	CGROUP_DATT
	CALL	SET_TELGROUP

;!!!
	LACK	1		;Tell MCU:DSP busy
	CALL	SEND_DSPSTAT
;!!!
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
.if	1
LOCAL_PROTEL_DAMUPDATE_1:
	CALL	GET_TELT
	SBHK	1
	BS	SGN,LOCAL_PROTEL_DAMUPDATE_END
;---2 or more ATT,then delete old one
	LACL	0XE501
	CALL	DAM_BIOSFUNC	;删除找到的号码

	;BS	B1,LOCAL_PROTEL_DAMUPDATE_1
LOCAL_PROTEL_DAMUPDATE_END:
	CALL	TEL_GC_CHK
	CALL	DAM_ATT_WRITE
	CALL	DAT_WRITE_STOP
.endif
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;!!!
	LACK	0		;Tell MCU:DSP idle
	CALL	SEND_DSPSTAT
;!!!	

	LACK	0
	SAH	PRO_VAR
	
	CALL	INIT_DAM_FUNC

	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	CALL	LINE_START

	RET
;---------------------------------------
LOCAL_PROTEL_FMAT:
;!!!
	LACK	1		;Tell MCU:DSP busy
	CALL	SEND_DSPSTAT
;!!!
	
	CALL	INIT_DAM_FUNC

	LACL    CMODE9|1
	CALL    DAM_BIOSFUNC
	CALL	TEL_GC_CHK	;Declare TEL-message Number in FLASH
	
	CALL	DAA_SPK
	CALL	LBEEP
;---------------------------------------
	LACL	CPASSWORD
	SAH	PASSWORD
;-
	LACL	CLOCACODE
	SAH	LOCACODE
;-
	LACL	CDAM_ATT
	SAH	DAM_ATT
;-	
	LACL	CDAM_ATT0
	SAH	DAM_ATT0
;-
	LACL	CDAM_ATT1
	SAH	DAM_ATT1
;---------------------------------------
	LACK	CGROUP_DATT
	CALL	SET_TELGROUP
	CALL	DAM_ATT_WRITE
	CALL	DAT_WRITE_STOP

;!!!
	LACK	0		;Tell MCU:DSP idle
	CALL	SEND_DSPSTAT
;!!!		
	LACK	0
	SAH	PRO_VAR

	RET
;-------------------------------------------------------------------------------

;-------------------------------------------------------------------------------
.INCLUDE	block/damatt_wr.asm
.INCLUDE	block/l_getctime.asm
.INCLUDE	block/l_setctime.asm
.INCLUDE	block/l_telcomm.asm
.INCLUDE	block/tel_wr.asm
.INCLUDE	block/tel_init.asm
;-------------------------------------------------------------------------------
.END
	