.NOLIST
.INCLUDE	include/REG_D22.inc
.INCLUDE	include/MD22U.inc
.INCLUDE	include/CONST.inc

.GLOBAL	REMOTE_PRO
;-------------------------------------------------------------------------------
.EXTERN	GetOneConst
.EXTERN	INIT_DAM_FUNC

;.EXTERN	ANNOUNCE_NUM

.EXTERN	BBBEEP
.EXTERN	BBEEP
.EXTERN	BEEP
.EXTERN	BCVOX_INIT

.EXTERN	CLR_FUNC
.EXTERN	CLR_TIMER

.EXTERN	DAA_SPK
.EXTERN	DAA_OFF
.EXTERN	DAA_ANS_SPK
.EXTERN	DAA_ANS_REC
.EXTERN	DAA_LIN_SPK
.EXTERN	DAA_LIN_REC
.EXTERN	DAM_BIOSFUNC
.EXTERN	DGT_TAB

.EXTERN	GC_CHK
.EXTERN	GET_VPTLEN

.EXTERN	HOOK_ON

.EXTERN	LBEEP
.EXTERN	LINE_START
.EXTERN	LOCAL_PRO

.EXTERN	OGM_SELECT
.EXTERN	OGM_STATUS

.EXTERN	PUSH_FUNC

.EXTERN	REC_START
;.EXTERN REAL_DEL

.EXTERN	SEND_DAT
.EXTERN	SEND_MSGNUM
.EXTERN	SET_TIMER
.EXTERN	STOR_MSG
.EXTERN	STOR_VP

.EXTERN	VOL_TAB
.EXTERN	VPMSG_CHK
.EXTERN	VPMSG_DEL
.EXTERN	VPMSG_CHK
.EXTERN	VPMSG_DELOLD
;---

;-------------------------------------------------------------------------------
.LIST
;-------------------------------------------------------------------------------
.ORG	ADDR_SECOND
.LIST
REMOTE_PRO:
	LAC	MSG			;接线后按ON/OFF(相当于CPC)
	XORL	CMSG_STOP
	BS	ACZ,REMOTE_PRO_STOP

	LAC	MSG
	XORL	CHOOK_OFF
	BS	ACZ,REMOTE_PRO_PHONE	;摘机
	LAC	MSG
	XORL	CPHONE_ON
	BS	ACZ,REMOTE_PRO_PHONE	;免提

	LAC	PRO_VAR
	ANDK	0X0F
	BS	ACZ,REMOTE_PRO0		;0 = IDEL
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW	;1 = play new
	SBHK	1
	BS	ACZ,REMOTE_PROPALL	;2 = play all
	SBHK	5
	BS	ACZ,REMOTE_PROOGM	;7 = record/play OGM
	SBHK	1
	BS	ACZ,REMOTE_PROMONT	;8 = Indoor room monitor
	SBHK	1
	BS	ACZ,REMOTE_PROEXIT	;9 = exit

	RET
;---------------
REMOTE_PRO_STOP:
	LACL	CMSG_CPC
	SAH	MSG
	BS	B1,REMOTE_PRO
;---------------------------------------
REMOTE_PRO_PHONE:
	LAC	MSG
	CALL	STOR_MSG
	
	LACL	CMSG_CPC
	SAH	MSG
	BS	B1,REMOTE_PRO
;===============================================================================
REMOTE_PRO0:
	LAC	MSG
	XORL	CMSG_INIT		;INITIAL(发两声BEEP)
	BS	ACZ,REMOTE_PRO0_INIT
;REMOTE_PRO0_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PRO0_REV_DTMF
;REMOTE_PRO0_2:	
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,REMOTE_PRO0_STOPVP	;VP完
;REMOTE_PRO0_3:	
	LAC	MSG
	XORL	CMSG_BTONE
	BS	ACZ,REMOTE_PRO0_TONE
;REMOTE_PRO0_4:	
	LAC	MSG
	XORL	CMSG_CTONE
	BS	ACZ,REMOTE_PRO0_TONE
;REMOTE_PRO0_5:	
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,REMOTE_PRO0_TMR
;REMOTE_PRO0_6:		
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
		
	RET
;---------------
REMOTE_PRO0_CPC:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACL	0X005
	CALL	STOR_VP
	CALL	VPMSG_CHK
	
	LACK	0X09
	SAH	PRO_VAR

	RET
REMOTE_PRO0_INIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	BBEEP		;BB
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	SEND_ENTERREMOTE
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	RET

;---------------------------------------
REMOTE_PRO0_STOPVP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_REC
	CALL	LINE_START
	
	LACK	0			;开始计时
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	CALL	BCVOX_INIT
	
	RET
	
REMOTE_PRO0_REV_DTMF:
	CALL	CLR_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	CALL	BCVOX_INIT
	
	LAC	DTMF_VAL
	ANDK	0X0F
	SBHK	1
	BS	ACZ,REMOTE_PRO0_PLYNEW		;1---play new
	SBHK	1
	BS	ACZ,REMOTE_PRO0_PLYALL		;2---play all
	SBHK	1
	BS	ACZ,REMOTE_PRO0_PROERA		;3---erase all old messages
	SBHK	4
	BS	ACZ,REMOTE_PRO0_OGM		;7---record/play OGM
	SBHK	1
	BS	ACZ,REMOTE_PRO0_MONITOR		;8---Indoor room monitor
	SBHK	7
	BS	ACZ,REMOTE_PRO0_EXIT		;#---exist
	

	RET
;---------------
REMOTE_PRO0_PLYNEW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	LACK	0X005
	CALL	STOR_VP

	CALL	VPMSG_CHK
	BIT	ANN_FG,12
	BS	TB,REMOTE_PRO0_PLYNEW_1

	CALL	BBBEEP
	
	LACK	0
	SAH	PRO_VAR
	RET
REMOTE_PRO0_PLYNEW_1:
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	LACK	1
	SAH	PRO_VAR

	LACK	0
	SAH	MSG_ID

	
	RET	
	
REMOTE_PRO0_PLYALL:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	LACK	0X005
	CALL	STOR_VP

	CALL	VPMSG_CHK
	LACK	0
	SAH	MSG_ID
	
	BIT	ANN_FG,14
	BS	TB,REMOTE_PRO0_REV_DTMF_2_1

	CALL	BBBEEP
	
	LACK	0
	SAH	PRO_VAR
	
	RET

REMOTE_PRO0_REV_DTMF_2_1:
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	
	LACK	2
	SAH	PRO_VAR

	RET
;---------------------------------------

REMOTE_PRO0_RECMEMO:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	
	BIT	ANN_FG,13
	BS	TB,REMOTE_PROX_DTMF_MFUL
	
	LACK	0X0003
	SAH	PRO_VAR
	CALL	LBEEP		;Lbee...

	RET
REMOTE_PROX_DTMF_MFUL:		;mfull 直接退出
	CALL	BBBEEP
	LACK	0
	SAH	PRO_VAR

	RET
;---------------------------------------
REMOTE_PRO0_PROERA:
	CALL	INIT_DAM_FUNC
	CALL	VPMSG_CHK
;------del old only
	CALL	VPMSG_DELOLD
	CALL	GC_CHK
;---
	CALL	VPMSG_CHK
	CALL	DAA_LIN_SPK
	CALL	BBEEP

	LACK	0X0
	SAH	PRO_VAR
	
	RET
;---------------------------------------
REMOTE_PRO0_OGM:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	LBEEP		;Lbee...
		
	LACK	0X0007
	SAH	PRO_VAR
	
	RET
;---------------------------------------
REMOTE_PRO0_MONITOR:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	LBEEP		;Lbee...
		
	LACK	0X0008
	SAH	PRO_VAR
	
	RET
;---------------------------------------

;---------------------------------------

;---

REMOTE_PRO0_EXIT:
REMOTE_PRO0_TMROUT:		;remote idle time out
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
		
	LACK	0X09
	SAH	PRO_VAR

	CALL	BBEEP

	RET
;---------------------------------------
REMOTE_PRO0_TONE:

	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK

	LACK	0X09
	SAH	PRO_VAR

	LACL	0X005
	CALL	STOR_VP

	RET

;-------
REMOTE_PRO0_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	20		;20s无操作退出
	BZ	SGN,REMOTE_PRO0_TMROUT
	
	RET

;=======================================================================
;11111111111111111111111111111111111111111111111111111111111111111111111
REMOTE_PROPNEW:				;播放新message
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROPNEW_CPC
	
	LAC	PRO_VAR
	SFR	4
	ANDK	0XF
	BS	ACZ,REMOTE_PROPNEW0
	SBHK	1
	BS	ACZ,REMOTE_PROX_PAUSE		;功能暂停
	SBHK	1
	BS	ACZ,REMOTE_PROXTMR_PAUSE	;时间暂停
	
	RET
;---------------
REMOTE_PROPNEW_CPC:
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACL	0X005
	CALL	STOR_VP
	
	CALL	REAL_DEL
	CALL	GC_CHK
	CALL	VPMSG_CHK
	
	LACK	9
	SAH	PRO_VAR
	
	RET
;---------------
REMOTE_PROPNEW0:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROPNEW_OVER
;REMOTE_PROPNEW0_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROPNEW_DTMF
;REMOTE_PROPNEW0_2:
	LAC	MSG
	XORL	CMSG_BTONE		;CMSG_BTONE
	BS	ACZ,REMOTE_PROEXIT_VPSTOP
;REMOTE_PROPNEW0_3:
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROPNEW0_TMR
;REMOTE_PROPNEW0_4:	

	RET
;---------------处理消息
REMOTE_PROPNEW0_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1

	RET

REMOTE_PROPNEW_OVER:
	LAC	MSG_ID
	SBH	MSG_N
	BZ	SGN,REMOTE_PROX_PLYSTOP

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID

REMOTE_PROPLY_LOADNEWVP:
	CALL	BEEP
	LAC	MSG_ID
	ORL	0XFD00
	CALL	STOR_VP

	RET	
;-------
REMOTE_PROPNEW_DTMF:	
	LAC	DTMF_VAL
	ANDK	0X0F
	SBHK	3
	BS	ACZ,REMOTE_PROX_ERAPLYING	;3---erase playing message
	SBHK	1
	BS	ACZ,REMOTE_PROPX_PLYPRE		;4---skip to previous message
	SBHK	1
	BS	ACZ,REMOTE_PROPX_REPEAT		;5---repeat message
	SBHK	1
	BS	ACZ,REMOTE_PROPX_NEXT		;6---skip to next message
	SBHK	8
	BS	ACZ,REMOTE_PROX_DO_PAUSE	;*---remote prompt
	SBHK	1
	BS	ACZ,REMOTE_PROX_PLYSTOP		;#---hang off	

	RET
;---------------
REMOTE_PROX_ERAPLYING:
	LAC	PRO_VAR
	ANDK	0X000F
	SBHK	2
	BS	ACZ,REMOTE_PROX_ERAPLYING_ALL
;REMOTE_PROX_ERAPLYING_NEW:
	LAC	MSG_ID
	CALL	SET_DELMARKNEW
	BS	B1,REMOTE_PROX_ERAPLYING_DONE
	
REMOTE_PROX_ERAPLYING_ALL:
	LAC	MSG_ID
	CALL	SET_DELMARK
REMOTE_PROX_ERAPLYING_DONE:
	CALL	INIT_DAM_FUNC
	
	LACK	0X005
	CALL	STOR_VP
	
	RET
;-------
REMOTE_PROPX_PLYPRE:
	CALL	INIT_DAM_FUNC

	LAC	MSG_ID
	SBHK	1
	BS	ACZ,REMOTE_PROPNEW_PLYPRE_1

	LAC	MSG_ID
	SBHK	1
	SAH	MSG_ID	

REMOTE_PROPNEW_PLYPRE_1:
	BIT	ANN_FG,12
	BZ	TB,REMOTE_PROPLY_LOADVP
	BS	B1,REMOTE_PROPLY_LOADNEWVP
;-------
REMOTE_PROPX_REPEAT:
	CALL	INIT_DAM_FUNC
	BIT	ANN_FG,12
	BZ	TB,REMOTE_PROPLY_LOADVP
	BS	B1,REMOTE_PROPLY_LOADNEWVP
;-------
REMOTE_PROPX_NEXT:
	CALL	INIT_DAM_FUNC
	BIT	ANN_FG,12
	BZ	TB,REMOTE_PROPALL_OVER
	BS	B1,REMOTE_PROPNEW_OVER
;-------
REMOTE_PROX_DO_PAUSE:
	LAC	CONF
	ORL	0X0100
	SAH	CONF
	CALL	DAM_BIOS
	
	LAC	PRO_VAR
	ORK	0X10
	SAH	PRO_VAR
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
	
	RET
REMOTE_PROX_DO_CONPLY:
	LAC	CONF
	ANDL	~(1<<8)
	CALL	DAM_BIOSFUNC
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	RET
;---------------------------------------
REMOTE_PROX_PAUSE:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROX_PAUSE_DTMF
REMOTE_PROX_PAUSE_1:
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROX_PAUSE_TIMER
	
	RET
;---------------
REMOTE_PROX_PAUSE_DTMF:
	
	LAC	DTMF_VAL
	ANDL	0X0F
	SBHK	3
	BS	ACZ,REMOTE_PROX_ERAPLYING	;3---erase playing message
	SBHK	1
	BS	ACZ,REMOTE_PROPX_PLYPRE		;4---skip to previous message
	SBHK	1
	BS	ACZ,REMOTE_PROPX_REPEAT	;5---repeat message
	SBHK	1
	BS	ACZ,REMOTE_PROPX_NEXT		;6---skip to next message
	SBHK	8
	BS	ACZ,REMOTE_PROX_DO_CONPLY	;*---play again
	SBHK	1
	BS	ACZ,REMOTE_PROX_PLYSTOP		;#---hang off	
	
	
	RET
;---------------
REMOTE_PROX_PAUSE_TIMER:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	10
	BS	SGN,REMOTE_PROX_PAUSE_TIMER_1
	
	CALL	INIT_DAM_FUNC
	CALL	BBEEP
	LACK	0
	SAH	PRO_VAR

REMOTE_PROX_PAUSE_TIMER_1:	
	RET
REMOTE_PROX_PAUSE_PLY:
	LAC	CONF
	ANDL	~(1<<8)
	CALL	DAM_BIOSFUNC
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	RET
;-------------------------------------------------------------------------------
REMOTE_PROXTMR_PAUSE:		;时间暂停
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROXTMR_PAUSE_DTMF
REMOTE_PROXTMR_PAUSE_1:
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROXTMR_PAUSE_TIMER

	RET
;---------------
REMOTE_PROXTMR_PAUSE_DTMF:
	LAC	CONF
	ANDL	~(1<<8)
	CALL	DAM_BIOSFUNC
	
	LAC	PRO_VAR
	ANDL	0XFF0F
	SAH	PRO_VAR
	
	LACK	0
	SAH	PRO_VAR1

	RET
REMOTE_PROXTMR_PAUSE_TIMER:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	8
	BZ	SGN,REMOTE_PROXTMR_PAUSE_TIMER_EXIT
	
	RET
REMOTE_PROXTMR_PAUSE_TIMER_EXIT:
	CALL	INIT_DAM_FUNC

	LACL	0X6100
	SAH	CONF
	CALL	DAM_BIOS

	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
		
	LACK	9
	SAH	PRO_VAR

	LACL	0X005
	CALL	STOR_VP

	RET

;=======================================================================
;22222222222222222222222222222222222222222222222222222222222222222222222
REMOTE_PROPALL:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROPALL_CPC
	
	LAC	PRO_VAR
	SFR	4
	ANDK	0XF
	BS	ACZ,REMOTE_PROPALL0		;播放
	SBHK	1
	BS	ACZ,REMOTE_PROX_PAUSE		;功能暂停
	SBHK	1
	BS	ACZ,REMOTE_PROXTMR_PAUSE	;时间暂停

	RET
;---------------
REMOTE_PROPALL_CPC:
	BS	B1,REMOTE_PROPNEW_CPC
;---------------
REMOTE_PROPALL0:	
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROPALL_OVER
;REMOTE_PROPALL0_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROPALL_DTMF
;REMOTE_PROPALL0_2:
	LAC	MSG
	XORL	CMSG_BTONE		;CMSG_BTONE
	BS	ACZ,REMOTE_PROEXIT_VPSTOP
;REMOTE_PROPALL0_3:	
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,REMOTE_PROPALL0_TMR

	RET
;---------------处理消息
REMOTE_PROPALL0_TMR:
	BS	B1,REMOTE_PROPNEW0_TMR

REMOTE_PROPALL_OVER:	
	LAC	MSG_ID
	SBH	MSG_T
	BZ	SGN,REMOTE_PROX_PLYSTOP

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
REMOTE_PROPLY_LOADVP:
	CALL	BEEP
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP

	RET

REMOTE_PROPALL_DTMF:	
	LAC	DTMF_VAL
	ANDL	0X0F
	SBHK	3
	BS	ACZ,REMOTE_PROX_ERAPLYING	;3---erase playing message
	SBHK	1
	BS	ACZ,REMOTE_PROPALL_PLYPRE	;4---skip to previous message
	SBHK	1
	BS	ACZ,REMOTE_PROPALL_REPEAT	;5---repeat message
	SBHK	1
	BS	ACZ,REMOTE_PROPALL_NEXT		;6---skip to next message
	SBHK	8
	BS	ACZ,REMOTE_PROX_DO_PAUSE	;*---do pause
	SBHK	1
	BS	ACZ,REMOTE_PROX_PLYSTOP		;#---hang off	

	RET
;---------------
REMOTE_PROPALL_PLYPRE:		;前一个
	CALL	INIT_DAM_FUNC

	LAC	MSG_ID
	SBHK	1
	BS	ACZ,REMOTE_PROPALL_PLYPRE_1 ;第一个吗?
	
	LAC	MSG_ID
	SBHK	1
	SAH	MSG_ID
	
REMOTE_PROPALL_PLYPRE_1:
	BS	B1,REMOTE_PROPLY_LOADVP
;-------
REMOTE_PROPALL_REPEAT:		;重复当前的一个
	CALL	INIT_DAM_FUNC
	BS	B1,REMOTE_PROPLY_LOADVP
;-------
REMOTE_PROPALL_NEXT:		;下一个
	CALL	INIT_DAM_FUNC
	BS	B1,REMOTE_PROPALL_OVER
;-------
REMOTE_PROX_PLYSTOP:
	CALL	INIT_DAM_FUNC
	;CALL	VP_EndOfMessage
	CALL	BBEEP		;BB
	CALL	VPMSG_CHK
	
	LACL	0X6100
	SAH	CONF
	CALL	DAM_BIOS

	LACK	0
	SAH	PRO_VAR
	SAH	PRO_VAR1
	
	RET
;=======================================================================
;33333333333333333333333333333333333333333333333333333333333333333333333
;=======================================================================
;44444444444444444444444444444444444444444444444444444444444444444444444
;=======================================================================
;55555555555555555555555555555555555555555555555555555555555555555555555
;=======================================================================
;66666666666666666666666666666666666666666666666666666666666666666666666
;=======================================================================
;77777777777777777777777777777777777777777777777777777777777777777777777
REMOTE_PROOGM:
	LAC	PRO_VAR
	SFR	4
	BS	ACZ,REMOTE_PROOGM0PLYVOP	;play LBEEP
	SBHK	1
	BS	ACZ,REMOTE_PROOGM1RECOGM	;record OGM
	SBHK	1
	BS	ACZ,REMOTE_PROOGM2PLYOGM	;play OGM
	
	RET
;---------------------------------------
REMOTE_PROOGM1RECOGM:
	LAC	MSG
	XORL	CMSG_TMR		;TIMER
	BS	ACZ,REMOTE_PROOGM_REC_TMR
	LAC	MSG
;REMOTE_PROOGM1RECOGM_1:
	LAC	MSG
	XORL	CREV_DTMF		;DTMF
	BS	ACZ,REMOTE_PROOGM_REC_DTMF
;REMOTE_PROOGM1RECOGM_2:	
	LAC	MSG
	XORL	CMSG_BTONE
	BS	ACZ,REMOTE_PROOGM_REC_BTONE
;REMOTE_PROOGM1RECOGM_3:	
	LAC	MSG
	XORL	CMSG_CTONE
	BS	ACZ,REMOTE_PROOGM_REC_CTONE
;REMOTE_PROOGM1RECOGM_4:	
	LAC	MSG
	XORL	CREC_FULL		;REC_FULL
	BS	ACZ,REMOTE_PROOGM_RECFULL
;REMOTE_PROOGM1RECOGM_5:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PROOGM_REC_CPC
;REMOTE_PROOGM1RECOGM_6:
	LAC	MSG			;BBBEEP after memful 
	XORL	CVP_STOP
	BS	ACZ,REMOTE_PROOGM_REC_STOP

	RET
;---------------
REMOTE_PROOGM_REC_CPC:
	LAC	PRO_VAR1
	SBHK	2
	BZ	SGN,REMOTE_PROOGM_REC_CPC1
	
	LAC	CONF
	ORL	1<<11
	SAH	CONF
	CALL	DAM_BIOSFUNC
REMOTE_PROOGM_REC_CPC1:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACK	0X005
	CALL	STOR_VP

	CALL	VPMSG_CHK
	
	LACK	0X09
	SAH	PRO_VAR

	RET
;---------------------------------------
REMOTE_PROOGM_REC_CTONE:
REMOTE_PROOGM_REC_BTONE:
	CALL	INIT_DAM_FUNC
	CALL	VPMSG_CHK
	LAC	MSG_T
	CALL	GET_VPTLEN
	SBHK	3
	BZ	SGN,REMOTE_PRO7_RECORD_END
;---删除比3s短的录音
	LAC	MSG_T
	CALL	VPMSG_DEL
	CALL	GC_CHK
REMOTE_PRO7_RECORD_END:
	BS	B1,REMOTE_PRO0_TONE
;---------------------------------------
REMOTE_PROOGM_REC_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	60
	BZ	SGN,REMOTE_PROOGM_REC_STOP

	RET
;---------------------------------------
REMOTE_PROOGM_REC_DTMF:	
	LAC	DTMF_VAL
	XORL	0XFF
	BS	ACZ,REMOTE_PROOGM_REC_DTMF_STOP		;pressed "#"

	RET
;---------------
REMOTE_PROOGM_REC_DTMF_STOP:
	LAC	PRO_VAR1
	SBHK	3
	BZ	SGN,REMOTE_PROOGM_REC_STOP
	
	LAC	CONF
	ORL	1<<11
	CALL	DAM_BIOSFUNC	;录音太短,直接删除	
REMOTE_PROOGM_REC_STOP:		;处理"time over","mfull"
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	LACK	0X0027
	SAH	PRO_VAR

	CALL	OGM_SELECT
	
	CALL	BEEP
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP

	CALL	OGM_SELECT
	BZ	ACZ,MAIN_PRO0_PLAY_OGM1
	
	CALL	INIT_DAM_FUNC
	CALL	BBBEEP		;VP_DefOGM

	LACK	0X0
	SAH	PRO_VAR
MAIN_PRO0_PLAY_OGM1:

	RET	
;---------------
REMOTE_PROOGM_RECFULL:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	LACK	0X0027
	SAH	PRO_VAR

	CALL	OGM_SELECT
	
	CALL	BEEP
	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP

	CALL	OGM_SELECT
	BZ	ACZ,REMOTE_PROOGM_RECFULL1
	
	CALL	INIT_DAM_FUNC
	CALL	BBBEEP		;VP_DefOGM

REMOTE_PROOGM_RECFULL1:
	
	RET
;---------------------------------------
REMOTE_PROOGM0PLYVOP:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,REMOTE_PROOGM0PLYVOP_VPSTOP
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	RET
;---------------------------------------
REMOTE_PROOGM0PLYVOP_VPSTOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_REC
	LACK	0X0017
	SAH	PRO_VAR
;---
	CALL	OGM_SELECT
;-------delete the old OGM fisrt------------
	LAC	MSG_ID
	CALL	VPMSG_DEL
	CALL	GC_CHK
;---set user index data0"OGM_ID"------------
    	LAC	MSG_N
    	ORL	0X8D00
    	CALL	DAM_BIOSFUNC
;---	
	CALL	REC_START
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER

	RET
;---------------------------------------
REMOTE_PROOGM2PLYOGM:
	LAC	MSG
	XORL	CVP_STOP		;CVP_STOP
	BS	ACZ,REMOTE_PROOGM2PLYOGM_VPSTOP
;REMOTE_PRO7_2_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PROOGM_PLY_DTMF
;REMOTE_PRO7_2_2:	
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	RET
;---------------------------------------
REMOTE_PROOGM2PLYOGM_VPSTOP:
	CALL	INIT_DAM_FUNC	
	CALL	BBEEP
	
	LACK	0
	SAH	PRO_VAR
	SAH	PRO_VAR1

	RET

REMOTE_PROOGM_PLY_DTMF:
	LAC	DTMF_VAL
	XORL	0X0FF
	BS	ACZ,REMOTE_PROOGM2PLYOGM_VPSTOP	;#

	RET

REMOTE_PROOGM_PLY_DTMF_3:
	CALL	INIT_DAM_FUNC
	CALL	OGM_SELECT
;---delete the old OGM fisrt------------
	LAC	MSG_ID
	CALL	VPMSG_DEL
	CALL	GC_CHK

	CALL	BBEEP		;BB
	LACK	0
	SAH	PRO_VAR
	
	RET
;=======================================================================
;88888888888888888888888888888888888888888888888888888888888888888888888
REMOTE_PROMONT:
	LAC	MSG			;接线后摘机(相当于CPC)
	XORL	CMSG_CPC
	BS	ACZ,REMOTE_PRO0_CPC
	
	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,REMOTE_PROMONTPLYVP
	SBHK	1
	BS	ACZ,REMOTE_PROMONT_DOING
	
	RET
;---------------------------------------
REMOTE_PROMONT_DOING:
;REMOTE_PROMONT_DOING_1:
	LAC	MSG
	XORL	CREV_DTMF		;CREV_DTMF
	BS	ACZ,REMOTE_PRORMONIT_DTMF
;REMOTE_PROMONT_DOING_2:
	LAC	MSG
	XORL	CMSG_TMR		;TIMER
	BS	ACZ,REMOTE_PRORMONIT_TIMER
;REMOTE_PROMONT_DOING_3:	

	RET
;---------------处理消息
REMOTE_PRORMONIT_DTMF:
	LAC	DTMF_VAL
	ANDK	0X0F
	SBHK	0X0E
	BS	ACZ,REMOTE_PRORMONIT_RESTART	;"*"
	SBHK	1
	BS	ACZ,REMOTE_PRORMONIT_STOP	;"#"

	RET

REMOTE_PRORMONIT_RESTART:
	LACK	0
	SAH	PRO_VAR1

	RET

REMOTE_PRORMONIT_STOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_LIN_SPK
	CALL	BBEEP
	CALL	BCVOX_INIT
	
	LACK	0
	SAH	PRO_VAR
	SAH	PRO_VAR1

	RET
;---------------------------------------
REMOTE_PRORMONIT_TIMER:
	LACL	CTMR_CTONE	;---不让产生VOX,CTONE消息,可产生BTONE
	SAH	TMR_VOX
	SAH	TMR_CTONE
	
	LAC	PRO_VAR1	;计时
	ADHK	1
	SAH	PRO_VAR1
	SBHK	30		;30s计时
	BZ	SGN,REMOTE_PRORMONIT_STOP
		
	RET
;-------
REMOTE_PROMONTPLYVP:
	LAC	MSG
	XORL	CVP_STOP			;CVP_STOP
	BS	ACZ,REMOTE_PROMONTPLYVP_VPSTOP
	
	RET
REMOTE_PROMONTPLYVP_VPSTOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_ROMMOR_ON
	CALL	LINE_START
	
	LACK	0X0018
	SAH	PRO_VAR
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1

	RET
	
;9999999999999999999999999999999999999999999999999999999999999999999999999999999
REMOTE_PROEXIT:
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,REMOTE_PROEXIT_VPSTOP
	
	RET

REMOTE_PROEXIT_VPSTOP:		;exist to idle
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF	
	CALL	HOOK_ON		;hook on
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	CALL	VPMSG_CHK
	CALL	SEND_MSGNUM
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	CALL	CLR_FUNC
	LACL	LOCAL_PRO	;goto local mode
     	CALL	PUSH_FUNC	
	
	LACL	CMODE9
	CALL	DAM_BIOSFUNC

	LACK	0
	SAH	PRO_VAR

	LACL	CMSG_INIT
	CALL	STOR_MSG

	RET
;-------------------------------------------------------------------------------
;===============================================================================
;-------------------------------------------------------------------------------
;       Function : SEND_ENTERREMOTE
;
;       Input  : no
;       Output : no
;-------------------------------------------------------------------------------
SEND_ENTERREMOTE:
	LACK	0X14
	CALL	SEND_DAT
	LACK	0X14
	CALL	SEND_DAT
	
	RET
;-------------------------------------------------------------------------------
DAA_ROMMOR_ON:
	LIPK    6	
				; MIC ->pre-pga -> ad1-pga -> SW4 -> LOUT
				; LIN -> ad2-pga -> ADC2
	OUTK	(1<<4)|(1<<1)|1,SWITCH
		;OUTK	(1<<4)|1,SWITCH
	OUTL	(0x17<<5),LOUTSPK
		;LOPVOL
	;OUTL	0X0F50,AGC
	OUTL	(0XF<<8)|(0X5<<4),AGC
	;	MIC	 AGCM	  AGCL

	RET

;-------------------------------------------------------------------------------
.INCLUDE	block/l_plydel.ASM
;-------------------------------------------------------------------------------

;-------------------------------------------------------------------------------
.END
	