
/***************************************
向下向上翻查来电记录

***************************************/
ORG	0X0800
DIAL_ADDR	==	140
/*
; 向下翻查
LOOK_UP:
	BANK	0
	
	MOV	A,CURRENT_CID
	JPNZ	LOOK_UP_1
	MOV	A,TOTAL_NUM
	JPZ	NO_TEL_NUM

LOOK_UP_1:
	INC	CURRENT_CID
	SUB	A,TOTAL_NUM
	JPNC	END_TEL_LIST
	CALL	#READ_RECORD
	CALL	#DISP_TEL_NUM
	RET

LOOK_DOWN:
	BANK	0
	MOV	A,CURRENT_CID
	JPNZ	LOOK_DOWN_1
	MOV	A,TOTAL_NUM
	JPZ	NO_TEL_NUM
	ADD	A,@1
	MOV	CURRENT_CID,A
LOOK_DOWN_1:
	DEC	CURRENT_CID
	JPZ	END_TEL_LIST
	CALL	#READ_RECORD
	CALL	#DISP_TEL_NUM
	RET

NO_TEL_NUM:
	MOV	PHRASE_NUM,@PH_NO_NUMBER
	MOV	A,@STYLE_CENTER
	CALL	#VGA_PHRASE
	RET
	
END_TEL_LIST:
	MOV	PHRASE_NUM,@PH_END_OF_LIST
	MOV	A,@STYLE_CENTER
	CALL	#VGA_PHRASE
	RET

*/
/***************************************
拨号程序
DIAL_CTRL:
.7	0/1	DISABLE/ENABLE
.6	0/1

.4~.3	0~16	0: START 1~16:拨号的位数
***************************************/
TAB_TONE1:
	TBL
	RETL	0X77	; 0
	RETL	0XA0	; 1
	RETL	0XA0	; 2
	RETL	0XA0	; 3
	RETL	0X91	; 4
	RETL	0X91	; 5
	RETL	0X91	; 6
	RETL	0X83	; 7
	RETL	0X83	; 8
	RETL	0X83	; 9
	RETL	0X77	; *
	RETL	0X77	; #
	RETL	0XA0	; A
	RETL	0X91	; B
	RETL	0X83	; C
	RETL	0X77	; D

TAB_TONE2:
	TBL
	RETL	0X54	; 0
	RETL	0X5D	; 1
	RETL	0X54	; 2
	RETL	0X4C	; 3
	RETL	0X5D	; 4
	RETL	0X54	; 5
	RETL	0X4C	; 6
	RETL	0X5D	; 7
	RETL	0X54	; 8
	RETL	0X4C	; 9
	RETL	0X5D	; *
	RETL	0X4C	; #
	RETL	0X44	; A
	RETL	0X44	; B
	RETL	0X44	; C
	RETL	0X44	; D



DIAL_NUM:
	CIDBANK	1
	PAGEIO	0
	BANK	0
	MOV	_RC,@DIAL_ADDR
	JPNB	_RD,7,DIAL_NUM_RET
	ANDA	_RD,@0X1F
	JPZ	DIAL_NUM_START
	JPB	_RD,6,DIAL_NUM_DIAL
	JMP	DIAL_NUM_PAUSE

DIAL_NUM_START:
	INC	_RD
	MOV	A,@STYLE_RIGHT			; 右对齐
	CALL	#VGA_NUM2
	MOV	TMR_DELAY,@250			; 延时1S
	
	MOV	A,@STYLE_CENTER
	CALL	#VGA_STR
	MOV	A,@(CH_D+0X80)
	CALL	#VGA_STR
	MOV	A,@CH_I
	CALL	#VGA_STR
	MOV	A,@CH_A
	CALL	#VGA_STR
	MOV	A,@CH_L
	CALL	#VGA_STR
	MOV	A,@CH_I
	CALL	#VGA_STR
	MOV	A,@CH_N
	CALL	#VGA_STR
	MOV	A,@CH_G
	CALL	#VGA_STR
	MOV	A,@CH_SCH1
	CALL	#VGA_STR
	MOV	A,@CH_SCH2
	CALL	#VGA_STR
	MOV	A,@CH_END
	CALL	#VGA_STR
	JMP	DIAL_NUM_RET

DIAL_NUM_PAUSE:
	MOV	A,TMR_DELAY
	JPNZ	DIAL_NUM_RET
	SRAM	_RD,6
	ANDA	_RD,@0X1F
	ADD	A,@DIAL_ADDR
	MOV	_RC,A
	;XORA	_RD,@0XFF
	;JPZ	DIAL_NUM_STOP
	MOV	A,_RD
	CALL	TAB_TONE1
	IOW	_IOCD
	MOV	A,_RD
	CALL	TAB_TONE2
	IOW	_IOCE
	SRAM	_STATUS,5			; OPEN TONE1、TONE2
	SRAM	_STATUS,6
	MOV	TMR_DELAY,@25			; 延时100MS
	MOV	A,_RD
	JPNZ	$+2
	MOV	A,@0X80
	CALL	#VGA_NUM2
	
	JMP	DIAL_NUM_RET
DIAL_NUM_DIAL:
	MOV	A,TMR_DELAY
	JPNZ	DIAL_NUM_RET
	CRAM	_STATUS,5
	CRAM	_STATUS,6			; CLOSE TONE1、TONE2
	CRAM	_RD,6
	JPB	_RD,4,DIAL_NUM_STOP		; 超过16位，停止
	INC	_RD
	ANDA	_RD,@0X1F
	ADD	A,@DIAL_ADDR
	MOV	_RC,A
	XORA	_RD,@CH_END
	JPZ	DIAL_NUM_STOP			; 下一位的值==0XFF，停止
	MOV	TMR_DELAY,@25
	JMP	DIAL_NUM_RET

DIAL_NUM_STOP:
	MOV	_RC,@DIAL_ADDR
	CLR	_RD
	MOV	A,@CH_END
	CALL	#VGA_NUM2
	JMP	DIAL_NUM_RET

DIAL_NUM_RET:
	RET
