.NOLIST
.INCLUDE	REG_D20.inc
.INCLUDE	MX93D20.inc
.INCLUDE	MACRO.inc
.INCLUDE	CONST.inc

.GLOBAL	LOCAL_PROMNU
;-------------------------------------------------------------------------------
.EXTERN	ANNOUNCE_NUM

.EXTERN	BBBEEP
.EXTERN	BBEEP
.EXTERN	BEEP
.EXTERN	BCVOX_INIT

.EXTERN CMIN_GET
.EXTERN CHOUR_GET
.EXTERN CWEEK_GET
.EXTERN	CLR_FLAG
.EXTERN	CLR_FUNC
.EXTERN	CLR_TIMER

;.EXTERN	DAA_LIN_SPK
;.EXTERN	DAA_LIN_REC
;.EXTERN	DAA_ROM_MOR
.EXTERN	DAA_SPK
.EXTERN	DAA_REC
.EXTERN	DAA_OFF
.EXTERN	DAM_BIOSFUNC
.EXTERN	DAT_WRITE_STOP
.EXTERN	DEL_ONETEL
.EXTERN	DGT_TAB

.EXTERN	FFW_MANAGE

.EXTERN	HOOK_ON
.EXTERN	HOOK_OFF
.EXTERN HOUR_SET

.EXTERN	GC_CHK
.EXTERN	GetOneConst
;.EXTERN	GET_SEGCODE
.EXTERN	INIT_DAM_FUNC

.EXTERN	LBEEP
.EXTERN	LED_HLDISP
.EXTERN	LINE_START
.EXTERN	LOCAL_PRO

.EXTERN MIN_SET
.EXTERN	OGM_SELECT
.EXTERN	PUSH_FUNC

.EXTERN	REAL_DEL
.EXTERN	REC_START
.EXTERN	REW_MANAGE

.EXTERN SEC_SET
.EXTERN	SET_DELMARK
.EXTERN	SET_DECLTEL
;.EXTERN	SET_LED3
;.EXTERN	SET_LED4
.EXTERN	SET_TIMER
.EXTERN	STORBYTE_DAT
.EXTERN	STOR_MSG
.EXTERN	STOR_VP

.EXTERN	TEL_GC_CHK
.EXTERN	TELNUM_WRITE
.EXTERN	UPDATE_FLASH
.EXTERN	VALUE_SUB
.EXTERN	VALUE_ADD
.EXTERN	VPMSG_CHK
.EXTERN	VPMSG_DEL

.EXTERN WEEK_SET
;---
.EXTERN	VP_AnswerOn
.EXTERN	VP_AnswerOff
.EXTERN	VP_EndOfMessage
.EXTERN	VP_AllOldMessagesErased
.EXTERN	VP_Message
.EXTERN	VP_Messages
.EXTERN	VP_NEW
.EXTERN	VP_NewCodeIs
.EXTERN	VP_No
.EXTERN	VP_Oclock
.EXTERN	VP_WEEK
;---
.LIST
;-------------------------------------------------------------------------------
.ORG	0x5500
;-------------------------------------------------------------------------------
LOCAL_PROMNU:				;MENU设置状态要考虑的消息(PRO_VAR)
	LAC	MSG
	XORL	CRING_IN
	BS	ACZ,MAIN_PROX_RINGIN
	LAC	MSG
	XORL	CMSG_KEY7S
	BS	ACZ,MAIN_PRO9_X_STOP	;STOP
	LAC	MSG
	XORL	CMSG_EXIT
	BS	ACZ,MAIN_PRO9_X_STOP	;STOP

	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_0		;(0Xyy04)reserved
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD		;(0Xyy14)psword set
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME		;(0Xyy24)time set
	
	RET
;-------common respond
MAIN_PROX_RINGIN:
	CALL	INIT_DAM_FUNC
	LACK	0
	SAH	PRO_VAR

	LACL	CMSG_INIT
	CALL	STOR_MSG
	
	RET

LOCAL_PROMNU_VPSTOP:

	LACK	0
	SAH	PRO_VAR1		;计数器清零(按键松开后BEEP结束)	
	CALL	DAA_OFF

	RET
MAIN_PRO9_X_STOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBEEP		;BB

	LACK	0X010
	SAH	PRO_VAR
	
	RET

LOCAL_PROMNU_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	30
	BZ	SGN,MAIN_PRO9_TMROVER
	
	RET
MAIN_PRO9_TMROVER:		;超时退出
	BS	B1,MAIN_PRO9_X_STOP
;-------------------------------------------------------------------------------
LOCAL_PROMNU_0:				;wait for key released

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_PSWORD:
	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_PSWORD_0	;wait
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD_1	;adjust ps1
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD_2	;adjust ps2
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD_3	;adjust ps3
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD_DISP	;Display

	RET

LOCAL_PROMNU_PSWORD_0:
	LAC	MSG
	XORL	CMSG_KEY6S		;Announce ps1
	BS	ACZ,LOCAL_PROMNU_PSWORD_0_CODE
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end
	
	RET
LOCAL_PROMNU_PSWORD_0_CODE:	
	LACL	0X0114
	SAH	PRO_VAR

	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER		;打开定时,按键清零,超时退出	

	RET
;-----------------------------------------------------------
LOCAL_PROMNU_PSWORD_1:
	
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR	;TMR
	
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end
;LOCAL_PROMNU_PSWORD_1_1:		
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_1_X_REW	;Vol-
;LOCAL_PROMNU_PSWORD_1_2:	
	LAC	MSG
	XORL	CMSG_KEY4S
	BS	ACZ,MAIN_PRO9_1_X_FFW	;Vol+
;LOCAL_PROMNU_PSWORD_1_3:
	LAC	MSG
	XORL	CMSG_KEY3S
	BS	ACZ,LOCAL_PROMNU_PSWORD_1_PLAY	;PLAY	

	RET
;---------------
LOCAL_PROMNU_PSWORD_1_PLAY:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK

	LAC	MSG_N
	SAH	NEW1		;暂存,设置完毕退出时保存
;---
	LACL	0X0214
	SAH	PRO_VAR
	LACK	2
	CALL	LED_HLDISP	;---"识别码"

	LAC	PASSWORD
	SFR	4
	ANDK	0X0F
	SAH	MSG_N		;LOAD CURRENT VALUE(ps2)
	CALL	ANNOUNCE_NUM

	RET

MAIN_PRO9_1_X_REW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
MAIN_PRO9_1_X_PREW:
	LACK	0
	SAH	SYSTMP1
	LACK	9
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_SUB
	SAH	MSG_N
	CALL	ANNOUNCE_NUM

	RET
;---
MAIN_PRO9_1_X_FFW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
MAIN_PRO9_1_X_PFFW:
	LACK	0
	SAH	SYSTMP1
	LACK	9
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	ANNOUNCE_NUM

	RET

;-----------------------------------------------------------
LOCAL_PROMNU_PSWORD_2:
	
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR	;TMR
	
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end

;MAIN_PRO9_1_2_1:		
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_1_X_REW	;Vol-
;MAIN_PRO9_1_2_2:	
	LAC	MSG
	XORL	CMSG_KEY4S
	BS	ACZ,MAIN_PRO9_1_X_FFW	;Vol+
;MAIN_PRO9_1_2_3:
	LAC	MSG
	XORL	CMSG_KEY3S
	BS	ACZ,LOCAL_PROMNU_PSWORD_2_PLAY	;PLAY

	RET
;---------------
LOCAL_PROMNU_PSWORD_2_PLAY:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	
	LAC	MSG_N
	SAH	NEW2		;暂存,设置完毕退出时保存
;---
	LACL	0X0314
	SAH	PRO_VAR
	LACK	3
	CALL	LED_HLDISP	;---"识别码"

	LAC	PASSWORD
	ANDK	0X0F
	SAH	MSG_N		;LOAD CURRENT VALUE(ps3)
	CALL	ANNOUNCE_NUM

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_PSWORD_3:
	
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR	;TMR
	
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end

;LOCAL_PROMNU_PSWORD_3_1:		
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_1_X_REW	;Vol-
;LOCAL_PROMNU_PSWORD_3_2:	
	LAC	MSG
	XORL	CMSG_KEY4S
	BS	ACZ,MAIN_PRO9_1_X_FFW	;Vol+
;LOCAL_PROMNU_PSWORD_3_3:	
	LAC	MSG
	XORL	CMSG_KEY3S
	BS	ACZ,LOCAL_PROMNU_PSWORD_3_PLAY	;PLAY

	RET
;---------------
LOCAL_PROMNU_PSWORD_3_PLAY:
	CALL	CLR_TIMER	;clear timer first
	CALL	INIT_DAM_FUNC
	;CALL	DAA_SPK
	LACK	0X005
	CALL	STOR_VP

	LAC	NEW1
	SFL	4
	OR	NEW2
	SFL	4
	OR	MSG_N
	SAH	PASSWORD
;---
	CALL	UPDATE_FLASH
;---
	LACL	1000
	CALL	SET_TIMER	;then set timer

	LACL	0X0414
	SAH	PRO_VAR

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_PSWORD_DISP:
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_PSWORD_DISP_TMR	;TMR
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP			;VP end

	RET
	
LOCAL_PROMNU_PSWORD_DISP_TMR:	
	LAC	PRO_VAR
	SFR	12
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_PSWORD0_DISP	;0X0414
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD1_DISP	;0X1414
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD2_DISP	;0X2414
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_PSWORD3_DISP	;0X3414
	
	RET
LOCAL_PROMNU_PSWORD0_DISP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK

	LACL	0X1414
	SAH	PRO_VAR
	
	LAC	PASSWORD
	SFR	8
	ANDK	0X0F		;LOAD CURRENT VALUE(ps1)
	SAH	MSG_N
	CALL	LED_HLDISP
	
	LAC	MSG_N
	CALL	ANNOUNCE_NUM

	RET
LOCAL_PROMNU_PSWORD1_DISP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	
	LACL	0X2414
	SAH	PRO_VAR
	
	LAC	PASSWORD
	SFR	4
	ANDK	0X0F		;LOAD CURRENT VALUE(ps2)
	SAH	MSG_N
	CALL	LED_HLDISP

	LAC	MSG_N
	CALL	ANNOUNCE_NUM

	RET
LOCAL_PROMNU_PSWORD2_DISP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK

	LACL	0X3414
	SAH	PRO_VAR
	
	LAC	PASSWORD
	ANDK	0X0F		;LOAD CURRENT VALUE(ps3)
	SAH	MSG_N
	CALL	LED_HLDISP

	LAC	MSG_N
	CALL	ANNOUNCE_NUM
	
	RET
LOCAL_PROMNU_PSWORD3_DISP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBEEP
	
	LACK	0X010
	SAH	PRO_VAR
	
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME:			;adjust time

	LAC	PRO_VAR
	SFR	8
	ANDK	0X0F
	BS	ACZ,LOCAL_PROMNU_TIME_0	;wait
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_1	;week
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_2	;hour
	SBHK	1
	BS	ACZ,LOCAL_PROMNU_TIME_3	;minute


	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME_0:		;Wait for "Time" release
	LAC	MSG
	XORL	CMSG_KEY8S
	BS	ACZ,LOCAL_PROMNU_TIME_TIME	;TIME = FFW
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end
	
	RET
LOCAL_PROMNU_TIME_TIME:
	LACL	0X0124
	SAH	PRO_VAR
	
	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME_1:			;adjust week
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR	;TMR
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end
;MAIN_PRO9_2_1_1:		
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_2_1_REW	;Vol-
;MAIN_PRO9_2_1_2:	
	LAC	MSG
	XORL	CMSG_KEY4S
	BS	ACZ,MAIN_PRO9_2_1_FFW	;Vol+
;MAIN_PRO9_2_1_3:
	LAC	MSG
	XORL	CMSG_KEY3S
	BS	ACZ,MAIN_PRO9_2_1_PLAY	;PLAY = CONFIRM
	
	RET
;-------respond9-2-1(week)
MAIN_PRO9_2_1_REW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
MAIN_PRO9_2_1_PREW:
	LACK	0
	SAH	SYSTMP1
	LACK	6
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_SUB
	SAH	MSG_N

	CALL	VP_WEEK

	RET
;---
MAIN_PRO9_2_1_FFW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
MAIN_PRO9_2_1_PFFW:
	LACK	0
	SAH	SYSTMP1
	LACK	6
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	VP_WEEK
	
	RET
;---------------
MAIN_PRO9_2_1_PLAY:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK

	LAC	MSG_N
	SAH	NEW1		;暂存,设置完毕退出时保存
	;CALL	WEEK_SET

	LACL	0X0224
	SAH	PRO_VAR
;---载入调节项	
	CALL	CHOUR_GET
	SAH	MSG_N		;CURRENT VALUE
	CALL	ANNOUNCE_NUM

	LACL	0XB7		;识别码"中下划线"
	SAH	LED_L

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME_2:		;
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR	;TMR
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end
;MAIN_PRO9_2_2_1:		
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_2_2_REW	;Vol-
;MAIN_PRO9_2_2_2:	
	LAC	MSG
	XORL	CMSG_KEY4S
	BS	ACZ,MAIN_PRO9_2_2_FFW	;Vol+
;MAIN_PRO9_2_2_3:
	LAC	MSG
	XORL	CMSG_KEY3S
	BS	ACZ,MAIN_PRO9_2_2_PLAY	;PLAY
	
	RET
;-------respond9-2-2(hour)
MAIN_PRO9_2_2_REW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
MAIN_PRO9_2_2_PREW:
	LACK	0
	SAH	SYSTMP1
	LACK	23
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_SUB
	SAH	MSG_N
	CALL	ANNOUNCE_NUM

	RET
;---------------
MAIN_PRO9_2_2_FFW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
MAIN_PRO9_2_2_PFFW:
	LACK	0
	SAH	SYSTMP1
	LACK	23
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	ANNOUNCE_NUM
	
	RET
;---------------
MAIN_PRO9_2_2_PLAY:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK

	LAC	MSG_N
	SAH	NEW2		;暂存,设置完毕退出时保存
	;CALL	HOUR_SET
	
	LACL	0X0324
	SAH	PRO_VAR
;---载入调节项	
	CALL	CMIN_GET
	SAH	MSG_N		;CURRENT VALUE
	CALL	ANNOUNCE_NUM

	LACL	0XB6		;识别码"上中下划线"
	SAH	LED_L

	RET
;-------------------------------------------------------------------------------
LOCAL_PROMNU_TIME_3:
	LAC	MSG
	XORL	CMSG_TMR
	BS	ACZ,LOCAL_PROMNU_TMR	;TMR
	LAC	MSG
	XORL	CVP_STOP
	BS	ACZ,LOCAL_PROMNU_VPSTOP	;VP end		
;MAIN_PRO9_2_3_1:		
	LAC	MSG
	XORL	CMSG_KEY2S
	BS	ACZ,MAIN_PRO9_2_3_REW	;Vol-
;MAIN_PRO9_2_3_2:	
	LAC	MSG
	XORL	CMSG_KEY4S
	BS	ACZ,MAIN_PRO9_2_3_FFW	;Vol+
;MAIN_PRO9_2_3_3:
	LAC	MSG
	XORL	CMSG_KEY3S
	BS	ACZ,MAIN_PRO9_2_3_PLAY	;PLAY

	RET
;-------respond9-2-3(minute)
MAIN_PRO9_2_3_REW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
MAIN_PRO9_2_3_PREW:
	LACK	0
	SAH	SYSTMP1
	LACK	59
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_SUB
	SAH	MSG_N
	CALL	ANNOUNCE_NUM

	RET
;---------------
MAIN_PRO9_2_3_FFW:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
MAIN_PRO9_2_3_PFFW:
	LACK	0
	SAH	SYSTMP1
	LACK	59
	SAH	SYSTMP2

	LAC	MSG_N
	CALL	VALUE_ADD
	SAH	MSG_N
	CALL	ANNOUNCE_NUM
	
	RET
;---------------
MAIN_PRO9_2_3_PLAY:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
;---Save the value
	LAC	NEW1
	CALL	WEEK_SET
	LAC	NEW2
	CALL	HOUR_SET
	LAC	MSG_N
	CALL	MIN_SET
	LACK	0
	CALL	SEC_SET
;---Announce Time
;---WEEK
	CALL	CWEEK_GET
	CALL	VP_WEEK
;---HOUR
	CALL	CHOUR_GET
	CALL	ANNOUNCE_NUM
;---MINUTE	
	CALL	CMIN_GET
	CALL	ANNOUNCE_NUM
	
	CALL	VP_Oclock
		
	LACK	0X010
	SAH	PRO_VAR
	
	RET

;===============================================================================
	
.END

