.LIST
LOCAL_PRO:
	LAC	PRO_VAR
	ANDK	0X0F
	BS	ACZ,LOCAL_PRO0		;(F0)0 = idle
	SBHK	1
	BS	ACZ,LOCAL_PROPLY	;(F1) = play memo/icm
	SBHK	1
	BS	ACZ,LOCAL_PROREC	;(F2) = record memo
	SBHK	1
	BS	ACZ,LOCAL_PROOGM	;(F3) = record/play OGM
	SBHK	1
	BS	ACZ,LOCAL_PROMNU	;(F4) = for set time and remote code
	SBHK	1
	BS	ACZ,LOCAL_PROTWR	;(F5) = two way record
	SBHK	1
	BS	ACZ,LOCAL_PROEAL	;(F6) = for ERASE all VP
	SBHK	1
	BS	ACZ,LOCAL_PROTXT	;(F7) = for test mode
	
	RET
;---------------事件响应区
LOCAL_PRO0:
	LAC	PRO_VAR
	SFR	4
	ANDK	0X0F
	BS	ACZ,LOCAL_PRO0_0	;0 = idel
	SBHK	1
	BS	ACZ,LOCAL_PRO0_1	;1 = End VP
	SBHK	1
	BS	ACZ,LOCAL_PRO0_2	;2 = VOL
	SBHK	1
	BS	ACZ,LOCAL_PRO0_3	;3 = 2WAY/init(format flash)

	RET
	
LOCAL_PRO0_0:	
	LAC	MSG
	XORL	CMSG_INIT		;INITIAL
	BS	ACZ,LOCAL_PRO0_INIT
LOCAL_PRO0_0_1:	
	LAC	MSG
	XORL	CMSG_KEY2D		;Vol-
	BS	ACZ,LOCAL_PRO0_VOLS
LOCAL_PRO0_0_2:
	LAC	MSG
	XORL	CMSG_KEY8S		;Announce time
	BS	ACZ,LOCAL_PRO0_ANNTIME
	LAC	MSG
	XORL	CMSG_KEY8L		;set time
	BS	ACZ,LOCAL_PRO0_SETTIME
LOCAL_PRO0_0_3:
	LAC	MSG
	XORL	CMSG_KEY4D		;Vol+
	BS	ACZ,LOCAL_PRO0_VOLA
LOCAL_PRO0_0_4:
	LAC	MSG
	XORL	CMSG_KEY1L		;
	BS	ACZ,LOCAL_PRO0_REAALL
LOCAL_PRO0_0_5:
	LAC	MSG
	XORL	CMSG_KEY7S		;on/off
	BS	ACZ,LOCAL_PRO0_ONOFF
	LAC	MSG
	XORL	CMSG_KEY7L		;2way_RECORD
	BS	ACZ,LOCAL_PRO0_ONOFFESC
LOCAL_PRO0_0_6:
	LAC	MSG
	XORL	CMSG_KEY6S		;
	BS	ACZ,LOCAL_PRO0_ANNPSWORD
	LAC	MSG
	XORL	CMSG_KEY6L		;code
	BS	ACZ,LOCAL_PRO0_SETPSWORD
LOCAL_PRO0_0_7:
	LAC	MSG
	XORL	CMSG_KEY5S		;Play OGM
	BS	ACZ,LOCAL_PRO0_PLYOGM
	LAC	MSG
	XORL	CMSG_KEY5L		;Record OGM
	BS	ACZ,LOCAL_PRO0_RECOGM
LOCAL_PRO0_0_8:
	LAC	MSG
	XORL	CMSG_KEY3S		;Play VP
	BS	ACZ,LOCAL_PRO0_PLYMSG
	;BS	ACZ,LOCAL_PRO0_PLYVOP
	LAC	MSG
	XORL	CMSG_KEY3L		;Record VP
	BS	ACZ,LOCAL_PRO0_RECMSG
LOCAL_PRO0_0_16:
	LAC	MSG
	XORL	CMSG_TMR		;CMSG_TMR
	BS	ACZ,LOCAL_PRO0_TMR
LOCAL_PRO0_0_17:
	LAC	MSG
	XORL	CVP_STOP		;VP_STOP
	BS	ACZ,LOCAL_PRO0_VPSTOP
LOCAL_PRO0_0_19:
	LAC	MSG
	XORL	CMSG_TMODE
	BS	ACZ,LOCAL_PRO0_TMODE

;---------------------------------------
	RET
LOCAL_PRO0_1:
	LAC	MSG
	XORL	CVP_STOP		;VP_STOP
	BS	ACZ,LOCAL_PRO0_1_VP_STOP
	LAC	MSG
	XORL	CRING_IN		;VP_STOP
	BS	ACZ,LOCAL_PRO0_1_VP_STOP

	RET
LOCAL_PRO0_1_VP_STOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACK	0
	SAH	PRO_VAR
	
	CALL	UPDATE_FLASH
	BS	B1,LOCAL_PRO0_INIT

;-------------------------------------------------------------------------------
LOCAL_PRO0_2:
	LAC	MSG
	XORL	CMSG_KEY2D		;Vol-
	BS	ACZ,LOCAL_PRO0_VOLS
;-
	LAC	MSG
	XORL	CMSG_KEY8S		;Announce time
	BS	ACZ,LOCAL_PRO0_ANNTIME
	LAC	MSG
	XORL	CMSG_KEY8L		;set time
	BS	ACZ,LOCAL_PRO0_SETTIME
;-
	LAC	MSG
	XORL	CMSG_KEY4D		;Vol+
	BS	ACZ,LOCAL_PRO0_VOLA
;-
	LAC	MSG
	XORL	CMSG_KEY1L		;
	BS	ACZ,LOCAL_PRO0_REAALL
;-
	LAC	MSG
	XORL	CMSG_KEY7S		;on/off
	BS	ACZ,LOCAL_PRO0_ONOFF
	LAC	MSG
	XORL	CMSG_KEY7L		;2way_RECORD/INII
	BS	ACZ,LOCAL_PRO0_ONOFFESC
;-
	LAC	MSG
	XORL	CMSG_KEY6S		;
	BS	ACZ,LOCAL_PRO0_ANNPSWORD
	LAC	MSG
	XORL	CMSG_KEY6L		;on/off
	BS	ACZ,LOCAL_PRO0_SETPSWORD
;-
	LAC	MSG
	XORL	CMSG_KEY5S		;Play OGM
	BS	ACZ,LOCAL_PRO0_PLYOGM
	LAC	MSG
	XORL	CMSG_KEY5L		;Record OGM
	BS	ACZ,LOCAL_PRO0_RECOGM
;-
	LAC	MSG
	XORL	CMSG_KEY3S		;Play VP
	BS	ACZ,LOCAL_PRO0_PLYMSG
	LAC	MSG
	XORL	CMSG_KEY3L		;Record VP
	BS	ACZ,LOCAL_PRO0_RECMSG
;-	
	LAC	MSG
	XORL	CMSG_TMR		;on/off key released
	BS	ACZ,LOCAL_PRO0_2_TMR
	LAC	MSG
	XORL	CVP_STOP		;erase key released
	BS	ACZ,LOCAL_PRO0_2_VPSTOP
	
	LAC	MSG
	XORL	CDISP_VOL
	BS	ACZ,LOCAL_PRO0_2_DISPVOL
	
	LAC	MSG
	XORL	CMSG_TMODE
	BS	ACZ,LOCAL_PRO0_TMODE
	
	RET
;-------
LOCAL_PRO0_2_TMR:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	LACK	0X005
	CALL	STOR_VP
	
	LACK	0X010
	SAH	PRO_VAR

	RET
LOCAL_PRO0_2_VPSTOP:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF
	
	RET
;-------------------------------------------------------------------------------
LOCAL_PRO0_3:
	LAC	MSG
	XORL	CMSG_KEY7S		;on/off release
	BS	ACZ,LOCAL_PRO0_3_2WAY
	LAC	MSG
	XORL	CMSG_TMR		;TMR
	BS	ACZ,LOCAL_PRO0_3_TMR
	
	RET
LOCAL_PRO0_3_TMR:
	LAC	PRO_VAR1
	ADHK	1
	SAH	PRO_VAR1
	SBHK	4
	BZ	SGN,LOCAL_PRO0_3_TMR_FATFLASH

	RET
LOCAL_PRO0_3_TMR_FATFLASH:
	CALL	INIT_DAM_FUNC
	LACL	0X86
	SAH	LED_L		;Didplay "E"

	LACL	CMODE9|1
	CALL	DAM_BIOSFUNC	;清flash……
	
	CALL	SET_DECLTEL
	CALL	INITATT

	CALL	DAA_SPK
	CALL	LBEEP
	LACK	0X010
	SAH	PRO_VAR

	RET
;---------------
LOCAL_PRO0_3_2WAY:
	CALL	INIT_DAM_FUNC
	CALL	VPMSG_CHK
	BIT	ANN_FG,13	;check memoful?
	BS	TB,LOCAL_PRO0_RECMSG_MFUL
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	LBEEP
	
	CALL	CLR_TIMER
	CALL	SET_COMPS
	LACK	0X0005
	SAH	PRO_VAR

	LACL	0XB6	;Didplay "三"
	SAH	LED_L

	CALL	LOAD_LOCF_VP

	RET
;-------------------------------------------------------------------------------	

LOCAL_PRO0_INIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_OFF

	CALL	VPMSG_CHK

	CALL	GET_FILEID
	CALL	SET_FILEID	;set use_dat()
	CALL	VPMSG_CHK

	LACL	1000
	CALL	SET_TIMER
	LACK	0
	SAH	PRO_VAR1
;---
	RET
LOCAL_PRO0_PROPHO:

	RET
;---------------------------------------
LOCAL_PRO0_VPSTOP:
	BS	B1,LOCAL_PRO0_INIT
;---------------------------------------
LOCAL_PRO0_TMODE:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP

	LACL	0X2447
	SAH	VOI_ATT		;RING_CNT/Line_Gain/SPK_Gain/SPK_VOL

	LACL	CMODE9|1
	CALL	DAM_BIOSFUNC	;清flash……

	LACK	0x0007
	SAH	PRO_VAR

	CALL	LOAD_TETF_VP
	
	RET

;-------------------------------------------------------------------------------
LOCAL_PRO0_ANNTIME:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
;---WEEK
	CALL	CWEEK_GET
	CALL	VP_WEEK
;---HOUR
	CALL	CHOUR_GET
	CALL	ANNOUNCE_NUM
;---MINUTE	
	CALL	CMIN_GET
	CALL	ANNOUNCE_NUM
	
	CALL	VP_Oclock
	
	LACK	0X010
	SAH	PRO_VAR
	
	RET
LOCAL_PRO0_SETTIME:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACL	0X005
	CALL	STOR_VP
	
	CALL	CLR_TIMER

	CALL	LOAD_MNUF_VP

	LACK	0X024
	SAH	PRO_VAR

	LACL	0X0F7
	SAH	LED_L		;识别码"下划线"

	CALL	CWEEK_GET
	SAH	MSG_N

	LAC	MSG_N
	CALL	VP_WEEK

	RET
	
LOCAL_PRO0_ANNPSWORD:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	
	LAC	PASSWORD	;Get PS1
	SFR	8
	ANDK	0X0F
	CALL	ANNOUNCE_NUM
		
	LAC	PASSWORD	;Get PS2
	SFR	4
	ANDK	0X0F
	CALL	ANNOUNCE_NUM
		
	LAC	PASSWORD	;Get PS3
	ANDK	0X0F
	CALL	ANNOUNCE_NUM
	
	LACK	0X010
	SAH	PRO_VAR
	
	RET
;---------------------------------------	
LOCAL_PRO0_SETPSWORD:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACL	0X005
	CALL	STOR_VP

	CALL	CLR_TIMER

	CALL	LOAD_MNUF_VP

	LACK	0X014
	SAH	PRO_VAR

	LAC	PASSWORD	;取数据并显示
	SFR	8
	ANDK	0X0F
	SAH	MSG_N
	CALL	ANNOUNCE_NUM
	
	LACK	1
	CALL	LED_HLDISP	;---"识别码"

	RET
;-------------------------------------------------------------------------------
LOCAL_PRO0_REAALL:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	VP_DoYouWantToDelAllMessage
	CALL	CLR_TIMER
	
	CALL	LOAD_LOCF_VP

	LACK	0X006
	SAH	PRO_VAR
	
	RET
;---------------------------------------
LOCAL_PRO0_VOLS:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP
	LACL	1000
	CALL	SET_TIMER
	
	LACK	0X020
	SAH	PRO_VAR
	
	LAC	VOI_ATT
        ANDL	0X07
        SBHK	1		;下限
        BZ	SGN,LOCAL_PROX_VOLS

	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBBEEP	
	
	;LACK	0X0
	;SAH	PRO_VAR
LOCAL_PROX_VOLS:
	
	LACL	CMSG_VOLS
	CALL	STOR_MSG
	
	RET
LOCAL_PRO0_VOLA:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP
	LACL	1000
	CALL	SET_TIMER
	
	LACK	0X020
	SAH	PRO_VAR
	
	LAC	VOI_ATT
        ANDL	0X07
        SBHK	7		;上限
        BS	SGN,LOCAL_PROX_VOLA

	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBBEEP
	
	;LACK	0X0
	;SAH	PRO_VAR
LOCAL_PROX_VOLA:

	LACL	CMSG_VOLA
	CALL	STOR_MSG
	
	RET
LOCAL_PRO0_2_DISPVOL:
	LAC	VOI_ATT
	ANDL	0X07
	CALL	LED_HLDISP
	
	RET
;---------------------------------------
LOCAL_PRO0_ONOFFESC:		;按住ON/OFF持续2秒
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BEEP
	
	LACK	0
	SAH	PRO_VAR1
	LACL	1000
	CALL	SET_TIMER
	LACK	0X0030
	SAH	PRO_VAR

	LACL	0X88	;Didplay "A"
	SAH	LED_L

	RET

;---------------------------------------
LOCAL_PRO0_RECMSG:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	SET_COMPS
	LACK	0X0002
	SAH	PRO_VAR

	CALL	BEEP

	LACL	0XB6	;Didplay "三"
	SAH	LED_L
	
	CALL	LOAD_LOCF_VP

	BIT	ANN_FG,13	;check memoful?
	BS	TB,LOCAL_PRO0_RECMSG_MFUL

	RET
LOCAL_PRO0_RECMSG_MFUL:
	BS	B1,LOCAL_PROWORN
;---------------------------------------
LOCAL_PRO0_RECOGM:
	CALL	INIT_DAM_FUNC
	CALL	BEEP
	CALL	SET_COMPS

;---delete the old OGM fisrt------------
	CALL	OGM_SELECT
	LAC	MSG_ID
	CALL	VPMSG_DEL
	CALL	GC_CHK
	
	CALL	VPMSG_CHK	;check mfull
;---LED_L "rA"
	CALL	DAA_SPK
	LACL	0XB6	;Didplay "三"
	SAH	LED_L

	LACK	0X0003
	SAH	PRO_VAR

	BIT	ANN_FG,13	;check memoful?
	BS	TB,LOCAL_PROWORN
LOCAL_PRO0_RECOGM1:	
	CALL	LOAD_LOCF_VP

	RET
;LOCAL_PRO0_RECOGM_MFUL:	
;	CALL	OGM_SELECT
;	BS	ACZ,LOCAL_PROWORN	;if full and VP not exist you can't record OGM

;	BS	B1,LOCAL_PRO0_RECOGM1
;---------------------------------------
LOCAL_PRO0_PLYOGM:		;准备播放OGM
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACK	0X0023
	SAH	PRO_VAR		;进入播放OGM子功能
	CALL	CLR_TIMER
	CALL	LOAD_LOCF_VP

	CALL	OGM_SELECT

	LAC	MSG_ID
	ORL	0XFE00
	CALL	STOR_VP
;---LED_L "P"
	LACL	0X8C
	SAH	LED_L

	CALL	OGM_SELECT
	BZ	ACZ,MAIN_PRO0_PLAY_OGM1

	CALL	INIT_DAM_FUNC
	;CALL	VP_DefOGM

	CALL	VP_No
	CALL	VP_OutGoingMessage	;outgoing message

MAIN_PRO0_PLAY_OGM1:

	RET
;---------------------------------------
LOCAL_PRO0_TMR:
	LAC	PRO_VAR1
	ADHK	1
	ANDK	0X0F
	SAH	PRO_VAR1
LOCAL_PRO0_TMR0:
	BIT	PRO_VAR1,0
	BS	TB,LOCAL_PRO0_TMR_MSGNT	;MSG_N/MSG_T
	;BS	B1,LOCAL_PRO0_TMR_STAT

	BIT	ANN_FG,13
	BS	TB,LOCAL_PRO0_TMR_FULL	;memory full ?

	BIT	EVENT,9
	BS	TB,LOCAL_PRO0_TMR_OFF	;answer off ?
	BS	B1,LOCAL_PRO0_TMR_ON

;---------------
LOCAL_PRO0_TMR_ON:
	LACL	0X88		;"A"
	SAH	LED_L
	
	RET
;---
LOCAL_PRO0_TMR_OFF:
	LACL	0X0BF		;--
	SAH	LED_L

	RET
;---
LOCAL_PRO0_TMR_FULL:
	LACL	0X8E		;"F"
	SAH	LED_L

	RET
;---
LOCAL_PRO0_TMR4:
	LACL	0X0FF		;LED灭
	SAH	LED_L

	RET
;---------------
LOCAL_PRO0_TMR_MSGNT:
	;BIT	ANN_FG,12
	;BS	TB,LOCAL_PRO0_TMR_MSGN
;LOCAL_PRO0_TMR_MSGT:
	;LAC	MSG_T
	;CALL	NUM_ADJ
	;CALL	LED_HLDISP
	
	;RET
LOCAL_PRO0_TMR_MSGN:
	LAC	MSG_N
	CALL	NUM_ADJ
	CALL	LED_HLDISP
	
	RET
;---------------------------------------
.IF	0
LOCAL_PRO0_PLYVOP:		;???????????????????????????????????????????????
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	LACK	0X0005
	CALL	STOR_VP
	
	LACK	0X0006
	SAH	PRO_VAR	
	
	LACK	0
	SAH	MSG_ID
	
	RET
.ENDIF
;---------------
LOCAL_PRO0_PLYMSG:
	
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	VP_YouHave

	CALL	VPMSG_CHK		;进入播放子功能
	CALL	CLR_FLAG
	CALL	CLR_TIMER
	LACK	0X0001
	SAH	PRO_VAR	

	LACK	0
	SAH	MSG_ID
	SAH	FILE_ID
;--	
	CALL	LOAD_LOCF_VP

	BIT	ANN_FG,12
	BS	TB,LOCAL_PRO0_PLAY_NEW
	BIT	ANN_FG,14
	BS	TB,LOCAL_PRO0_PLAY_ALL
;LOCAL_PRO0_PLYMSG_NO:

	CALL	VP_No
	CALL	VP_Messages
	LACK	0X010
	SAH	PRO_VAR	
	
	RET
;-------play new messages
LOCAL_PRO0_PLAY_NEW:
	LAC	MSG_N
	SBHK	1
	BS	ACZ,LOCAL_PRO0_PLAY_ONENEW
	
	LAC	MSG_N
	CALL	ANNOUNCE_NUM
	CALL	VP_NEW
	CALL	VP_Messages
	
	RET
LOCAL_PRO0_PLAY_ONENEW:
	LAC	MSG_N
	CALL	ANNOUNCE_NUM
	CALL	VP_NEW
	CALL	VP_Message
	
	RET
;-------play old messages
LOCAL_PRO0_PLAY_ALL:
	LAC	MSG_T
	SBHK	1
	BS	ACZ,LOCAL_PRO0_PLAY_ONEALL

	LAC	MSG_T
	CALL	ANNOUNCE_NUM
	CALL	VP_Messages
	
	RET
LOCAL_PRO0_PLAY_ONEALL:
	LAC	MSG_T
	CALL	ANNOUNCE_NUM
	CALL	VP_Message
	
	RET
;---------------------------------------
LOCAL_PRO0_ONOFF:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK

	CALL	CLR_TIMER
	
	LACK	0X010
	SAH	PRO_VAR
	
	LAC	EVENT		;EVENT.9
	XORL	(1<<9)
	SAH	EVENT
	
	BIT	EVENT,9
	BS	TB,LOCAL_PRO0_OFF
;LOCAL_PRO0_ON:
	CALL	VP_AnswerOn

	LACL	0X88		;"A"
	SAH	LED_L
	
	RET
LOCAL_PRO0_OFF:
	CALL	VP_AnswerOff
	
	LACL	0XBF		;"-"
	SAH	LED_L
	
	RET
;-------------------------------------------------------------------------------	
LOCAL_PROEND_BEFORINIT:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBEEP
	
	LACK	0X0
	SAH	PRO_VAR

	RET

;-------------------------------------------------------------------------------
.IF	0
LOCAL_PROVOP:
	LAC	MSG
	XORL	CVP_STOP		;PLAY END
	BS	ACZ,LOCAL_PROVOP_OVER
LOCAL_PROVOP_1:	
	LAC	MSG
	XORL	CMSG_KEY7S		;ON/OFF(stop)
	BS	ACZ,LOCAL_PROVOP_STOP
	
	RET
LOCAL_PROVOP_OVER:
	CALL	INIT_DAM_FUNC

	LAC	MSG_ID
	SBHL	219
	BZ	SGN,LOCAL_PROVOP_STOP

	LAC	MSG_ID			;next message
	ADHK	1
	SAH	MSG_ID
	
	LAC	MSG_ID
	ORL	0XFF00
	CALL	STOR_VP
	
	RET
LOCAL_PROVOP_STOP:
	CALL	INIT_DAM_FUNC
	BS	B1,LOCAL_PROEND_BEFORINIT
.ENDIF
;-------------------------------------------------------------------------------
;LOCAL_PROMNU:
;LOCAL_PROSET:
;	RET
;-------------------------------------------------------------------------------
LOCAL_PROWORN:
	CALL	INIT_DAM_FUNC
	CALL	DAA_SPK
	CALL	BBBEEP
	
	LACK	0X0
	SAH	PRO_VAR
	
	RET
;-------------------------------------------------------------------------------

;-------------------------------------------------------------------------------
	
.END
